/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Euclidean.OSPositiveHalfSpaceScalarFunctionalTensorCandidate

/-!
# Iterated OS positive-half-space scalar-functional tensor candidates

OS-I, printed p. 87, forms the `n`-fold completed tensor powers of
`𝒮(ℝ⁴₊) = 𝒮(ℝ₊) ⊗̂ 𝒮(ℝ³)`. This module records only a fixed left-associated family of supplied
scalar-functional candidate carriers. Index `n : ℕ` denotes `n + 1` intended factors, so index zero
is the one-factor candidate and is not the scalar zero-point component of an OS source sequence.

Every successor retains OS-I's scalar-valued continuous-bilinear extension consequence. Such
extensions do not characterize the completed projective tensor topology. This family neither
inherits the arbitrary-complete-target universal property nor represents OS-I's nuclearity statement.
No completed tensor carrier, associator, permutation equivalence, product-Schwartz identification,
or OS test-space bridge is constructed. Dense pure span derives extension uniqueness within each
chosen candidate, and recursively tensoring the explicit nonzero bump blocks finite-level collapse.
-/

namespace YangMills

noncomputable section

/-- The number of positive-half-space factors represented by zero-based power index `n`. -/
def osPositiveHalfSpaceScalarFunctionalTensorFactorCount (n : ℕ) : ℕ := n + 1

@[simp]
theorem osPositiveHalfSpaceScalarFunctionalTensorFactorCount_zero :
    osPositiveHalfSpaceScalarFunctionalTensorFactorCount 0 = 1 := rfl

@[simp]
theorem osPositiveHalfSpaceScalarFunctionalTensorFactorCount_succ (n : ℕ) :
    osPositiveHalfSpaceScalarFunctionalTensorFactorCount (n + 1) =
      osPositiveHalfSpaceScalarFunctionalTensorFactorCount n + 1 := by
  simp [osPositiveHalfSpaceScalarFunctionalTensorFactorCount, Nat.add_assoc]

/-- Source-facing scalar-functional candidate data indexed by every intended finite positive tensor
power of `𝒮(ℝ⁴₊)`. The family is fixed left-associated: `T 0` is the one-factor candidate and
`T (n+1)` is a complete candidate carrier with scalar extensions for `T n ⊗ T 0`. This structure
does not characterize any completed projective tensor product. -/
structure OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate
    (T : ℕ → Type)
    [∀ n, UniformSpace (T n)] [∀ n, AddCommGroup (T n)] [∀ n, Module ℂ (T n)]
    [∀ n, IsUniformAddGroup (T n)] [∀ n, IsTopologicalAddGroup (T n)]
    [∀ n, ContinuousSMul ℂ (T n)] [∀ n, LocallyConvexSpace ℝ (T n)]
    [∀ n, T2Space (T n)] [∀ n, CompleteSpace (T n)] where
  /-- Index zero is exactly the supplied one-factor scalar-functional candidate. -/
  oneFactor : OSPositiveHalfSpaceScalarFunctionalTensorCandidate (T 0)
  /-- Left-associated pure tensor from the `n+1` factor carrier and one further factor. -/
  stepPure : ∀ n, T n →ₗ[ℂ] T 0 →ₗ[ℂ] T (n + 1)
  /-- Every successor pure-tensor map is jointly continuous. -/
  stepPure_joint_continuous : ∀ n,
    Continuous (fun p : T n × T 0 => stepPure n p.1 p.2)
  /-- Every successor carrier is densely generated by its left-associated pure tensors. -/
  stepDensePureSpan : ∀ n, Dense ((Submodule.span ℂ (Set.range
    (fun p : T n × T 0 => stepPure n p.1 p.2)) :
      Submodule ℂ (T (n + 1))) : Set (T (n + 1)))
  /-- No successor pure tensor collapses two nonzero factors. -/
  stepPure_ne_zero : ∀ n (f : T n) (g : T 0),
    f ≠ 0 → g ≠ 0 → stepPure n f g ≠ 0
  /-- Every jointly continuous scalar-valued bilinear functional extends at each successor. -/
  stepScalarLift : ∀ n, (b : T n →ₗ[ℂ] T 0 →ₗ[ℂ] ℂ) →
    Continuous (fun p : T n × T 0 => b p.1 p.2) → T (n + 1) →L[ℂ] ℂ
  /-- Every successor scalar extension agrees exactly on pure tensors. -/
  stepScalarLift_pure : ∀ n (b : T n →ₗ[ℂ] T 0 →ₗ[ℂ] ℂ)
    (hb : Continuous (fun p : T n × T 0 => b p.1 p.2)) (f : T n) (g : T 0),
      stepScalarLift n b hb (stepPure n f g) = b f g

namespace OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate

variable {T : ℕ → Type}
variable [∀ n, UniformSpace (T n)] [∀ n, AddCommGroup (T n)] [∀ n, Module ℂ (T n)]
variable [∀ n, IsUniformAddGroup (T n)] [∀ n, IsTopologicalAddGroup (T n)]
variable [∀ n, ContinuousSMul ℂ (T n)] [∀ n, LocallyConvexSpace ℝ (T n)]
variable [∀ n, T2Space (T n)] [∀ n, CompleteSpace (T n)]

/-- The explicit nonzero tensor at every positive factor count, recursively left-associated. -/
def iteratedBumpPureTensor (D : OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate T) : ∀ n, T n
  | 0 => D.oneFactor.nonzeroBumpPureTensor
  | n + 1 => D.stepPure n (iteratedBumpPureTensor D n) D.oneFactor.nonzeroBumpPureTensor

@[simp]
theorem iteratedBumpPureTensor_zero
    (D : OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate T) :
    D.iteratedBumpPureTensor 0 = D.oneFactor.nonzeroBumpPureTensor := rfl

@[simp]
theorem iteratedBumpPureTensor_succ
    (D : OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate T) (n : ℕ) :
    D.iteratedBumpPureTensor (n + 1) =
      D.stepPure n (D.iteratedBumpPureTensor n) D.oneFactor.nonzeroBumpPureTensor := rfl

/-- Every finite positive tensor power retains the recursively pure nonzero bump. -/
theorem iteratedBumpPureTensor_ne_zero
    (D : OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate T) :
    ∀ n, D.iteratedBumpPureTensor n ≠ 0
  | 0 => D.oneFactor.nonzeroBumpPureTensor_ne_zero
  | n + 1 => D.stepPure_ne_zero n _ _ (D.iteratedBumpPureTensor_ne_zero n)
      D.oneFactor.nonzeroBumpPureTensor_ne_zero

/-- Agreement on successor pure tensors uniquely determines a scalar-valued extension. -/
theorem stepScalarLift_unique
    (D : OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate T) (n : ℕ)
    (b : T n →ₗ[ℂ] T 0 →ₗ[ℂ] ℂ)
    (hb : Continuous (fun p : T n × T 0 => b p.1 p.2))
    (L : T (n + 1) →L[ℂ] ℂ)
    (hL : ∀ f g, L (D.stepPure n f g) = b f g) :
    L = D.stepScalarLift n b hb := by
  apply ContinuousLinearMap.ext
  intro x
  have hpure : Set.EqOn L (D.stepScalarLift n b hb)
      (Set.range (fun p : T n × T 0 => D.stepPure n p.1 p.2)) := by
    rintro _ ⟨⟨f, g⟩, rfl⟩
    rw [hL f g, D.stepScalarLift_pure n b hb f g]
  have hclosure := ContinuousLinearMap.eqOn_closure_span hpure
  exact hclosure (by
    rw [(D.stepDensePureSpan n).closure_eq]
    exact Set.mem_univ x)

end OSPositiveHalfSpaceIteratedScalarFunctionalTensorCandidate

end

end YangMills
