/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Euclidean.SchwingerSequenceInvolution

/-!
# Finite-stage final topology for scalar Schwinger sequences

OS-I equips finite Schwinger sequences with a direct-sum topology induced by the per-arity test
spaces. This module constructs a preliminary finite-stage final topology: for every finite set of
arities, take the dependent finite product of the corresponding Mathlib Schwartz spaces, map it into
the exact-support sequence carrier, and put the final topology for all such stage maps on that
carrier.

The topology is named and not installed globally. It is not yet identified with OS-I's printed
locally convex direct-sum topology: that comparison still requires topological vector-space
operations, the per-arity source-space comparison, and the completed positive-half-space tensor
products. The universal property proved here is exactly for all finite-stage maps and is not silently
upgraded to the paper's linear-map criterion.
-/

namespace YangMills

/-- The dependent finite product of exact arity Schwartz spaces indexed by a finite stage. -/
abbrev ScalarFiniteSchwartzStage
    (d : EuclideanDimension) (s : Finset ℕ) :=
  (n : {n // n ∈ s}) → ScalarSchwartzTestFunction d n.val

/-- Extend finite-stage data by zero to every natural arity. -/
noncomputable def scalarFiniteSchwartzStageComponent
    (d : EuclideanDimension) (s : Finset ℕ) (x : ScalarFiniteSchwartzStage d s)
    (n : ℕ) : ScalarSchwartzTestFunction d n := by
  classical
  by_cases h : n ∈ s
  · exact x ⟨n, h⟩
  · exact 0

@[simp] theorem scalarFiniteSchwartzStageComponent_of_mem
    (d : EuclideanDimension) (s : Finset ℕ) (x : ScalarFiniteSchwartzStage d s)
    (n : ℕ) (h : n ∈ s) :
    scalarFiniteSchwartzStageComponent d s x n = x ⟨n, h⟩ := by
  simp [scalarFiniteSchwartzStageComponent, h]

@[simp] theorem scalarFiniteSchwartzStageComponent_of_not_mem
    (d : EuclideanDimension) (s : Finset ℕ) (x : ScalarFiniteSchwartzStage d s)
    (n : ℕ) (h : n ∉ s) :
    scalarFiniteSchwartzStageComponent d s x n = 0 := by
  simp [scalarFiniteSchwartzStageComponent, h]

/-- Map a finite dependent product into the exact-support unrestricted sequence carrier. Its stored
support filters out zero entries rather than retaining an arbitrary stage superset. -/
noncomputable def scalarFiniteSchwartzStageToSequence
    (d : EuclideanDimension) (s : Finset ℕ) (x : ScalarFiniteSchwartzStage d s) :
    ScalarFiniteSchwartzSequence d := by
  classical
  exact {
    support := s.filter (fun n => scalarFiniteSchwartzStageComponent d s x n ≠ 0)
    component := scalarFiniteSchwartzStageComponent d s x
    mem_support_iff := by
      intro n
      simp only [Finset.mem_filter]
      constructor
      · exact fun h => h.2
      · intro hnonzero
        refine ⟨?_, hnonzero⟩
        by_contra hnot
        exact hnonzero (by simp [scalarFiniteSchwartzStageComponent, hnot]) }

@[simp] theorem scalarFiniteSchwartzStageToSequence_component
    (d : EuclideanDimension) (s : Finset ℕ) (x : ScalarFiniteSchwartzStage d s)
    (n : ℕ) :
    (scalarFiniteSchwartzStageToSequence d s x).component n =
      scalarFiniteSchwartzStageComponent d s x n :=
  rfl

/-- Exact stage output support is contained in the chosen finite stage. -/
theorem scalarFiniteSchwartzStageToSequence_support_subset
    (d : EuclideanDimension) (s : Finset ℕ) (x : ScalarFiniteSchwartzStage d s) :
    (scalarFiniteSchwartzStageToSequence d s x).support ⊆ s := by
  classical
  intro n h
  exact (Finset.mem_filter.mp h).1

/-- Restrict an exact-support sequence to the finite stage given by its actual support. -/
noncomputable def scalarFiniteSchwartzSequenceToSupportStage
    (d : EuclideanDimension) (f : ScalarFiniteSchwartzSequence d) :
    ScalarFiniteSchwartzStage d f.support :=
  fun n => f.component n.val

/-- Every unrestricted finite sequence is recovered exactly from its actual finite support stage. -/
theorem scalarFiniteSchwartzStage_recover
    (d : EuclideanDimension) (f : ScalarFiniteSchwartzSequence d) :
    scalarFiniteSchwartzStageToSequence d f.support
      (scalarFiniteSchwartzSequenceToSupportStage d f) = f := by
  apply ScalarFiniteSchwartzSequence.ext
  intro n
  rw [scalarFiniteSchwartzStageToSequence_component]
  by_cases h : n ∈ f.support
  · rw [scalarFiniteSchwartzStageComponent_of_mem d f.support _ n h]
    rfl
  · rw [scalarFiniteSchwartzStageComponent_of_not_mem d f.support _ n h,
      f.component_eq_zero_of_not_mem n h]

/-- The final topology generated by every dependent finite-stage product map.

It is reducible only so local explicit-instance proofs can expose the topology lattice expression;
it remains a named structure and is never installed as a global instance. -/
@[reducible] noncomputable def scalarFiniteSchwartzFiniteStageFinalTopology
    (d : EuclideanDimension) : TopologicalSpace (ScalarFiniteSchwartzSequence d) :=
  ⨆ s : Finset ℕ, TopologicalSpace.coinduced
    (scalarFiniteSchwartzStageToSequence d s) inferInstance

/-- Every finite-stage map is continuous into the named final topology. -/
theorem continuous_scalarFiniteSchwartzStageToSequence
    (d : EuclideanDimension) (s : Finset ℕ) :
    @Continuous (ScalarFiniteSchwartzStage d s) (ScalarFiniteSchwartzSequence d)
      inferInstance (scalarFiniteSchwartzFiniteStageFinalTopology d)
      (scalarFiniteSchwartzStageToSequence d s) := by
  rw [continuous_iff_coinduced_le]
  exact le_iSup
    (fun t : Finset ℕ => TopologicalSpace.coinduced
      (scalarFiniteSchwartzStageToSequence d t) inferInstance) s

/-- Universal property of the finite-stage final topology: a map out is continuous exactly when
its composite with every finite-stage map is continuous. -/
theorem continuous_from_scalarFiniteSchwartzFiniteStageFinalTopology_iff
    (d : EuclideanDimension) {Y : Type*} [TopologicalSpace Y]
    (g : ScalarFiniteSchwartzSequence d → Y) :
    @Continuous (ScalarFiniteSchwartzSequence d) Y
        (scalarFiniteSchwartzFiniteStageFinalTopology d) inferInstance g ↔
      ∀ s : Finset ℕ,
        Continuous (g ∘ scalarFiniteSchwartzStageToSequence d s) := by
  unfold scalarFiniteSchwartzFiniteStageFinalTopology
  rw [continuous_iSup_dom]
  apply forall_congr'
  intro s
  exact continuous_coinduced_dom

end YangMills
