/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Foundation.Dimensions
import YangMills.Foundation.DimensionsProbes
import YangMills.Foundation.Signatures
import YangMills.Foundation.SignaturesProbes
import YangMills.Mathematics.LieAlgebraSimplicity
import YangMills.Mathematics.LieAlgebraSimplicityProbes
import YangMills.Mathematics.LieGroupAdjoint
import YangMills.Mathematics.LieGroupAdjointProbes
import YangMills.Mathematics.LieGroupContinuousBracket
import YangMills.Mathematics.LieGroupContinuousBracketProbes
import YangMills.Mathematics.LieGroupSmoothBracket
import YangMills.Mathematics.LieBracketWedge
import YangMills.Mathematics.LieBracketWedgeProbes
import YangMills.Mathematics.ManifoldDifferentialForms
import YangMills.Mathematics.ManifoldDifferentialFormsProbes
import YangMills.Mathematics.ManifoldOneFormExteriorDerivative
import YangMills.Mathematics.ManifoldOneFormExteriorDerivativeProbes
import YangMills.Mathematics.NormedSpaceExteriorDerivative
import YangMills.Mathematics.NormedSpaceExteriorDerivativeProbes
import YangMills.Mathematics.SmoothManifoldDifferentialForms
import YangMills.Mathematics.SmoothManifoldDifferentialFormsProbes
import YangMills.Mathematics.SmoothManifoldDifferentialFormOperations
import YangMills.Mathematics.SmoothManifoldDifferentialFormOperationsProbes
import YangMills.Mathematics.SmoothLieBracketWedge
import YangMills.Mathematics.SmoothLieBracketWedgeProbes
import YangMills.Geometry.LieGroup
import YangMills.Geometry.LieGroupProbes
import YangMills.Geometry.InvariantInnerProduct
import YangMills.Geometry.InvariantInnerProductProbes
import YangMills.Geometry.AdjointBundle
import YangMills.Geometry.AdjointBundleProbes
import YangMills.Geometry.AdjointBundleTopology
import YangMills.Geometry.AdjointBundleTopologyProbes
import YangMills.Geometry.AdjointBundleLocalCoordinates
import YangMills.Geometry.AdjointBundleLocalCoordinatesProbes
import YangMills.Geometry.PrincipalBundleTorsor
import YangMills.Geometry.PrincipalBundleTorsorProbes
import YangMills.Geometry.PrincipalBundleMap
import YangMills.Geometry.PrincipalBundleMapProbes
import YangMills.Geometry.TopologicalPrincipalBundle
import YangMills.Geometry.TopologicalPrincipalBundleProbes
import YangMills.Geometry.SmoothPrincipalBundle
import YangMills.Geometry.SmoothPrincipalBundleProbes
import YangMills.Geometry.SmoothGaugeTransformation
import YangMills.Geometry.SmoothGaugeTransformationProbes
import YangMills.Geometry.PointwisePrincipalConnection
import YangMills.Geometry.PointwisePrincipalConnectionProbes
import YangMills.Geometry.PrincipalCurvature
import YangMills.Geometry.PrincipalCurvatureProbes
import YangMills.Geometry.PrincipalCurvatureStructure
import YangMills.Geometry.PrincipalCurvatureStructureProbes
import YangMills.Audit

/-!
# Yang–Mills acceptance contract

This is the root module for a formal definition of the Yang–Mills problem. It intentionally does
not assert existence of a Yang–Mills theory or a mass gap.
-/

namespace YangMills

end YangMills

audit_yang_mills_axioms
