/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Foundation.Dimensions
import YangMills.Foundation.DimensionsProbes
import YangMills.Foundation.Signatures
import YangMills.Foundation.SignaturesProbes
import YangMills.Mathematics.LieAlgebraSimplicity
import YangMills.Mathematics.LieAlgebraSimplicityProbes
import YangMills.Mathematics.LieGroupAdjoint
import YangMills.Mathematics.LieGroupAdjointProbes
import YangMills.Mathematics.LieGroupAdjointRegularity
import YangMills.Mathematics.LieGroupAdjointRegularityProbes
import YangMills.Mathematics.LieGroupContinuousBracket
import YangMills.Mathematics.LieGroupContinuousBracketProbes
import YangMills.Mathematics.LieGroupSmoothBracket
import YangMills.Mathematics.LieBracketWedge
import YangMills.Mathematics.LieBracketWedgeProbes
import YangMills.Mathematics.ManifoldDifferentialForms
import YangMills.Mathematics.ManifoldDifferentialFormsProbes
import YangMills.Mathematics.ManifoldOneFormExteriorDerivative
import YangMills.Mathematics.ManifoldOneFormExteriorDerivativeProbes
import YangMills.Mathematics.NormedSpaceExteriorDerivative
import YangMills.Mathematics.NormedSpaceExteriorDerivativeProbes
import YangMills.Mathematics.SmoothManifoldDifferentialForms
import YangMills.Mathematics.SmoothManifoldDifferentialFormsProbes
import YangMills.Mathematics.SmoothManifoldDifferentialFormAlongMap
import YangMills.Mathematics.SmoothManifoldDifferentialFormAlongMapProbes
import YangMills.Mathematics.SmoothManifoldDifferentialFormOperations
import YangMills.Mathematics.SmoothManifoldDifferentialFormOperationsProbes
import YangMills.Mathematics.SmoothLieBracketWedge
import YangMills.Mathematics.SmoothLieBracketWedgeProbes
import YangMills.Geometry.LieGroup
import YangMills.Geometry.LieGroupProbes
import YangMills.Geometry.InvariantInnerProduct
import YangMills.Geometry.InvariantInnerProductProbes
import YangMills.Geometry.AdjointBundle
import YangMills.Geometry.AdjointBundleProbes
import YangMills.Geometry.AdjointBundleTopology
import YangMills.Geometry.AdjointBundleTopologyProbes
import YangMills.Geometry.AdjointBundleLocalCoordinates
import YangMills.Geometry.AdjointBundleLocalCoordinatesProbes
import YangMills.Geometry.AdjointBundleLocalTrivialization
import YangMills.Geometry.AdjointBundleLocalTrivializationProbes
import YangMills.Geometry.AdjointBundleTrivialization
import YangMills.Geometry.AdjointBundleTrivializationProbes
import YangMills.Geometry.AdjointBundleTransition
import YangMills.Geometry.AdjointBundleTransitionProbes
import YangMills.Geometry.SmoothAdjointBundleTransition
import YangMills.Geometry.SmoothAdjointBundleTransitionProbes
import YangMills.Geometry.AdjointBundleChartedSpace
import YangMills.Geometry.AdjointBundleChartedSpaceProbes
import YangMills.Geometry.AdjointBundleSmoothAtlas
import YangMills.Geometry.AdjointBundleSmoothAtlasProbes
import YangMills.Geometry.AdjointBundleDependentFiber
import YangMills.Geometry.AdjointBundleDependentFiberProbes
import YangMills.Geometry.AdjointBundleDependentFiberTopology
import YangMills.Geometry.AdjointBundleDependentFiberTopologyProbes
import YangMills.Geometry.AdjointBundleFiberAlgebra
import YangMills.Geometry.AdjointBundleFiberAlgebraProbes
import YangMills.Geometry.AdjointBundleFiberLinearity
import YangMills.Geometry.AdjointBundleFiberLinearityProbes
import YangMills.Geometry.AdjointBundleDependentTrivialization
import YangMills.Geometry.AdjointBundleDependentTrivializationProbes
import YangMills.Geometry.AdjointBundleFiberBundle
import YangMills.Geometry.AdjointBundleFiberBundleProbes
import YangMills.Geometry.AdjointBundleVectorBundle
import YangMills.Geometry.AdjointBundleVectorBundleProbes
import YangMills.Geometry.AdjointBundleSmoothVectorBundle
import YangMills.Geometry.AdjointBundleSmoothVectorBundleProbes
import YangMills.Geometry.AdjointBundleSection
import YangMills.Geometry.AdjointBundleSectionProbes
import YangMills.Geometry.AdjointBundleDifferentialForm
import YangMills.Geometry.AdjointBundleDifferentialFormProbes
import YangMills.Geometry.AdjointBundleSmoothDifferentialForm
import YangMills.Geometry.AdjointBundleSmoothDifferentialFormProbes
import YangMills.Geometry.AdjointBundleDegreeZeroForm
import YangMills.Geometry.AdjointBundleDegreeZeroFormProbes
import YangMills.Geometry.PrincipalBundleTorsor
import YangMills.Geometry.PrincipalBundleTorsorProbes
import YangMills.Geometry.PrincipalBundleMap
import YangMills.Geometry.PrincipalBundleMapProbes
import YangMills.Geometry.TopologicalPrincipalBundle
import YangMills.Geometry.TopologicalPrincipalBundleProbes
import YangMills.Geometry.SmoothPrincipalBundle
import YangMills.Geometry.SmoothPrincipalBundleProbes
import YangMills.Geometry.PrincipalBundleLocalTangentLift
import YangMills.Geometry.PrincipalBundleLocalTangentLiftProbes
import YangMills.Geometry.PrincipalBundleLocalTangentLiftSmooth
import YangMills.Geometry.PrincipalBundleLocalTangentLiftSmoothProbes
import YangMills.Geometry.PrincipalBundleLocalTangentLiftAmbient
import YangMills.Geometry.PrincipalBundleLocalTangentLiftAmbientProbes
import YangMills.Geometry.PrincipalFormLocalLiftSmooth
import YangMills.Geometry.PrincipalFormLocalLiftSmoothProbes
import YangMills.Geometry.SmoothGaugeTransformation
import YangMills.Geometry.SmoothGaugeTransformationProbes
import YangMills.Geometry.PointwisePrincipalConnection
import YangMills.Geometry.PointwisePrincipalConnectionProbes
import YangMills.Geometry.PrincipalCurvature
import YangMills.Geometry.PrincipalCurvatureProbes
import YangMills.Geometry.PrincipalCurvatureStructure
import YangMills.Geometry.PrincipalCurvatureStructureProbes
import YangMills.Geometry.PrincipalTwoFormLiftIndependence
import YangMills.Geometry.PrincipalTwoFormLiftIndependenceProbes
import YangMills.Geometry.PrincipalTwoFormRepresentativeIndependence
import YangMills.Geometry.PrincipalTwoFormRepresentativeIndependenceProbes
import YangMills.Geometry.PrincipalTwoFormPointwiseDescent
import YangMills.Geometry.PrincipalTwoFormPointwiseDescentProbes
import YangMills.Geometry.PrincipalCurvaturePointwiseDescent
import YangMills.Geometry.PrincipalCurvaturePointwiseDescentProbes
import YangMills.Audit

/-!
# Yang–Mills acceptance contract

This is the root module for a formal definition of the Yang–Mills problem. It intentionally does
not assert existence of a Yang–Mills theory or a mass gap.
-/

namespace YangMills

end YangMills

audit_yang_mills_axioms
