/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.CompactSurfaceOrientationReversingBoundaryIdentification
import Mathlib.Topology.Constructions

/-!
# Exact quotient carrier for compact-surface boundary gluing

This file constructs the minimal equivalence-relation quotient of the disjoint union of two surface
carriers generated by an exact orientation-reversing boundary identification. It is the topological
carrier underlying Lévy's phrase “the result of the gluing”. The generators identify precisely the
paired parameterized boundary points; reflexivity, symmetry, and transitivity are supplied only by
`Relation.EqvGen`.

The quotient receives its genuine quotient topology. A universal lift is provided for functions on
the two sides that agree on every paired boundary point. No Hausdorffness, manifold-with-corners
atlas, descended orientation, area measure, probability law, or Yang--Mills model is asserted.
-/

namespace YangMills.Geometry

open scoped Manifold ContDiff

noncomputable section

universe uEL uHL uSL uER uHR uSR uTarget

variable
    {EL : Type uEL} [NormedAddCommGroup EL] [NormedSpace ℝ EL] [FiniteDimensional ℝ EL]
    [MeasurableSpace EL] [BorelSpace EL]
    {HL : Type uHL} [TopologicalSpace HL]
    {SL : Type uSL} [TopologicalSpace SL] [MeasurableSpace SL] [BorelSpace SL]
    {IL : ModelWithCorners ℝ EL HL} [ChartedSpace HL SL] [IsManifold IL ∞ SL]
    [CompactSpace SL] [T2Space SL] [SecondCountableTopology SL]
    {ER : Type uER} [NormedAddCommGroup ER] [NormedSpace ℝ ER] [FiniteDimensional ℝ ER]
    [MeasurableSpace ER] [BorelSpace ER]
    {HR : Type uHR} [TopologicalSpace HR]
    {SR : Type uSR} [TopologicalSpace SR] [MeasurableSpace SR] [BorelSpace SR]
    {IR : ModelWithCorners ℝ ER HR} [ChartedSpace HR SR] [IsManifold IR ∞ SR]
    [CompactSpace SR] [T2Space SR] [SecondCountableTopology SR]

abbrev CompactSurfaceBoundaryIdentification
    (leftSurface : CompactOrientedMeasuredSurfaceData IL SL)
    (leftPresentation : CompactSurfaceBoundaryCirclePresentationData leftSurface)
    (leftOrientation : CompactSurfaceBoundaryOrientationData leftSurface leftPresentation)
    (rightSurface : CompactOrientedMeasuredSurfaceData IR SR)
    (rightPresentation : CompactSurfaceBoundaryCirclePresentationData rightSurface)
    (rightOrientation : CompactSurfaceBoundaryOrientationData rightSurface rightPresentation) :=
  CompactSurfaceOrientationReversingBoundaryIdentificationData
    leftSurface leftPresentation leftOrientation rightSurface rightPresentation rightOrientation

variable
    {leftSurface : CompactOrientedMeasuredSurfaceData IL SL}
    {leftPresentation : CompactSurfaceBoundaryCirclePresentationData leftSurface}
    {leftOrientation : CompactSurfaceBoundaryOrientationData leftSurface leftPresentation}
    {rightSurface : CompactOrientedMeasuredSurfaceData IR SR}
    {rightPresentation : CompactSurfaceBoundaryCirclePresentationData rightSurface}
    {rightOrientation : CompactSurfaceBoundaryOrientationData rightSurface rightPresentation}

/-- The primitive directed gluing relation. Its only generators go from the selected point on the
left surface to its paired point on the right surface. -/
def compactSurfaceBoundaryGluingRelation
    (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
      leftOrientation rightSurface rightPresentation rightOrientation) :
    (SL ⊕ SR) → (SL ⊕ SR) → Prop
  | Sum.inl leftPoint, Sum.inr rightPoint =>
      ∃ (pair : Fin identification.pairCount) (circlePoint : Circle),
        leftPoint = identification.leftBoundaryPoint pair circlePoint ∧
        rightPoint = identification.rightBoundaryPoint pair circlePoint
  | _, _ => False

/-- The least setoid generated by the exact paired-boundary relation. -/
def compactSurfaceBoundaryGluingSetoid
    (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
      leftOrientation rightSurface rightPresentation rightOrientation) : Setoid (SL ⊕ SR) :=
  Relation.EqvGen.setoid (compactSurfaceBoundaryGluingRelation identification)

/-- Exact quotient carrier of the disjoint union by the generated boundary identifications. -/
def CompactSurfaceBoundaryGluingQuotient
    (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
      leftOrientation rightSurface rightPresentation rightOrientation) : Type _ :=
  Quot (Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification))

namespace CompactSurfaceBoundaryGluingQuotient

variable (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
  leftOrientation rightSurface rightPresentation rightOrientation)

instance : TopologicalSpace (CompactSurfaceBoundaryGluingQuotient identification) :=
  instTopologicalSpaceQuot

/-- Canonical quotient projection from the full disjoint union. -/
def projection : SL ⊕ SR → CompactSurfaceBoundaryGluingQuotient identification :=
  Quot.mk _

/-- Canonical map from the whole left surface into the quotient carrier. -/
def leftInclusion : SL → CompactSurfaceBoundaryGluingQuotient identification :=
  fun point => projection identification (Sum.inl point)

/-- Canonical map from the whole right surface into the quotient carrier. -/
def rightInclusion : SR → CompactSurfaceBoundaryGluingQuotient identification :=
  fun point => projection identification (Sum.inr point)

/-- Every exact generator pair is equal in the quotient. -/
theorem paired_boundary_points_equal
    (pair : Fin identification.pairCount) (circlePoint : Circle) :
    leftInclusion identification (identification.leftBoundaryPoint pair circlePoint) =
      rightInclusion identification (identification.rightBoundaryPoint pair circlePoint) := by
  apply Quot.sound
  apply Relation.EqvGen.rel
  exact ⟨pair, circlePoint, rfl, rfl⟩

/-- The quotient projection is continuous for the genuine quotient topology. -/
theorem projection_continuous : Continuous (projection identification) :=
  continuous_quot_mk

/-- The quotient projection is a topological quotient map. -/
theorem projection_isQuotientMap : Topology.IsQuotientMap (projection identification) :=
  isQuotientMap_quot_mk

/-- The full left-surface map is continuous. -/
theorem leftInclusion_continuous : Continuous (leftInclusion identification) :=
  (projection_continuous identification).comp continuous_inl

/-- The full right-surface map is continuous. -/
theorem rightInclusion_continuous : Continuous (rightInclusion identification) :=
  (projection_continuous identification).comp continuous_inr

/-- Universal lift of sidewise functions agreeing on every exact paired boundary point. -/
def lift {Target : Type uTarget}
    (leftFunction : SL → Target) (rightFunction : SR → Target)
    (compatible : ∀ (pair : Fin identification.pairCount) (circlePoint : Circle),
      leftFunction (identification.leftBoundaryPoint pair circlePoint) =
        rightFunction (identification.rightBoundaryPoint pair circlePoint)) :
    CompactSurfaceBoundaryGluingQuotient identification → Target :=
  Quot.lift (Sum.elim leftFunction rightFunction) (by
    intro first second related
    induction related with
    | rel first second generator =>
        rcases first with leftPoint | rightPoint <;>
          rcases second with leftPoint' | rightPoint' <;>
          simp only [compactSurfaceBoundaryGluingRelation] at generator
        obtain ⟨pair, circlePoint, leftEquality, rightEquality⟩ := generator
        simpa [leftEquality, rightEquality] using compatible pair circlePoint
    | refl point => rfl
    | symm first second _ inductionHypothesis => exact inductionHypothesis.symm
    | trans first second third _ _ firstHypothesis secondHypothesis =>
        exact firstHypothesis.trans secondHypothesis)

/-- The universal lift agrees literally with the left function. -/
theorem lift_left {Target : Type uTarget}
    (leftFunction : SL → Target) (rightFunction : SR → Target)
    (compatible : ∀ (pair : Fin identification.pairCount) (circlePoint : Circle),
      leftFunction (identification.leftBoundaryPoint pair circlePoint) =
        rightFunction (identification.rightBoundaryPoint pair circlePoint))
    (point : SL) :
    lift identification leftFunction rightFunction compatible
      (leftInclusion identification point) = leftFunction point :=
  rfl

/-- The universal lift agrees literally with the right function. -/
theorem lift_right {Target : Type uTarget}
    (leftFunction : SL → Target) (rightFunction : SR → Target)
    (compatible : ∀ (pair : Fin identification.pairCount) (circlePoint : Circle),
      leftFunction (identification.leftBoundaryPoint pair circlePoint) =
        rightFunction (identification.rightBoundaryPoint pair circlePoint))
    (point : SR) :
    lift identification leftFunction rightFunction compatible
      (rightInclusion identification point) = rightFunction point :=
  rfl

end CompactSurfaceBoundaryGluingQuotient

end

end YangMills.Geometry
