/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.CompactSurfaceBoundaryOrientation

/-!
# Hostile probes for induced compact-surface boundary orientations
-/

namespace YangMills.Geometry.CompactSurfaceBoundaryOrientation.Probes

open Set
open scoped Manifold ContDiff

noncomputable section

universe uE uH uSurface

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [MeasurableSpace E] [BorelSpace E]
    {H : Type uH} [TopologicalSpace H]
    {Surface : Type uSurface} [TopologicalSpace Surface]
    [MeasurableSpace Surface] [BorelSpace Surface]
    {I : ModelWithCorners ℝ E H} [ChartedSpace H Surface] [IsManifold I ∞ Surface]
    [CompactSpace Surface] [T2Space Surface] [SecondCountableTopology Surface]
    {surface : CompactOrientedMeasuredSurfaceData I Surface}
    {presentation : CompactSurfaceBoundaryCirclePresentationData surface}

omit [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]
  [MeasurableSpace Surface] [BorelSpace Surface] [IsManifold I ∞ Surface]
  [CompactSpace Surface] [T2Space Surface] [SecondCountableTopology Surface] in
/-- The outward certificate retains both the entering negative ray and exiting positive ray on the
exact model-with-corners range. -/
theorem exact_two_sided_outward_ray
    {point : Surface} {vector : TangentSpace I point}
    (outward : IsPreferredChartOutwardBoundaryVector I point vector) :
    ∃ radius : ℝ, 0 < radius ∧
      (∀ time : ℝ, -radius < time → time < 0 →
        extChartAt I point point + time •
          NormedSpace.fromTangentSpace (extChartAt I point point)
            (mfderiv I 𝓘(ℝ, E) (extChartAt I point) point vector) ∈
          interior (Set.range I)) ∧
      (∀ time : ℝ, 0 < time → time < radius →
        extChartAt I point point + time •
          NormedSpace.fromTangentSpace (extChartAt I point point)
            (mfderiv I 𝓘(ℝ, E) (extChartAt I point) point vector) ∉ Set.range I) :=
  outward

omit [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]
  [MeasurableSpace Surface] [BorelSpace Surface] [IsManifold I ∞ Surface]
  [CompactSpace Surface] [T2Space Surface] [SecondCountableTopology Surface] in
/-- A zero tangent is never outward; a bare nonzero-looking field name cannot bypass the two-sided
chart-ray geometry. -/
theorem zero_vector_not_outward (point : Surface) :
    ¬ IsPreferredChartOutwardBoundaryVector I point 0 :=
  not_isPreferredChartOutwardBoundaryVector_zero (I := I) point

omit [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E]
  [MeasurableSpace Surface] [BorelSpace Surface] [IsManifold I ∞ Surface]
  [CompactSpace Surface] [T2Space Surface] [SecondCountableTopology Surface] in
/-- The ray semantics depend only on the positive ray generated by the tangent, not its positive
normalization. -/
theorem positive_rescaling_retains_outward
    {point : Surface} {vector : TangentSpace I point} {scale : ℝ}
    (outward : IsPreferredChartOutwardBoundaryVector I point vector)
    (scale_pos : 0 < scale) :
    IsPreferredChartOutwardBoundaryVector I point (scale • vector) ∧ vector ≠ 0 ∧
      (IsPreferredChartOutwardBoundaryVector I point (scale • vector) ↔
        IsPreferredChartOutwardBoundaryVector I point vector) :=
  ⟨outward.smul_of_pos scale_pos, outward.ne_zero,
    isPreferredChartOutwardBoundaryVector_smul_iff scale_pos⟩

/-- In the concrete Euclidean half-space model, the two-sided ray certificate is exactly the
strict outward sign of the charted tangent's zeroth coordinate. -/
theorem exact_halfSpace_outward_sign
    {n : ℕ} [NeZero n]
    {BoundarySurface : Type uSurface} [TopologicalSpace BoundarySurface]
    [ChartedSpace (EuclideanHalfSpace n) BoundarySurface]
    {point : BoundarySurface} {vector : TangentSpace (𝓡∂ n) point}
    (boundary : (extChartAt (𝓡∂ n) point point) 0 = 0) :
    IsPreferredChartOutwardBoundaryVector (𝓡∂ n) point vector ↔
      (NormedSpace.fromTangentSpace (extChartAt (𝓡∂ n) point point)
        (mfderiv (𝓡∂ n) 𝓘(ℝ, EuclideanSpace ℝ (Fin n))
          (extChartAt (𝓡∂ n) point) point vector)) 0 < 0 :=
  isPreferredChartOutwardBoundaryVector_euclideanHalfSpace_iff boundary

/-- A charted tangent with nonnegative normal coordinate cannot bypass the exact two-sided
half-space ray predicate. -/
theorem nonnegative_halfSpace_coordinate_blocked
    {n : ℕ} [NeZero n]
    {BoundarySurface : Type uSurface} [TopologicalSpace BoundarySurface]
    [ChartedSpace (EuclideanHalfSpace n) BoundarySurface]
    {point : BoundarySurface} {vector : TangentSpace (𝓡∂ n) point}
    (boundary : (extChartAt (𝓡∂ n) point point) 0 = 0)
    (nonnegative : 0 ≤
      (NormedSpace.fromTangentSpace (extChartAt (𝓡∂ n) point point)
        (mfderiv (𝓡∂ n) 𝓘(ℝ, EuclideanSpace ℝ (Fin n))
          (extChartAt (𝓡∂ n) point) point vector)) 0) :
    ¬ IsPreferredChartOutwardBoundaryVector (𝓡∂ n) point vector := by
  rw [isPreferredChartOutwardBoundaryVector_euclideanHalfSpace_iff boundary]
  exact not_lt_of_ge nonnegative

/-- Outwardness computed in any two eligible overlapping half-space atlas charts agrees at every
actual manifold boundary point. -/
theorem exact_atlas_chart_outward_invariance
    {n : ℕ} [NeZero n]
    {BoundarySurface : Type uSurface} [TopologicalSpace BoundarySurface]
    [ChartedSpace (EuclideanHalfSpace n) BoundarySurface]
    [IsManifold (𝓡∂ n) 1 BoundarySurface]
    {e e' : OpenPartialHomeomorph BoundarySurface (EuclideanHalfSpace n)}
    {point : BoundarySurface}
    (he : e ∈ atlas (EuclideanHalfSpace n) BoundarySurface)
    (he' : e' ∈ atlas (EuclideanHalfSpace n) BoundarySurface)
    (hxe : point ∈ e.source) (hxe' : point ∈ e'.source)
    (boundary : point ∈ (𝓡∂ n).boundary BoundarySurface)
    {vector : TangentSpace (𝓡∂ n) point} :
    IsChartOutwardBoundaryVector e' point vector ↔
      IsChartOutwardBoundaryVector e point vector :=
  isChartOutwardBoundaryVector_iff_of_mem_boundary he he' hxe hxe' boundary

/-- No eligible atlas chart may disagree with the preferred-chart outward predicate at an actual
boundary point. -/
theorem changed_chart_outward_blocked
    {n : ℕ} [NeZero n]
    {BoundarySurface : Type uSurface} [TopologicalSpace BoundarySurface]
    [ChartedSpace (EuclideanHalfSpace n) BoundarySurface]
    [IsManifold (𝓡∂ n) 1 BoundarySurface]
    {e : OpenPartialHomeomorph BoundarySurface (EuclideanHalfSpace n)}
    {point : BoundarySurface}
    (he : e ∈ atlas (EuclideanHalfSpace n) BoundarySurface)
    (hxe : point ∈ e.source)
    (boundary : point ∈ (𝓡∂ n).boundary BoundarySurface)
    {vector : TangentSpace (𝓡∂ n) point}
    (chartOutward : IsChartOutwardBoundaryVector e point vector)
    (preferredNotOutward : ¬ IsPreferredChartOutwardBoundaryVector (𝓡∂ n) point vector) : False :=
  preferredNotOutward
    ((isChartOutwardBoundaryVector_iff_preferred he hxe boundary).mp chartOutward)

/-- The positive circle tangent is a genuine smooth nonvanishing tangent-bundle field, separately
for each exact component. -/
theorem exact_positive_circle_tangent
    (orientation : CompactSurfaceBoundaryOrientationData surface presentation)
    (component : surface.BoundaryComponent) :
    ContMDiff (𝓡 1) ((𝓡 1).prod 𝓘(ℝ, EuclideanSpace ℝ (Fin 1))) ∞
        (fun circlePoint =>
          (⟨circlePoint, orientation.positiveCircleTangent component circlePoint⟩ :
            TangentBundle (𝓡 1) Circle)) ∧
      ∀ circlePoint, orientation.positiveCircleTangent component circlePoint ≠ 0 :=
  ⟨orientation.positiveCircleTangent_smooth component,
    orientation.positiveCircleTangent_ne_zero component⟩

/-- The outward field is smooth along the exact ambient parameterization and every value carries
the actual two-sided outward certificate. -/
theorem exact_smooth_outward_field
    (orientation : CompactSurfaceBoundaryOrientationData surface presentation)
    (component : surface.BoundaryComponent) :
    ContMDiff (𝓡 1) (I.prod 𝓘(ℝ, E)) ∞
        (fun circlePoint =>
          (⟨presentation.parameterization component circlePoint,
            orientation.outwardBoundaryVector component circlePoint⟩ :
            TangentBundle I Surface)) ∧
      ∀ circlePoint,
        IsPreferredChartOutwardBoundaryVector I
          (presentation.parameterization component circlePoint)
          (orientation.outwardBoundaryVector component circlePoint) :=
  ⟨orientation.outwardBoundaryVector_smooth component,
    orientation.outwardBoundaryVector_isOutward component⟩

/-- For a Euclidean-half-space surface, the exact boundary presentation itself forces every
stored outward field value to have the strict outward coordinate sign. -/
theorem exact_presented_boundary_outward_sign
    {n : ℕ} [NeZero n]
    {BoundarySurface : Type uSurface} [TopologicalSpace BoundarySurface]
    [MeasurableSpace (EuclideanSpace ℝ (Fin n))]
    [BorelSpace (EuclideanSpace ℝ (Fin n))]
    [MeasurableSpace BoundarySurface] [BorelSpace BoundarySurface]
    [ChartedSpace (EuclideanHalfSpace n) BoundarySurface]
    [IsManifold (𝓡∂ n) ∞ BoundarySurface] [CompactSpace BoundarySurface]
    [T2Space BoundarySurface] [SecondCountableTopology BoundarySurface]
    {boundarySurface : CompactOrientedMeasuredSurfaceData (𝓡∂ n) BoundarySurface}
    {boundaryPresentation : CompactSurfaceBoundaryCirclePresentationData boundarySurface}
    (orientation : CompactSurfaceBoundaryOrientationData boundarySurface boundaryPresentation)
    (component : boundarySurface.BoundaryComponent) (circlePoint : Circle) :
    (NormedSpace.fromTangentSpace
      (extChartAt (𝓡∂ n) (boundaryPresentation.parameterization component circlePoint)
        (boundaryPresentation.parameterization component circlePoint))
      (mfderiv (𝓡∂ n) 𝓘(ℝ, EuclideanSpace ℝ (Fin n))
        (extChartAt (𝓡∂ n) (boundaryPresentation.parameterization component circlePoint))
        (boundaryPresentation.parameterization component circlePoint)
        (orientation.outwardBoundaryVector component circlePoint))) 0 < 0 :=
  orientation.outwardBoundaryVector_charted_zeroCoordinate_neg component circlePoint

/-- Boundary orientation is induced by the ordered pair `(outward, pushed tangent)` and the exact
surface orientation form. -/
theorem exact_induced_orientation_sign
    (orientation : CompactSurfaceBoundaryOrientationData surface presentation)
    (component : surface.BoundaryComponent) (circlePoint : Circle) :
    0 < surface.orientationForm.toForm
      (presentation.parameterization component circlePoint)
      ![orientation.outwardBoundaryVector component circlePoint,
        orientation.pushedPositiveBoundaryTangent component circlePoint] :=
  orientation.orientationForm_outward_pushedPositive_pos component circlePoint

/-- Neither vector in the oriented boundary frame may collapse to zero. -/
theorem exact_oriented_frame_nondegenerate
    (orientation : CompactSurfaceBoundaryOrientationData surface presentation)
    (component : surface.BoundaryComponent) (circlePoint : Circle) :
    orientation.outwardBoundaryVector component circlePoint ≠ 0 ∧
      orientation.pushedPositiveBoundaryTangent component circlePoint ≠ 0 :=
  ⟨orientation.outwardBoundaryVector_ne_zero component circlePoint,
    orientation.pushedPositiveBoundaryTangent_ne_zero component circlePoint⟩

/-- An unrelated ambient tangent field cannot replace the designated outward field without an
actual equality proof. -/
theorem unrelated_outward_field_blocked
    (orientation : CompactSurfaceBoundaryOrientationData surface presentation)
    (component : surface.BoundaryComponent) (circlePoint : Circle)
    (wrong : TangentSpace I (presentation.parameterization component circlePoint))
    (different : wrong ≠ orientation.outwardBoundaryVector component circlePoint)
    (claimed : wrong = orientation.outwardBoundaryVector component circlePoint) : False :=
  different claimed

end

end YangMills.Geometry.CompactSurfaceBoundaryOrientation.Probes
