/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.CompactSurfaceOrientationReversingBoundaryIdentification
import Mathlib.Topology.Constructions
import Mathlib.Topology.Maps.Basic

/-!
# Exact quotient carrier for compact-surface boundary gluing

This file constructs the minimal equivalence-relation quotient of the disjoint union of two surface
carriers generated by an exact orientation-reversing boundary identification. It is the topological
carrier underlying Lévy's phrase “the result of the gluing”. The generators identify precisely the
paired parameterized boundary points; reflexivity, symmetry, and transitivity are supplied only by
`Relation.EqvGen`.

The quotient receives its genuine quotient topology. Its exact matching relation is characterized
and proved closed; compact equivalence classes and a closed projection then derive Hausdorffness.
Compactness, connectedness, and closed side embeddings are also derived. A universal lift is
provided for compatible sidewise functions. No manifold-with-corners atlas, descended orientation,
area measure, probability law, or Yang--Mills model is asserted.
-/

namespace YangMills.Geometry

open scoped Manifold ContDiff

noncomputable section

universe uEL uHL uSL uER uHR uSR uTarget

variable
    {EL : Type uEL} [NormedAddCommGroup EL] [NormedSpace ℝ EL] [FiniteDimensional ℝ EL]
    [MeasurableSpace EL] [BorelSpace EL]
    {HL : Type uHL} [TopologicalSpace HL]
    {SL : Type uSL} [TopologicalSpace SL] [MeasurableSpace SL] [BorelSpace SL]
    {IL : ModelWithCorners ℝ EL HL} [ChartedSpace HL SL] [IsManifold IL ∞ SL]
    [CompactSpace SL] [T2Space SL] [SecondCountableTopology SL]
    {ER : Type uER} [NormedAddCommGroup ER] [NormedSpace ℝ ER] [FiniteDimensional ℝ ER]
    [MeasurableSpace ER] [BorelSpace ER]
    {HR : Type uHR} [TopologicalSpace HR]
    {SR : Type uSR} [TopologicalSpace SR] [MeasurableSpace SR] [BorelSpace SR]
    {IR : ModelWithCorners ℝ ER HR} [ChartedSpace HR SR] [IsManifold IR ∞ SR]
    [CompactSpace SR] [T2Space SR] [SecondCountableTopology SR]

abbrev CompactSurfaceBoundaryIdentification
    (leftSurface : CompactOrientedMeasuredSurfaceData IL SL)
    (leftPresentation : CompactSurfaceBoundaryCirclePresentationData leftSurface)
    (leftOrientation : CompactSurfaceBoundaryOrientationData leftSurface leftPresentation)
    (rightSurface : CompactOrientedMeasuredSurfaceData IR SR)
    (rightPresentation : CompactSurfaceBoundaryCirclePresentationData rightSurface)
    (rightOrientation : CompactSurfaceBoundaryOrientationData rightSurface rightPresentation) :=
  CompactSurfaceOrientationReversingBoundaryIdentificationData
    leftSurface leftPresentation leftOrientation rightSurface rightPresentation rightOrientation

variable
    {leftSurface : CompactOrientedMeasuredSurfaceData IL SL}
    {leftPresentation : CompactSurfaceBoundaryCirclePresentationData leftSurface}
    {leftOrientation : CompactSurfaceBoundaryOrientationData leftSurface leftPresentation}
    {rightSurface : CompactOrientedMeasuredSurfaceData IR SR}
    {rightPresentation : CompactSurfaceBoundaryCirclePresentationData rightSurface}
    {rightOrientation : CompactSurfaceBoundaryOrientationData rightSurface rightPresentation}

/-- The primitive directed gluing relation. Its only generators go from the selected point on the
left surface to its paired point on the right surface. -/
def compactSurfaceBoundaryGluingRelation
    (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
      leftOrientation rightSurface rightPresentation rightOrientation) :
    (SL ⊕ SR) → (SL ⊕ SR) → Prop
  | Sum.inl leftPoint, Sum.inr rightPoint =>
      ∃ (pair : Fin identification.pairCount) (circlePoint : Circle),
        leftPoint = identification.leftBoundaryPoint pair circlePoint ∧
        rightPoint = identification.rightBoundaryPoint pair circlePoint
  | _, _ => False

/-- The least setoid generated by the exact paired-boundary relation. -/
def compactSurfaceBoundaryGluingSetoid
    (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
      leftOrientation rightSurface rightPresentation rightOrientation) : Setoid (SL ⊕ SR) :=
  Relation.EqvGen.setoid (compactSurfaceBoundaryGluingRelation identification)

/-- Exact quotient carrier of the disjoint union by the generated boundary identifications. -/
def CompactSurfaceBoundaryGluingQuotient
    (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
      leftOrientation rightSurface rightPresentation rightOrientation) : Type _ :=
  Quot (Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification))

namespace CompactSurfaceBoundaryGluingQuotient

variable (identification : CompactSurfaceBoundaryIdentification leftSurface leftPresentation
  leftOrientation rightSurface rightPresentation rightOrientation)

instance : TopologicalSpace (CompactSurfaceBoundaryGluingQuotient identification) :=
  instTopologicalSpaceQuot

/-- Compactness descends from the compact disjoint union through the continuous surjective quotient
projection. -/
instance compactSurfaceBoundaryGluingQuotientCompactSpace :
    CompactSpace (CompactSurfaceBoundaryGluingQuotient identification) :=
  isCompact_univ_iff.mp (by
    have compactImage := (isCompact_univ : IsCompact (Set.univ : Set (SL ⊕ SR))).image
      (continuous_quot_mk : Continuous
        (Quot.mk (Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification))))
    have compactRange : IsCompact
        (Set.range (Quot.mk
          (Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification)))) := by
      simpa only [Set.image_univ] using compactImage
    rw [Quot.mk_surjective.range_eq] at compactRange
    exact compactRange)

/-- Canonical quotient projection from the full disjoint union. -/
def projection : SL ⊕ SR → CompactSurfaceBoundaryGluingQuotient identification :=
  Quot.mk _

/-- Canonical map from the whole left surface into the quotient carrier. -/
def leftInclusion : SL → CompactSurfaceBoundaryGluingQuotient identification :=
  fun point => projection identification (Sum.inl point)

/-- Canonical map from the whole right surface into the quotient carrier. -/
def rightInclusion : SR → CompactSurfaceBoundaryGluingQuotient identification :=
  fun point => projection identification (Sum.inr point)

/-- Every exact generator pair is equal in the quotient. -/
theorem paired_boundary_points_equal
    (pair : Fin identification.pairCount) (circlePoint : Circle) :
    leftInclusion identification (identification.leftBoundaryPoint pair circlePoint) =
      rightInclusion identification (identification.rightBoundaryPoint pair circlePoint) := by
  apply Quot.sound
  apply Relation.EqvGen.rel
  exact ⟨pair, circlePoint, rfl, rfl⟩

/-- The quotient projection is continuous for the genuine quotient topology. -/
theorem projection_continuous : Continuous (projection identification) :=
  continuous_quot_mk

/-- The quotient projection is a topological quotient map. -/
theorem projection_isQuotientMap : Topology.IsQuotientMap (projection identification) :=
  isQuotientMap_quot_mk

/-- The full left-surface map is continuous. -/
theorem leftInclusion_continuous : Continuous (leftInclusion identification) :=
  (projection_continuous identification).comp continuous_inl

/-- The full right-surface map is continuous. -/
theorem rightInclusion_continuous : Continuous (rightInclusion identification) :=
  (projection_continuous identification).comp continuous_inr

/-- One primitive gluing edge leaves any fixed left endpoint with a unique right endpoint. -/
theorem primitive_leftEndpoint_unique {left : SL} {right₁ right₂ : SR}
    (first : compactSurfaceBoundaryGluingRelation identification
      (Sum.inl left) (Sum.inr right₁))
    (second : compactSurfaceBoundaryGluingRelation identification
      (Sum.inl left) (Sum.inr right₂)) : right₁ = right₂ := by
  rcases first with ⟨pair₁, z₁, left₁, right₁eq⟩
  rcases second with ⟨pair₂, z₂, left₂, right₂eq⟩
  have pair_eq : pair₁ = pair₂ := by
    by_contra pair_ne
    have component_ne : identification.leftComponent pair₁ ≠
        identification.leftComponent pair₂ := by
      intro component_eq
      exact pair_ne (identification.leftComponent_injective component_eq)
    have disjoint := leftPresentation.parameterization_ranges_disjoint component_ne
    have mem₁ : left ∈ Set.range (leftPresentation.parameterization
        (identification.leftComponent pair₁)) := ⟨z₁, left₁.symm⟩
    have mem₂ : left ∈ Set.range (leftPresentation.parameterization
        (identification.leftComponent pair₂)) := ⟨z₂, left₂.symm⟩
    exact Set.disjoint_left.mp disjoint mem₁ mem₂
  subst pair₂
  have z_eq : z₁ = z₂ := by
    apply leftPresentation.parameterization_injective (identification.leftComponent pair₁)
    exact left₁.symm.trans left₂
  subst z₂
  exact right₁eq.trans right₂eq.symm

/-- One primitive gluing edge enters any fixed right endpoint from a unique left endpoint. -/
theorem primitive_rightEndpoint_unique {left₁ left₂ : SL} {right : SR}
    (first : compactSurfaceBoundaryGluingRelation identification
      (Sum.inl left₁) (Sum.inr right))
    (second : compactSurfaceBoundaryGluingRelation identification
      (Sum.inl left₂) (Sum.inr right)) : left₁ = left₂ := by
  rcases first with ⟨pair₁, z₁, left₁eq, right₁⟩
  rcases second with ⟨pair₂, z₂, left₂eq, right₂⟩
  have pair_eq : pair₁ = pair₂ := by
    by_contra pair_ne
    have component_ne : identification.rightComponent pair₁ ≠
        identification.rightComponent pair₂ := by
      intro component_eq
      exact pair_ne (identification.rightComponent_injective component_eq)
    have disjoint := rightPresentation.parameterization_ranges_disjoint component_ne
    have mem₁ : right ∈ Set.range (rightPresentation.parameterization
        (identification.rightComponent pair₁)) :=
      ⟨identification.circleDiffeomorphism pair₁ z₁, right₁.symm⟩
    have mem₂ : right ∈ Set.range (rightPresentation.parameterization
        (identification.rightComponent pair₂)) :=
      ⟨identification.circleDiffeomorphism pair₂ z₂, right₂.symm⟩
    exact Set.disjoint_left.mp disjoint mem₁ mem₂
  subst pair₂
  have mapped_eq : identification.circleDiffeomorphism pair₁ z₁ =
      identification.circleDiffeomorphism pair₁ z₂ := by
    apply rightPresentation.parameterization_injective (identification.rightComponent pair₁)
    exact right₁.symm.trans right₂
  have z_eq : z₁ = z₂ := (identification.circleDiffeomorphism pair₁).injective mapped_eq
  subst z₂
  exact left₁eq.trans left₂eq.symm

/-- Explicit equivalence relation generated by gluing: equality or exactly one primitive edge in
either direction. -/
def explicitGluingEquivalence (first second : SL ⊕ SR) : Prop :=
  first = second ∨
    compactSurfaceBoundaryGluingRelation identification first second ∨
    compactSurfaceBoundaryGluingRelation identification second first

/-- The explicit relation is an equivalence because the primitive seam relation is a matching. -/
theorem explicitGluingEquivalence_equivalence :
    Equivalence (explicitGluingEquivalence identification) := by
  refine ⟨?_, ?_, ?_⟩
  · intro point
    exact Or.inl rfl
  · intro first second related
    rcases related with equality | forward | reverse
    · exact Or.inl equality.symm
    · exact Or.inr (Or.inr forward)
    · exact Or.inr (Or.inl reverse)
  · intro first second third firstSecond secondThird
    rcases firstSecond with equality | firstSecond | firstSecond
    · subst second
      exact secondThird
    rcases secondThird with equality | secondThird | secondThird
    · subst third
      exact Or.inr (Or.inl firstSecond)
    · rcases first with left₁ | right₁ <;> rcases second with left₂ | right₂ <;>
        rcases third with left₃ | right₃ <;>
        simp only [compactSurfaceBoundaryGluingRelation] at firstSecond secondThird
    · rcases first with left₁ | right₁ <;> rcases second with left₂ | right₂ <;>
        rcases third with left₃ | right₃ <;>
        simp only [compactSurfaceBoundaryGluingRelation] at firstSecond secondThird
      exact Or.inl (congrArg Sum.inl
        (primitive_rightEndpoint_unique identification firstSecond secondThird))
    rcases secondThird with equality | secondThird | secondThird
    · subst third
      exact Or.inr (Or.inr firstSecond)
    · rcases first with left₁ | right₁ <;> rcases second with left₂ | right₂ <;>
        rcases third with left₃ | right₃ <;>
        simp only [compactSurfaceBoundaryGluingRelation] at firstSecond secondThird
      exact Or.inl (congrArg Sum.inr
        (primitive_leftEndpoint_unique identification firstSecond secondThird))
    · rcases first with left₁ | right₁ <;> rcases second with left₂ | right₂ <;>
        rcases third with left₃ | right₃ <;>
        simp only [compactSurfaceBoundaryGluingRelation] at firstSecond secondThird

/-- The generated equivalence closure has no extra identifications beyond equality or one matching
edge in either direction. -/
theorem eqvGen_iff_explicitGluingEquivalence (first second : SL ⊕ SR) :
    Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification) first second ↔
      explicitGluingEquivalence identification first second := by
  constructor
  · intro related
    induction related with
    | rel first second primitive => exact Or.inr (Or.inl primitive)
    | refl point => exact Or.inl rfl
    | symm first second _ hypothesis =>
        exact (explicitGluingEquivalence_equivalence identification).2 hypothesis
    | trans first second third _ _ firstHypothesis secondHypothesis =>
        exact (explicitGluingEquivalence_equivalence identification).3
          firstHypothesis secondHypothesis
  · intro related
    rcases related with equality | forward | reverse
    · subst second
      exact Relation.EqvGen.refl first
    · exact Relation.EqvGen.rel first second forward
    · exact Relation.EqvGen.symm second first (Relation.EqvGen.rel second first reverse)

/-- Graph of one exact primitive seam pairing in the disjoint-union square. -/
def boundarySeamGraph (pair : Fin identification.pairCount) :
    Circle → (SL ⊕ SR) × (SL ⊕ SR) :=
  fun circlePoint =>
    (Sum.inl (identification.leftBoundaryPoint pair circlePoint),
      Sum.inr (identification.rightBoundaryPoint pair circlePoint))

/-- Every exact seam graph is continuous. -/
theorem boundarySeamGraph_continuous (pair : Fin identification.pairCount) :
    Continuous (boundarySeamGraph identification pair) := by
  apply Continuous.prodMk
  · apply continuous_inl.comp
    exact (leftPresentation.parameterization_smooth
      (identification.leftComponent pair)).continuous
  · apply continuous_inr.comp
    apply (rightPresentation.parameterization_smooth
      (identification.rightComponent pair)).continuous.comp
    exact (identification.circleDiffeomorphism pair).contMDiff.continuous

/-- Every exact seam graph has closed range by compactness of the circle and Hausdorffness of the
disjoint-union square. -/
theorem boundarySeamGraph_range_isClosed (pair : Fin identification.pairCount) :
    IsClosed (Set.range (boundarySeamGraph identification pair)) := by
  apply IsCompact.isClosed
  have compactImage := (isCompact_univ : IsCompact (Set.univ : Set Circle)).image
    (boundarySeamGraph_continuous identification pair)
  simpa only [Set.image_univ] using compactImage

/-- The primitive relation set is literally the finite union of exact seam-graph ranges. -/
theorem primitiveRelation_set_eq_iUnion :
    {points : (SL ⊕ SR) × (SL ⊕ SR) |
      compactSurfaceBoundaryGluingRelation identification points.1 points.2} =
      ⋃ pair : Fin identification.pairCount,
        Set.range (boundarySeamGraph identification pair) := by
  ext points
  rcases points with ⟨first, second⟩
  rcases first with left | right
  · rcases second with left' | right'
    · simp [compactSurfaceBoundaryGluingRelation, boundarySeamGraph]
    · constructor
      · rintro ⟨pair, circlePoint, leftEquality, rightEquality⟩
        exact Set.mem_iUnion.mpr
          ⟨pair, ⟨circlePoint, by
            simp [boundarySeamGraph, leftEquality, rightEquality]⟩⟩
      · intro membership
        rcases Set.mem_iUnion.mp membership with ⟨pair, circlePoint, equality⟩
        simp only [boundarySeamGraph, Prod.mk.injEq, Sum.inl.injEq, Sum.inr.injEq]
          at equality
        exact ⟨pair, circlePoint, equality.1.symm, equality.2.symm⟩
  · rcases second with left' | right'
    · simp [compactSurfaceBoundaryGluingRelation, boundarySeamGraph]
    · simp [compactSurfaceBoundaryGluingRelation, boundarySeamGraph]

/-- The primitive matching relation is closed. -/
theorem primitiveRelation_set_isClosed :
    IsClosed {points : (SL ⊕ SR) × (SL ⊕ SR) |
      compactSurfaceBoundaryGluingRelation identification points.1 points.2} := by
  rw [primitiveRelation_set_eq_iUnion identification]
  exact isClosed_iUnion_of_finite fun pair =>
    boundarySeamGraph_range_isClosed identification pair

/-- The reversed primitive matching relation is closed. -/
theorem reversePrimitiveRelation_set_isClosed :
    IsClosed {points : (SL ⊕ SR) × (SL ⊕ SR) |
      compactSurfaceBoundaryGluingRelation identification points.2 points.1} := by
  change IsClosed (Prod.swap ⁻¹' {points : (SL ⊕ SR) × (SL ⊕ SR) |
    compactSurfaceBoundaryGluingRelation identification points.1 points.2})
  exact (primitiveRelation_set_isClosed identification).preimage continuous_swap

/-- The full generated equivalence relation is closed in the compact Hausdorff disjoint-union
square. -/
theorem explicitGluingEquivalence_set_isClosed :
    IsClosed {points : (SL ⊕ SR) × (SL ⊕ SR) |
      explicitGluingEquivalence identification points.1 points.2} := by
  have diagonal : IsClosed {points : (SL ⊕ SR) × (SL ⊕ SR) |
      points.1 = points.2} :=
    isClosed_eq continuous_fst continuous_snd
  have unionClosed := ((diagonal.union (primitiveRelation_set_isClosed identification)).union
    (reversePrimitiveRelation_set_isClosed identification))
  have setEquality :
      {points : (SL ⊕ SR) × (SL ⊕ SR) |
        explicitGluingEquivalence identification points.1 points.2} =
      {points | points.1 = points.2} ∪
        {points | compactSurfaceBoundaryGluingRelation identification points.1 points.2} ∪
        {points | compactSurfaceBoundaryGluingRelation identification points.2 points.1} := by
    ext points
    simp only [Set.mem_setOf_eq, Set.mem_union, explicitGluingEquivalence]
    tauto
  rw [setEquality]
  exact unionClosed

/-- Saturation of a subset by the exact explicit gluing equivalence. -/
def explicitGluingSaturation (subset : Set (SL ⊕ SR)) : Set (SL ⊕ SR) :=
  {point | ∃ source ∈ subset, explicitGluingEquivalence identification source point}

/-- Saturation of every closed subset is closed. This is the compact-Hausdorff projection argument:
the relevant part of the closed equivalence relation is compact, and its second projection is closed. -/
theorem explicitGluingSaturation_isClosed {subset : Set (SL ⊕ SR)}
    (subsetClosed : IsClosed subset) :
    IsClosed (explicitGluingSaturation identification subset) := by
  let relationOverSubset : Set ((SL ⊕ SR) × (SL ⊕ SR)) :=
    {points | points.1 ∈ subset ∧
      explicitGluingEquivalence identification points.1 points.2}
  have relationOverSubsetClosed : IsClosed relationOverSubset := by
    exact (subsetClosed.preimage continuous_fst).inter
      (explicitGluingEquivalence_set_isClosed identification)
  have relationOverSubsetCompact : IsCompact relationOverSubset :=
    relationOverSubsetClosed.isCompact
  have secondImageCompact : IsCompact (Prod.snd '' relationOverSubset) :=
    relationOverSubsetCompact.image continuous_snd
  have secondImageClosed : IsClosed (Prod.snd '' relationOverSubset) :=
    secondImageCompact.isClosed
  have imageEquality : Prod.snd '' relationOverSubset =
      explicitGluingSaturation identification subset := by
    ext point
    constructor
    · rintro ⟨points, ⟨sourceMembership, related⟩, equality⟩
      exact ⟨points.1, sourceMembership, equality ▸ related⟩
    · rintro ⟨source, sourceMembership, related⟩
      exact ⟨(source, point), ⟨sourceMembership, related⟩, rfl⟩
  rw [← imageEquality]
  exact secondImageClosed

/-- Equality of projected representatives gives the exact, non-nested generated relation. -/
theorem eqvGen_of_projection_eq {first second : SL ⊕ SR}
    (equality : projection identification first = projection identification second) :
    Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification) first second := by
  have nested : Relation.EqvGen
      (Relation.EqvGen (compactSurfaceBoundaryGluingRelation identification)) first second :=
    Quot.eqvGen_exact equality
  change (Relation.EqvGen.setoid
    (Relation.EqvGen.setoid (compactSurfaceBoundaryGluingRelation identification))) first second
    at nested
  rw [Setoid.eqvGen_idem] at nested
  exact nested

/-- The preimage of a projected subset is exactly its explicit equivalence saturation. -/
theorem projection_preimage_image (subset : Set (SL ⊕ SR)) :
    projection identification ⁻¹' (projection identification '' subset) =
      explicitGluingSaturation identification subset := by
  ext point
  constructor
  · rintro ⟨source, sourceMembership, projectedEquality⟩
    have generated := eqvGen_of_projection_eq identification projectedEquality
    exact ⟨source, sourceMembership,
      (eqvGen_iff_explicitGluingEquivalence identification source point).mp generated⟩
  · rintro ⟨source, sourceMembership, related⟩
    have generated :=
      (eqvGen_iff_explicitGluingEquivalence identification source point).mpr related
    exact ⟨source, sourceMembership, Quot.sound generated⟩

/-- The quotient projection is a closed map. Unlike an invalid appeal to a product quotient map, the
proof uses the exact saturation characterization and compact-Hausdorff closedness above. -/
theorem projection_isClosedMap : IsClosedMap (projection identification) := by
  intro subset subsetClosed
  change @IsClosed _
    (TopologicalSpace.coinduced (projection identification)
      (inferInstance : TopologicalSpace (SL ⊕ SR)))
    (projection identification '' subset)
  rw [isClosed_coinduced]
  change IsClosed (projection identification ⁻¹' (projection identification '' subset))
  rw [projection_preimage_image identification subset]
  exact explicitGluingSaturation_isClosed identification subsetClosed

/-- Exact equivalence class of one representative in the disjoint union. -/
def gluingEquivalenceClass (point : SL ⊕ SR) : Set (SL ⊕ SR) :=
  {other | explicitGluingEquivalence identification point other}

/-- Every exact equivalence class is closed. -/
theorem gluingEquivalenceClass_isClosed (point : SL ⊕ SR) :
    IsClosed (gluingEquivalenceClass identification point) := by
  change IsClosed ((fun other : SL ⊕ SR => (point, other)) ⁻¹'
    {points : (SL ⊕ SR) × (SL ⊕ SR) |
      explicitGluingEquivalence identification points.1 points.2})
  exact (explicitGluingEquivalence_set_isClosed identification).preimage
    (continuous_const.prodMk continuous_id)

/-- Every exact equivalence class is compact. -/
theorem gluingEquivalenceClass_isCompact (point : SL ⊕ SR) :
    IsCompact (gluingEquivalenceClass identification point) :=
  (gluingEquivalenceClass_isClosed identification point).isCompact

/-- Classes of two distinct quotient points have product disjoint from the equivalence relation. -/
theorem gluingEquivalenceClasses_prod_subset_compl_relation
    {first second : SL ⊕ SR}
    (distinct : projection identification first ≠ projection identification second) :
    gluingEquivalenceClass identification first ×ˢ
        gluingEquivalenceClass identification second ⊆
      {points : (SL ⊕ SR) × (SL ⊕ SR) |
        explicitGluingEquivalence identification points.1 points.2}ᶜ := by
  rintro ⟨left, right⟩ ⟨firstLeft, secondRight⟩ related
  have firstRight := (explicitGluingEquivalence_equivalence identification).3 firstLeft related
  have firstSecond := (explicitGluingEquivalence_equivalence identification).3 firstRight
    ((explicitGluingEquivalence_equivalence identification).2 secondRight)
  apply distinct
  exact Quot.sound
    ((eqvGen_iff_explicitGluingEquivalence identification first second).mpr firstSecond)

/-- Distinct quotient points have disjoint open neighborhoods. The proof separates their compact
classes in the complement of the closed relation, then saturates those neighborhoods through the
closed quotient projection. -/
theorem exists_disjoint_open_neighborhoods
    (first second : CompactSurfaceBoundaryGluingQuotient identification)
    (distinct : first ≠ second) :
    ∃ firstOpen secondOpen : Set (CompactSurfaceBoundaryGluingQuotient identification),
      IsOpen firstOpen ∧ IsOpen secondOpen ∧ first ∈ firstOpen ∧ second ∈ secondOpen ∧
        Disjoint firstOpen secondOpen := by
  revert distinct
  refine Quot.inductionOn first ?_
  intro firstRepresentative
  refine Quot.inductionOn second ?_
  intro secondRepresentative distinct
  let firstClass := gluingEquivalenceClass identification firstRepresentative
  let secondClass := gluingEquivalenceClass identification secondRepresentative
  have firstCompact : IsCompact firstClass :=
    gluingEquivalenceClass_isCompact identification firstRepresentative
  have secondCompact : IsCompact secondClass :=
    gluingEquivalenceClass_isCompact identification secondRepresentative
  let relationSet : Set ((SL ⊕ SR) × (SL ⊕ SR)) :=
    {points | explicitGluingEquivalence identification points.1 points.2}
  have relationClosed : IsClosed relationSet :=
    explicitGluingEquivalence_set_isClosed identification
  have classesAvoid : firstClass ×ˢ secondClass ⊆ relationSetᶜ :=
    gluingEquivalenceClasses_prod_subset_compl_relation identification distinct
  obtain ⟨firstNeighborhood, secondNeighborhood, firstOpen, secondOpen,
      firstSubset, secondSubset, productSubset⟩ :=
    generalized_tube_lemma firstCompact secondCompact relationClosed.isOpen_compl classesAvoid
  let quotientFirst : Set (CompactSurfaceBoundaryGluingQuotient identification) :=
    (projection identification '' firstNeighborhoodᶜ)ᶜ
  let quotientSecond : Set (CompactSurfaceBoundaryGluingQuotient identification) :=
    (projection identification '' secondNeighborhoodᶜ)ᶜ
  have quotientFirstOpen : IsOpen quotientFirst :=
    ((projection_isClosedMap identification) firstNeighborhoodᶜ
      firstOpen.isClosed_compl).isOpen_compl
  have quotientSecondOpen : IsOpen quotientSecond :=
    ((projection_isClosedMap identification) secondNeighborhoodᶜ
      secondOpen.isClosed_compl).isOpen_compl
  have firstMem : projection identification firstRepresentative ∈ quotientFirst := by
    show projection identification firstRepresentative ∉
      projection identification '' firstNeighborhoodᶜ
    rintro ⟨other, otherOutside, equality⟩
    have generated := eqvGen_of_projection_eq identification equality
    have otherFirst :=
      (eqvGen_iff_explicitGluingEquivalence identification other firstRepresentative).mp generated
    have firstOther := (explicitGluingEquivalence_equivalence identification).2 otherFirst
    exact otherOutside (firstSubset firstOther)
  have secondMem : projection identification secondRepresentative ∈ quotientSecond := by
    show projection identification secondRepresentative ∉
      projection identification '' secondNeighborhoodᶜ
    rintro ⟨other, otherOutside, equality⟩
    have generated := eqvGen_of_projection_eq identification equality
    have otherSecond :=
      (eqvGen_iff_explicitGluingEquivalence identification other secondRepresentative).mp generated
    have secondOther := (explicitGluingEquivalence_equivalence identification).2 otherSecond
    exact otherOutside (secondSubset secondOther)
  have quotientDisjoint : Disjoint quotientFirst quotientSecond := by
    apply Set.disjoint_left.mpr
    intro quotientPoint firstMembership secondMembership
    obtain ⟨representative, rfl⟩ := Quot.mk_surjective quotientPoint
    have representativeFirst : representative ∈ firstNeighborhood := by
      by_contra outside
      exact firstMembership ⟨representative, outside, rfl⟩
    have representativeSecond : representative ∈ secondNeighborhood := by
      by_contra outside
      exact secondMembership ⟨representative, outside, rfl⟩
    have diagonalMembership :
        (representative, representative) ∈ firstNeighborhood ×ˢ secondNeighborhood :=
      ⟨representativeFirst, representativeSecond⟩
    have outsideRelation := productSubset diagonalMembership
    exact outsideRelation (Or.inl rfl)
  exact ⟨quotientFirst, quotientSecond, quotientFirstOpen, quotientSecondOpen,
    firstMem, secondMem, quotientDisjoint⟩

/-- The exact compact-surface gluing quotient is Hausdorff. -/
instance compactSurfaceBoundaryGluingQuotientT2Space :
    T2Space (CompactSurfaceBoundaryGluingQuotient identification) :=
  T2Space.mk fun first second distinct =>
    exists_disjoint_open_neighborhoods identification first second distinct

/-- The canonical left-side map is injective; the generated quotient makes no same-side
identifications. -/
theorem leftInclusion_injective : Function.Injective (leftInclusion identification) := by
  intro first second equality
  have related := eqvGen_of_projection_eq identification equality
  have explicit := (eqvGen_iff_explicitGluingEquivalence identification _ _).mp related
  rcases explicit with representativeEquality | forward | reverse
  · exact Sum.inl_injective representativeEquality
  · simp [compactSurfaceBoundaryGluingRelation] at forward
  · simp [compactSurfaceBoundaryGluingRelation] at reverse

/-- The canonical right-side map is injective; the generated quotient makes no same-side
identifications. -/
theorem rightInclusion_injective : Function.Injective (rightInclusion identification) := by
  intro first second equality
  have related := eqvGen_of_projection_eq identification equality
  have explicit := (eqvGen_iff_explicitGluingEquivalence identification _ _).mp related
  rcases explicit with representativeEquality | forward | reverse
  · exact Sum.inr_injective representativeEquality
  · simp [compactSurfaceBoundaryGluingRelation] at forward
  · simp [compactSurfaceBoundaryGluingRelation] at reverse

/-- The canonical left-side map is closed as a composite of the closed sum injection and closed
quotient projection. -/
theorem leftInclusion_isClosedMap : IsClosedMap (leftInclusion identification) := by
  change IsClosedMap (fun point : SL => projection identification (Sum.inl point))
  exact (projection_isClosedMap identification).comp
    (isClosedMap_inl : IsClosedMap (Sum.inl : SL → SL ⊕ SR))

/-- The canonical right-side map is closed. -/
theorem rightInclusion_isClosedMap : IsClosedMap (rightInclusion identification) := by
  change IsClosedMap (fun point : SR => projection identification (Sum.inr point))
  exact (projection_isClosedMap identification).comp
    (isClosedMap_inr : IsClosedMap (Sum.inr : SR → SL ⊕ SR))

/-- Each side map is a closed topological embedding, without assuming the quotient Hausdorff. -/
theorem leftInclusion_isClosedEmbedding :
    Topology.IsClosedEmbedding (leftInclusion identification) :=
  Topology.IsClosedEmbedding.of_continuous_injective_isClosedMap
    (leftInclusion_continuous identification) (leftInclusion_injective identification)
    (leftInclusion_isClosedMap identification)

/-- The right side is likewise a closed topological embedding. -/
theorem rightInclusion_isClosedEmbedding :
    Topology.IsClosedEmbedding (rightInclusion identification) :=
  Topology.IsClosedEmbedding.of_continuous_injective_isClosedMap
    (rightInclusion_continuous identification) (rightInclusion_injective identification)
    (rightInclusion_isClosedMap identification)

/-- The two side ranges cover the whole exact quotient. -/
theorem range_leftInclusion_union_range_rightInclusion :
    Set.range (leftInclusion identification) ∪ Set.range (rightInclusion identification) = Set.univ := by
  ext quotientPoint
  constructor
  · intro _
    exact Set.mem_univ quotientPoint
  · intro _
    refine Quot.inductionOn quotientPoint ?_
    intro sidePoint
    cases sidePoint with
    | inl leftPoint => exact Or.inl ⟨leftPoint, rfl⟩
    | inr rightPoint => exact Or.inr ⟨rightPoint, rfl⟩

/-- The exact quotient is connected: both connected side images meet at any one of the positively
many paired seam points and together cover the quotient. -/
theorem quotient_isConnected :
    IsConnected (Set.univ : Set (CompactSurfaceBoundaryGluingQuotient identification)) := by
  have leftConnected : IsConnected (Set.range (leftInclusion identification)) := by
    simpa only [Set.image_univ] using leftSurface.connected.image
      (leftInclusion identification) (leftInclusion_continuous identification).continuousOn
  have rightConnected : IsConnected (Set.range (rightInclusion identification)) := by
    simpa only [Set.image_univ] using rightSurface.connected.image
      (rightInclusion identification) (rightInclusion_continuous identification).continuousOn
  obtain ⟨pair⟩ := identification.pairIndex_nonempty
  let seamPoint := leftInclusion identification (identification.leftBoundaryPoint pair 1)
  have rangesMeet :
      (Set.range (leftInclusion identification) ∩
        Set.range (rightInclusion identification)).Nonempty := by
    refine ⟨seamPoint, ⟨⟨identification.leftBoundaryPoint pair 1, rfl⟩, ?_⟩⟩
    refine ⟨identification.rightBoundaryPoint pair 1, ?_⟩
    exact (paired_boundary_points_equal identification pair 1).symm
  have connectedUnion := IsConnected.union rangesMeet leftConnected rightConnected
  rw [range_leftInclusion_union_range_rightInclusion identification] at connectedUnion
  exact connectedUnion

instance compactSurfaceBoundaryGluingQuotientConnectedSpace :
    ConnectedSpace (CompactSurfaceBoundaryGluingQuotient identification) :=
  connectedSpace_iff_univ.mpr (quotient_isConnected identification)

/-- Universal lift of sidewise functions agreeing on every exact paired boundary point. -/
def lift {Target : Type uTarget}
    (leftFunction : SL → Target) (rightFunction : SR → Target)
    (compatible : ∀ (pair : Fin identification.pairCount) (circlePoint : Circle),
      leftFunction (identification.leftBoundaryPoint pair circlePoint) =
        rightFunction (identification.rightBoundaryPoint pair circlePoint)) :
    CompactSurfaceBoundaryGluingQuotient identification → Target :=
  Quot.lift (Sum.elim leftFunction rightFunction) (by
    intro first second related
    induction related with
    | rel first second generator =>
        rcases first with leftPoint | rightPoint <;>
          rcases second with leftPoint' | rightPoint' <;>
          simp only [compactSurfaceBoundaryGluingRelation] at generator
        obtain ⟨pair, circlePoint, leftEquality, rightEquality⟩ := generator
        simpa [leftEquality, rightEquality] using compatible pair circlePoint
    | refl point => rfl
    | symm first second _ inductionHypothesis => exact inductionHypothesis.symm
    | trans first second third _ _ firstHypothesis secondHypothesis =>
        exact firstHypothesis.trans secondHypothesis)

/-- The universal lift agrees literally with the left function. -/
theorem lift_left {Target : Type uTarget}
    (leftFunction : SL → Target) (rightFunction : SR → Target)
    (compatible : ∀ (pair : Fin identification.pairCount) (circlePoint : Circle),
      leftFunction (identification.leftBoundaryPoint pair circlePoint) =
        rightFunction (identification.rightBoundaryPoint pair circlePoint))
    (point : SL) :
    lift identification leftFunction rightFunction compatible
      (leftInclusion identification point) = leftFunction point :=
  rfl

/-- The universal lift agrees literally with the right function. -/
theorem lift_right {Target : Type uTarget}
    (leftFunction : SL → Target) (rightFunction : SR → Target)
    (compatible : ∀ (pair : Fin identification.pairCount) (circlePoint : Circle),
      leftFunction (identification.leftBoundaryPoint pair circlePoint) =
        rightFunction (identification.rightBoundaryPoint pair circlePoint))
    (point : SR) :
    lift identification leftFunction rightFunction compatible
      (rightInclusion identification point) = rightFunction point :=
  rfl

end CompactSurfaceBoundaryGluingQuotient

end

end YangMills.Geometry
