/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.SmoothPrincipalBundle
import YangMills.Mathematics.LieGroupAdjoint
import YangMills.Mathematics.ManifoldDifferentialForms

/-!
# Pointwise principal connection-form conditions

This module states the vertical-normalization and adjoint-equivariance conditions of a principal
connection one-form. The form carrier is still pointwise: smooth-section regularity is deliberately
not hidden here, so this is not yet the final principal-connection interface.
-/

namespace YangMills.Geometry

open scoped Manifold ContDiff

universe uEG uHG uEB uHB uEP uHP uG uB uP

noncomputable section

variable
    {EG : Type uEG} {HG : Type uHG}
    [NormedAddCommGroup EG] [NormedSpace ℝ EG] [TopologicalSpace HG]
    {EB : Type uEB} {HB : Type uHB}
    [NormedAddCommGroup EB] [NormedSpace ℝ EB] [TopologicalSpace HB]
    {EP : Type uEP} {HP : Type uHP}
    [NormedAddCommGroup EP] [NormedSpace ℝ EP] [TopologicalSpace HP]
    {G : Type uG} {B : Type uB} {P : Type uP}
    [Group G] [TopologicalSpace G] [TopologicalSpace B] [TopologicalSpace P]
    [IsTopologicalGroup G]
    {IB : ModelWithCorners ℝ EB HB}
    {IG : ModelWithCorners ℝ EG HG}
    {IP : ModelWithCorners ℝ EP HP}
    [ChartedSpace HB B] [IsManifold IB ∞ B]
    [ChartedSpace HG G] [LieGroup IG ∞ G]
    [ChartedSpace HP P] [IsManifold IP ∞ P]
    {torsor : PrincipalBundleTorsorData G B P}
    {bundle : TopologicalPrincipalBundleData torsor}

/-- Orbit map through a total-space point. -/
def principalOrbitMap (torsor : PrincipalBundleTorsorData G B P) (p : P) : G → P :=
  fun g => torsor.rightAction p g

/-- Right translation of the total carrier by a fixed group element. -/
def principalRightTranslation (torsor : PrincipalBundleTorsorData G B P) (g : G) : P → P :=
  fun p => torsor.rightAction p g

/-- Orbit maps are smooth in a smooth principal bundle. -/
theorem principalOrbitMap_smooth
    (smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle) (p : P) :
    ContMDiff IG IP ∞ (principalOrbitMap torsor p) := by
  exact smoothBundle.rightAction_smooth.comp (contMDiff_const.prodMk contMDiff_id)

/-- Right translations of the total carrier are smooth. -/
theorem principalRightTranslation_smooth
    (smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle) (g : G) :
    ContMDiff IP IP ∞ (principalRightTranslation torsor g) := by
  exact smoothBundle.rightAction_smooth.comp (contMDiff_id.prodMk contMDiff_const)

/-- Fundamental vertical tangent vector generated by `X` at `p`. -/
def principalFundamentalVector
    (_smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle)
    (p : P) : GroupLieAlgebra IG G →L[ℝ] TangentSpace IP p :=
  mfderiv IG IP (principalOrbitMap torsor p) 1

/-- Differential of right translation by `g` at `p`. -/
def principalRightTranslationDifferential
    (_smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle)
    (p : P) (g : G) : TangentSpace IP p →L[ℝ] TangentSpace IP (torsor.rightAction p g) :=
  mfderiv IP IP (principalRightTranslation torsor g) p

/-- Pointwise algebraic conditions for a principal connection form.

The field has degree one and values in the tangent Lie algebra. `vertical_normalization` is Freed's
(1.9); `right_equivariant` is the tangent-vector form of (1.10). Smooth dependence of `form` on `p`
is intentionally absent and remains a named prerequisite for the final connection layer. -/
structure PointwisePrincipalConnectionData
    (smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle) where
  /-- Lie-algebra-valued pointwise one-form on the total space. -/
  form : YangMills.Mathematics.ManifoldDifferentialForm IP P (GroupLieAlgebra IG G) 1
  /-- The form recovers every infinitesimal generator on vertical fundamental vectors. -/
  vertical_normalization : ∀ p X,
    form.evalOne p (principalFundamentalVector smoothBundle p X) = X
  /-- Pullback by right translation transforms the form by `Ad(g⁻¹)`. -/
  right_equivariant : ∀ p g v,
    form.evalOne (torsor.rightAction p g)
        (principalRightTranslationDifferential smoothBundle p g v) =
      YangMills.Mathematics.lieGroupAdjoint IG g⁻¹ (form.evalOne p v)

namespace PointwisePrincipalConnectionData

variable {smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle}

/-- Vertical normalization forces the infinitesimal orbit map to be injective. -/
theorem fundamentalVector_injective
    (connection : PointwisePrincipalConnectionData smoothBundle) (p : P) :
    Function.Injective (principalFundamentalVector smoothBundle p) := by
  intro X Y equalVectors
  calc
    X = connection.form.evalOne p (principalFundamentalVector smoothBundle p X) :=
      (connection.vertical_normalization p X).symm
    _ = connection.form.evalOne p (principalFundamentalVector smoothBundle p Y) := by
      rw [equalVectors]
    _ = Y := connection.vertical_normalization p Y

end PointwisePrincipalConnectionData

end

end YangMills.Geometry
