/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.SmoothGaugeAssociatedFunction

/-!
# Affine gauge transformation of principal connection forms

The left Maurer--Cartan value is defined by left trivialization
`θ_g(w) = d(L_{g⁻¹})_g(w)`. Pulling it back through the globally smooth associated gauge function
produces an exact Lie-algebra-valued one-form carrier. Differentiating the variable principal right
action splits the gauge tangent into fixed right translation plus the fundamental vector generated
by `g_ϕ⁻¹ dg_ϕ`. Right equivariance and vertical normalization then derive Freed's evaluated affine
formula

`ϕ*Θ = Ad(g_ϕ⁻¹) Θ + g_ϕ*θ`.

The Maurer--Cartan pullback is presently exposed as an exact pointwise manifold form; a bundled
smooth-form theorem and its Maurer--Cartan equation remain separate infrastructure. No action or
observable gauge invariance follows from this connection identity alone.
-/

namespace YangMills.Geometry

open scoped Manifold ContDiff
open YangMills.Mathematics

universe uEG uHG uEB uHB uEP uHP uG uB uP

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable
    {EG : Type uEG} {HG : Type uHG}
    [NormedAddCommGroup EG] [NormedSpace ℝ EG] [TopologicalSpace HG]
    {EB : Type uEB} {HB : Type uHB}
    [NormedAddCommGroup EB] [NormedSpace ℝ EB] [TopologicalSpace HB]
    {EP : Type uEP} {HP : Type uHP}
    [NormedAddCommGroup EP] [NormedSpace ℝ EP] [TopologicalSpace HP]
    {G : Type uG} {B : Type uB} {P : Type uP}
    [Group G] [TopologicalSpace G] [TopologicalSpace B] [TopologicalSpace P]
    [IsTopologicalGroup G]
    {IB : ModelWithCorners ℝ EB HB}
    {IG : ModelWithCorners ℝ EG HG}
    {IP : ModelWithCorners ℝ EP HP}
    [ChartedSpace HB B] [IsManifold IB ∞ B]
    [ChartedSpace HG G] [LieGroup IG ∞ G]
    [ChartedSpace HP P] [IsManifold IP ∞ P]
    {torsor : PrincipalBundleTorsorData G B P}
    {bundle : TopologicalPrincipalBundleData torsor}
    {smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle}

/-- Left translation by a fixed group element. -/
def lieGroupLeftTranslation (g : G) : G → G := fun h => g * h

omit [IsTopologicalGroup G] in
 theorem lieGroupLeftTranslation_smooth (g : G) :
    ContMDiff IG IG ∞ (lieGroupLeftTranslation g) := by
  exact contMDiff_const.mul contMDiff_id

/-- Left trivialization of a tangent vector to the group. -/
def leftMaurerCartanApply (g : G) (w : TangentSpace IG g) : GroupLieAlgebra IG G :=
  mfderiv IG IG (lieGroupLeftTranslation g⁻¹) g w

/-- Pullback of the left Maurer--Cartan form along the associated gauge function, evaluated on
one tangent vector. -/
def SmoothGaugeTransformation.associatedMaurerCartanApply
    (gauge : SmoothGaugeTransformation smoothBundle) (p : P)
    (v : TangentSpace IP p) : GroupLieAlgebra IG G :=
  leftMaurerCartanApply (gauge.associatedGaugeFunction p)
    (mfderiv IP IG gauge.associatedGaugeFunction p v)

/-- The associated left Maurer--Cartan pullback as an actual Lie-algebra-valued manifold one-form. -/
noncomputable def SmoothGaugeTransformation.associatedMaurerCartanPullback
    (gauge : SmoothGaugeTransformation smoothBundle) :
    ManifoldDifferentialForm IP P (GroupLieAlgebra IG G) 1 := fun p =>
  ContinuousAlternatingMap.ofSubsingleton ℝ (TangentSpace IP p)
      (GroupLieAlgebra IG G) (0 : Fin 1)
    ((mfderiv IG IG
        (lieGroupLeftTranslation (gauge.associatedGaugeFunction p)⁻¹)
        (gauge.associatedGaugeFunction p)).comp
      (mfderiv IP IG gauge.associatedGaugeFunction p))

/-- The bundled pullback evaluates to the explicit left-trivialized derivative. -/
@[simp] theorem SmoothGaugeTransformation.associatedMaurerCartanPullback_evalOne
    (gauge : SmoothGaugeTransformation smoothBundle) (p : P)
    (v : TangentSpace IP p) :
    gauge.associatedMaurerCartanPullback.evalOne p v =
      gauge.associatedMaurerCartanApply p v := by
  simp [SmoothGaugeTransformation.associatedMaurerCartanPullback,
    SmoothGaugeTransformation.associatedMaurerCartanApply,
    leftMaurerCartanApply, ManifoldDifferentialForm.evalOne]
  rfl

/-- The derivative of the principal right action is the sum of its fixed-group and fixed-point
parts; the latter is the fundamental vector generated by left Maurer--Cartan trivialization. -/
theorem principalRightAction_mfderiv_apply
    (p : P) (g : G) (v : TangentSpace IP p) (w : TangentSpace IG g) :
    mfderiv (IP.prod IG) IP (fun z : P × G => torsor.rightAction z.1 z.2) (p, g) (v, w) =
      principalRightTranslationDifferential smoothBundle p g v +
        principalFundamentalVector smoothBundle (torsor.rightAction p g)
          (leftMaurerCartanApply g w) := by
  let action : P × G → P := fun z => torsor.rightAction z.1 z.2
  have hactionSmooth : ContMDiff (IP.prod IG) IP ∞ action := smoothBundle.rightAction_smooth
  rw [show (v, w) = (v, 0) + (0, w) by ext <;> simp, map_add]
  congr 1
  · have hright : principalRightTranslation torsor g = action ∘ fun q => (q, g) := by rfl
    have hgconst : ContMDiff IP IG ∞ (fun _ : P => g) := contMDiff_const
    have hconstPair : ContMDiff IP (IP.prod IG) ∞ (fun q => (q, g)) :=
      contMDiff_id.prodMk hgconst
    have hchain := mfderiv_comp (I := IP) (I' := IP.prod IG) (I'' := IP)
      (f := fun q : P => (q, g)) (g := action) p
      (hactionSmooth.mdifferentiableAt (by simp))
      (hconstPair.mdifferentiableAt (by simp))
    rw [← hright] at hchain
    rw [mfderiv_prod_left] at hchain
    have happ := congrArg (fun L => L v) hchain
    change mfderiv IP IP (principalRightTranslation torsor g) p v =
      mfderiv (IP.prod IG) IP action (p, g)
        (ContinuousLinearMap.inl ℝ (TangentSpace IP p) (TangentSpace IG g) v) at happ
    rw [ContinuousLinearMap.inl_apply] at happ
    simpa [action, principalRightTranslationDifferential, principalRightTranslation] using happ.symm
  · let left : G → G := lieGroupLeftTranslation g⁻¹
    have hleftSmooth : ContMDiff IG IG ∞ left := lieGroupLeftTranslation_smooth g⁻¹
    have horbit : principalOrbitMap torsor p =
        principalOrbitMap torsor (torsor.rightAction p g) ∘ left := by
      funext h
      simp [principalOrbitMap, left, lieGroupLeftTranslation, torsor.right_mul]
    have htargetOrbitSmooth : ContMDiff IG IP ∞
        (principalOrbitMap torsor (torsor.rightAction p g)) :=
      principalOrbitMap_smooth smoothBundle (torsor.rightAction p g)
    have hchainLeft := mfderiv_comp (I := IG) (I' := IG) (I'' := IP)
      (f := left) (g := principalOrbitMap torsor (torsor.rightAction p g)) g
      (htargetOrbitSmooth.mdifferentiableAt (by simp))
      (hleftSmooth.mdifferentiableAt (by simp))
    rw [← horbit] at hchainLeft
    have hleftAt : left g = 1 := by simp [left, lieGroupLeftTranslation]
    rw [hleftAt] at hchainLeft
    have hactionOrbit : principalOrbitMap torsor p = action ∘ fun h => (p, h) := by rfl
    have hpconst : ContMDiff IG IP ∞ (fun _ : G => p) := contMDiff_const
    have hconstPair : ContMDiff IG (IP.prod IG) ∞ (fun h => (p, h)) :=
      hpconst.prodMk contMDiff_id
    have hchainAction := mfderiv_comp (I := IG) (I' := IP.prod IG) (I'' := IP)
      (f := fun h : G => (p, h)) (g := action) g
      (hactionSmooth.mdifferentiableAt (by simp))
      (hconstPair.mdifferentiableAt (by simp))
    rw [← hactionOrbit] at hchainAction
    rw [mfderiv_prod_right] at hchainAction
    change mfderiv (IP.prod IG) IP action (p, g) (0, w) =
      mfderiv IG IP (principalOrbitMap torsor (torsor.rightAction p g)) 1
        (mfderiv IG IG left g w)
    have hactionW := congrArg (fun L => L w) hchainAction
    have hleftW := congrArg (fun L => L w) hchainLeft
    change mfderiv IG IP (principalOrbitMap torsor p) g w =
      mfderiv (IP.prod IG) IP action (p, g)
        (ContinuousLinearMap.inr ℝ (TangentSpace IP p) (TangentSpace IG g) w) at hactionW
    rw [ContinuousLinearMap.inr_apply] at hactionW
    change mfderiv IG IP (principalOrbitMap torsor p) g w =
      mfderiv IG IP (principalOrbitMap torsor (torsor.rightAction p g)) 1
        (mfderiv IG IG left g w) at hleftW
    simpa [action, principalOrbitMap] using hactionW.symm.trans hleftW

/-- Exact gauge tangent decomposition, stated in the tangent bundle so the dependent target fiber
is transported by the pointwise gauge decomposition without an exposed cast. -/
theorem SmoothGaugeTransformation.tangentMap_eq_rightTranslation_add_fundamental
    (gauge : SmoothGaugeTransformation smoothBundle) (p : P)
    (v : TangentSpace IP p) :
    tangentMap IP IP gauge ⟨p, v⟩ =
      (⟨torsor.rightAction p (gauge.associatedGaugeFunction p),
        principalRightTranslationDifferential smoothBundle p
            (gauge.associatedGaugeFunction p) v +
          principalFundamentalVector smoothBundle
            (torsor.rightAction p (gauge.associatedGaugeFunction p))
            (gauge.associatedMaurerCartanApply p v)⟩ : TangentBundle IP P) := by
  let gfun := gauge.associatedGaugeFunction
  let action : P × G → P := fun z => torsor.rightAction z.1 z.2
  have hgSmooth : ContMDiff IP IG ∞ gfun := gauge.associatedGaugeFunction_contMDiff
  have hdecomp : (gauge : P → P) = action ∘ fun q => (id q, gfun q) := by
    funext q
    exact gauge.eq_rightAction_associatedGaugeFunction q
  have hactionSmooth : ContMDiff (IP.prod IG) IP ∞ action := smoothBundle.rightAction_smooth
  have hpairSmooth : ContMDiff IP (IP.prod IG) ∞ (fun q => (id q, gfun q)) :=
    contMDiff_id.prodMk hgSmooth
  have htangentCongr := congrArg (fun f : P → P => tangentMap IP IP f ⟨p, v⟩) hdecomp
  rw [tangentMap_comp
      (hactionSmooth.mdifferentiable (by simp))
      (hpairSmooth.mdifferentiable (by simp))] at htangentCongr
  rw [htangentCongr]
  change (⟨action (p, gfun p),
      mfderiv (IP.prod IG) IP action (p, gfun p)
        (mfderiv IP (IP.prod IG) (fun q => (id q, gfun q)) p v)⟩ : TangentBundle IP P) = _
  rw [Bundle.TotalSpace.mk.injEq]
  constructor
  · rfl
  simp only [action, gfun]
  rw [heq_iff_eq]
  change mfderiv (IP.prod IG) IP action (p, gfun p)
      (mfderiv IP (IP.prod IG) (fun q => (id q, gfun q)) p v) = _
  have hpairDeriv :
      mfderiv IP (IP.prod IG) (fun q : P => (id q, gfun q)) p =
        (mfderiv IP IP id p).prod (mfderiv IP IG gfun p) :=
    mfderiv_prodMk (x := p)
      (mdifferentiableAt_id (𝕜 := ℝ) (I := IP))
      (hgSmooth.mdifferentiableAt (by simp))
  rw [hpairDeriv, mfderiv_id]
  change mfderiv (IP.prod IG) IP action (p, gfun p)
      (v, mfderiv IP IG gfun p v) = _
  exact principalRightAction_mfderiv_apply p (gfun p) v
    (mfderiv IP IG gfun p v)

/-- Evaluated affine gauge transformation formula with the exact left Maurer--Cartan pullback and
plus sign fixed by the project's right-action convention. -/
theorem gaugePullbackForm_evalOne_affine
    (gauge : SmoothGaugeTransformation smoothBundle)
    (connection : PrincipalConnectionData smoothBundle)
    (p : P) (v : TangentSpace IP p) :
    (gaugePullbackForm gauge connection).evalOne p v =
      lieGroupAdjoint IG (gauge.associatedGaugeFunction p)⁻¹
          (connection.pointwise.form.evalOne p v) +
        gauge.associatedMaurerCartanApply p v := by
  let evaluate : TangentBundle IP P → GroupLieAlgebra IG G := fun z =>
    connection.pointwise.form.evalOne z.1 z.2
  have htangent := gauge.tangentMap_eq_rightTranslation_add_fundamental p v
  have heval := congrArg evaluate htangent
  change connection.pointwise.form.evalOne (gauge p) (mfderiv IP IP gauge p v) =
    connection.pointwise.form.evalOne
      (torsor.rightAction p (gauge.associatedGaugeFunction p))
      (principalRightTranslationDifferential smoothBundle p
          (gauge.associatedGaugeFunction p) v +
        principalFundamentalVector smoothBundle
          (torsor.rightAction p (gauge.associatedGaugeFunction p))
          (gauge.associatedMaurerCartanApply p v)) at heval
  have hlinear :
      connection.pointwise.form.evalOne
          (torsor.rightAction p (gauge.associatedGaugeFunction p))
          (principalRightTranslationDifferential smoothBundle p
              (gauge.associatedGaugeFunction p) v +
            principalFundamentalVector smoothBundle
              (torsor.rightAction p (gauge.associatedGaugeFunction p))
              (gauge.associatedMaurerCartanApply p v)) =
        connection.pointwise.form.evalOne
            (torsor.rightAction p (gauge.associatedGaugeFunction p))
            (principalRightTranslationDifferential smoothBundle p
              (gauge.associatedGaugeFunction p) v) +
          connection.pointwise.form.evalOne
            (torsor.rightAction p (gauge.associatedGaugeFunction p))
            (principalFundamentalVector smoothBundle
              (torsor.rightAction p (gauge.associatedGaugeFunction p))
              (gauge.associatedMaurerCartanApply p v)) := by
    unfold YangMills.Mathematics.ManifoldDifferentialForm.evalOne
    rw [show (fun _ : Fin 1 =>
          principalRightTranslationDifferential smoothBundle p
              (gauge.associatedGaugeFunction p) v +
            principalFundamentalVector smoothBundle
              (torsor.rightAction p (gauge.associatedGaugeFunction p))
              (gauge.associatedMaurerCartanApply p v)) =
        (fun _ => principalRightTranslationDifferential smoothBundle p
            (gauge.associatedGaugeFunction p) v) +
          (fun _ => principalFundamentalVector smoothBundle
            (torsor.rightAction p (gauge.associatedGaugeFunction p))
            (gauge.associatedMaurerCartanApply p v)) by
          ext i
          simp]
    let f := connection.pointwise.form
      (torsor.rightAction p (gauge.associatedGaugeFunction p))
    let a := principalRightTranslationDifferential smoothBundle p
      (gauge.associatedGaugeFunction p) v
    let b := principalFundamentalVector smoothBundle
      (torsor.rightAction p (gauge.associatedGaugeFunction p))
      (gauge.associatedMaurerCartanApply p v)
    have hadd := f.map_update_add (fun _ : Fin 1 => a) (0 : Fin 1) a b
    have hab : Function.update (fun _ : Fin 1 => a) 0 (a + b) = fun _ => a + b := by
      funext i
      fin_cases i
      simp
    have ha : Function.update (fun _ : Fin 1 => a) 0 a = fun _ => a := by
      funext i
      fin_cases i
      simp
    have hb : Function.update (fun _ : Fin 1 => a) 0 b = fun _ => b := by
      funext i
      fin_cases i
      simp
    rw [hab, ha, hb] at hadd
    exact hadd
  rw [hlinear, connection.right_equivariant,
    connection.vertical_normalization] at heval
  rw [gaugePullbackForm_evalOne]
  exact heval

/-- The affine law stated directly on the exact transformed `PrincipalConnectionData` carrier. -/
theorem gaugePullbackConnection_form_evalOne_affine
    (gauge : SmoothGaugeTransformation smoothBundle)
    (connection : PrincipalConnectionData smoothBundle)
    (p : P) (v : TangentSpace IP p) :
    (gaugePullbackConnection gauge connection).pointwise.form.evalOne p v =
      lieGroupAdjoint IG (gauge.associatedGaugeFunction p)⁻¹
          (connection.pointwise.form.evalOne p v) +
        gauge.associatedMaurerCartanPullback.evalOne p v := by
  rw [SmoothGaugeTransformation.associatedMaurerCartanPullback_evalOne]
  exact gaugePullbackForm_evalOne_affine gauge connection p v

end

end YangMills.Geometry
