/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.PrincipalFundamentalVectorField
import YangMills.Geometry.PrincipalBundleLocalTangentLiftAmbient
import YangMills.Mathematics.LieGroupInvariantFieldCommutation

/-!
# Orbit-adapted tangent fields in principal product coordinates

An arbitrary group tangent is normalized to the identity and extended as a right-invariant field.
Together with a centered-chart local base field this constructs a smooth product tangent field with
prescribed value and exact right-translation behavior along the whole fiber. The normalized
left/right invariant bracket vanishes. Transport through a partial principal trivialization remains
a separate step.
-/

namespace YangMills.Geometry.PrincipalOrbitAdapted

open Set Function Bundle
open scoped Manifold ContDiff
open YangMills.Mathematics

universe uE uH uG

noncomputable section

variable
    {E : Type uE} {H : Type uH}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [TopologicalSpace H]
    (I : ModelWithCorners ℝ E H)
    {G : Type uG} [Group G] [TopologicalSpace G]
    [ChartedSpace H G] [LieGroup I ∞ G]

/-- Normalize an arbitrary tangent at `h` to the identity by right translation. -/
def rightInvariantGeneratorAt (h : G) (w : TangentSpace I h) : GroupLieAlgebra I G :=
  mfderiv I I (fun q : G => q * h⁻¹) h w

/-- The right-invariant field generated by `rightInvariantGeneratorAt` has the prescribed value. -/
theorem mulRightInvariantVectorField_rightInvariantGeneratorAt
    (h : G) (w : TangentSpace I h) :
    mulRightInvariantVectorField I (rightInvariantGeneratorAt I h w) h = w := by
  unfold mulRightInvariantVectorField rightInvariantGeneratorAt
  have hcomp := mfderiv_comp (I := I) (I' := I) (I'' := I)
    (f := fun q : G => q * h⁻¹) (g := fun q : G => q * h) h
    ((contMDiff_mul_right (I := I) (n := ∞) (a := h)).mdifferentiableAt (by simp))
    ((contMDiff_mul_right (I := I) (n := ∞) (a := h⁻¹)).mdifferentiableAt (by simp))
  have happ := congrArg (fun L => L w) hcomp
  have hfun : (fun q : G => q * h) ∘ (fun q : G => q * h⁻¹) = id := by
    funext q
    simp [mul_assoc]
  rw [hfun, mfderiv_id] at happ
  rw [mul_inv_cancel] at happ
  exact happ.symm

/-- The normalized field is exactly transported by every right translation. -/
theorem rightInvariantGeneratorAt_rightTranslation
    (h g : G) (w : TangentSpace I h) :
    mfderiv I I (fun q : G => q * g) h w =
      mulRightInvariantVectorField I (rightInvariantGeneratorAt I h w) (h * g) := by
  calc
    _ = mfderiv I I (fun q : G => q * g) h
        (mulRightInvariantVectorField I (rightInvariantGeneratorAt I h w) h) := by
      rw [mulRightInvariantVectorField_rightInvariantGeneratorAt I h w]
    _ = _ := mfderiv_mul_right_mulRightInvariantVectorField I _ h g

/-- At the normalized fiber coordinate `1`, the fundamental (left-invariant) field and every
prescribed-value adapted (right-invariant) field have zero intrinsic bracket. -/
theorem normalizedFundamental_adapted_bracket_zero
    [FiniteDimensional ℝ E] [ENat.LEInfty (minSmoothness ℝ 3)]
    (X : GroupLieAlgebra I G) (w : GroupLieAlgebra I G) :
    VectorField.mlieBracket I (mulInvariantVectorField X)
      (mulRightInvariantVectorField I (rightInvariantGeneratorAt I 1 w)) 1 = 0 :=
  mlieBracket_mulInvariant_mulRightInvariant_identity I X _

/-- The normalized prescribed-value right-invariant field is globally smooth. -/
theorem rightInvariantGeneratorAt_smooth (h : G) (w : TangentSpace I h) :
    ContMDiff I I.tangent ∞
      (fun g : G =>
        (⟨g, mulRightInvariantVectorField I (rightInvariantGeneratorAt I h w) g⟩ :
          TangentBundle I G)) :=
  contMDiff_mulRightInvariantVectorField I _


universe uEB uHB uB

variable
    {EB : Type uEB} {HB : Type uHB}
    [NormedAddCommGroup EB] [NormedSpace ℝ EB] [FiniteDimensional ℝ EB]
    [TopologicalSpace HB]
    {B : Type uB} [TopologicalSpace B]
    (IB : ModelWithCorners ℝ EB HB)
    [ChartedSpace HB B] [IsManifold IB ∞ B]

/-- A chart-local tangent field obtained by pulling back the constant coordinate value of `v`. -/
def localTangentFieldAt (b : B) (v : TangentSpace IB b) (q : B) : TangentSpace IB q :=
  VectorField.mpullback IB (modelWithCornersSelf ℝ EB) (extChartAt IB b)
    (fun _ => mfderiv IB (modelWithCornersSelf ℝ EB) (extChartAt IB b) b v) q

omit [FiniteDimensional ℝ EB] in
/-- The chart-local field takes the prescribed tangent value at its center. -/
theorem localTangentFieldAt_self (b : B) (v : TangentSpace IB b) :
    localTangentFieldAt IB b v b = v := by
  simp only [localTangentFieldAt, VectorField.mpullback_apply]
  rw [(isInvertible_mfderiv_extChartAt (I := IB)
    (mem_extChartAt_source b)).inverse_apply_eq]

/-- The prescribed-value field is smooth on the full source of its centered extended chart. -/
theorem localTangentFieldAt_isSmoothOn (b : B) (v : TangentSpace IB b) :
    ManifoldTangentField.IsSmoothOn IB (extChartAt IB b).source
      (localTangentFieldAt IB b v) := by
  letI : CompleteSpace EB := FiniteDimensional.complete ℝ EB
  let coordinateValue : EB :=
    mfderiv IB (modelWithCornersSelf ℝ EB) (extChartAt IB b) b v
  let constantField : (x : EB) → TangentSpace (modelWithCornersSelf ℝ EB) x :=
    fun _ => coordinateValue
  have constantField_smooth : ContMDiff (modelWithCornersSelf ℝ EB)
      ((modelWithCornersSelf ℝ EB).prod (modelWithCornersSelf ℝ EB)) ∞
      (fun x => (⟨x, constantField x⟩ :
        TangentBundle (modelWithCornersSelf ℝ EB) EB)) := by
    rw [contMDiff_vectorSpace_iff_contDiff]
    exact contDiff_const
  intro q hq
  have hq' : q ∈ (chartAt HB b).source := by simpa using hq
  have h := constantField_smooth.contMDiffAt.mpullback_vectorField_preimage
    (m := ∞) (n := ∞)
    (contMDiffAt_extChartAt' hq')
    (isInvertible_mfderiv_extChartAt hq) (by simp)
  simpa only [localTangentFieldAt, constantField, coordinateValue] using
    h.contMDiffWithinAt


/-- Product-coordinate field combining a prescribed local base field and the uniquely normalized
right-invariant group field. -/
def adaptedProductField (b : B) (u : TangentSpace IB b)
    (h : G) (w : TangentSpace I h) (z : B × G) : TangentSpace (IB.prod I) z :=
  (localTangentFieldAt IB b u z.1,
    mulRightInvariantVectorField I (rightInvariantGeneratorAt I h w) z.2)

omit [FiniteDimensional ℝ EB] in
@[simp] theorem adaptedProductField_self (b : B) (u : TangentSpace IB b)
    (h : G) (w : TangentSpace I h) :
    adaptedProductField I IB b u h w (b, h) = (u, w) := by
  simp [adaptedProductField, localTangentFieldAt_self,
    mulRightInvariantVectorField_rightInvariantGeneratorAt]
  rfl

/-- The product-coordinate field is smooth on the base centered-chart source times the whole
fiber group. -/
theorem adaptedProductField_isSmoothOn (b : B) (u : TangentSpace IB b)
    (h : G) (w : TangentSpace I h) :
    ManifoldTangentField.IsSmoothOn (IB.prod I)
      ((extChartAt IB b).source ×ˢ (Set.univ : Set G))
      (adaptedProductField I IB b u h w) := by
  let first : B × G → TangentBundle IB B := fun z =>
    ⟨z.1, localTangentFieldAt IB b u z.1⟩
  have hfirst : ContMDiffOn (IB.prod I) IB.tangent ∞ first
      ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) :=
    (localTangentFieldAt_isSmoothOn IB b u).comp contMDiffOn_fst (by
      intro z hz
      exact hz.1)
  let second : B × G → TangentBundle I G := fun z =>
    ⟨z.2, mulRightInvariantVectorField I (rightInvariantGeneratorAt I h w) z.2⟩
  have hsecond : ContMDiffOn (IB.prod I) I.tangent ∞ second
      ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) :=
    (rightInvariantGeneratorAt_smooth I h w).comp_contMDiffOn contMDiffOn_snd
  have hpair : ContMDiffOn (IB.prod I) (IB.tangent.prod I.tangent) ∞
      (fun z => (first z, second z))
      ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) := hfirst.prodMk hsecond
  have htotal := contMDiff_equivTangentBundleProd_symm.comp_contMDiffOn hpair
  convert htotal using 1
  all_goals rfl

omit [FiniteDimensional ℝ EB] in
/-- Exact right-translation law in product coordinates. -/
theorem adaptedProductField_rightTranslation (b : B) (u : TangentSpace IB b)
    (h g : G) (w : TangentSpace I h) :
    mfderiv (IB.prod I) (IB.prod I) (fun z : B × G => (z.1, z.2 * g)) (b, h)
        (adaptedProductField I IB b u h w (b, h)) =
      adaptedProductField I IB b u h w (b, h * g) := by
  rw [adaptedProductField_self]
  have hid : MDifferentiableAt IB IB id b := mdifferentiableAt_id
  have hright : MDifferentiableAt I I (fun q : G => q * g) h :=
    (contMDiff_mul_right (I := I) (n := ∞) (a := g)).mdifferentiableAt (by simp)
  rw [show (fun z : B × G => (z.1, z.2 * g)) =
      Prod.map id (fun q : G => q * g) by rfl]
  rw [mfderiv_prodMap hid hright, mfderiv_id]
  simp only [ContinuousLinearMap.prodMap]
  change (u, mfderiv I I (fun q : G => q * g) h w) = _
  rw [rightInvariantGeneratorAt_rightTranslation I h g w]
  unfold adaptedProductField
  rw [localTangentFieldAt_self]
  rfl


omit [Group G] [FiniteDimensional ℝ EB] [IsManifold IB ∞ B] in
/-- The natural product domain of the construction is open. -/
theorem isOpen_adaptedProductDomain (b : B) :
    IsOpen ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) :=
  (isOpen_extChartAt_source (I := IB) b).prod isOpen_univ

omit [Group G] [TopologicalSpace G] [FiniteDimensional ℝ EB]
    [IsManifold IB ∞ B] in
/-- The prescribed point belongs to the natural product domain. -/
theorem adaptedProductDomain_mem (b : B) (h : G) :
    (b, h) ∈ ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) :=
  ⟨mem_extChartAt_source b, Set.mem_univ h⟩

omit [TopologicalSpace G] [FiniteDimensional ℝ EB] [IsManifold IB ∞ B] in
/-- The whole right fiber orbit remains in the natural product domain. -/
theorem adaptedProductDomain_orbit (b : B) (h g : G) :
    (b, h * g) ∈ ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) :=
  ⟨mem_extChartAt_source b, Set.mem_univ (h * g)⟩

/-- Compiled product-coordinate existence package: arbitrary prescribed tangent pair, open domain,
`C∞` regularity, and exact right transport along the entire fiber orbit. -/
theorem exists_adaptedProductField (b : B) (u : TangentSpace IB b)
    (h : G) (w : TangentSpace I h) :
    ∃ field : (z : B × G) → TangentSpace (IB.prod I) z,
      field (b, h) = (u, w) ∧
      ManifoldTangentField.IsSmoothOn (IB.prod I)
        ((extChartAt IB b).source ×ˢ (Set.univ : Set G)) field ∧
      ∀ g : G,
        mfderiv (IB.prod I) (IB.prod I) (fun z : B × G => (z.1, z.2 * g)) (b, h)
          (field (b, h)) = field (b, h * g) := by
  refine ⟨adaptedProductField I IB b u h w, adaptedProductField_self I IB b u h w,
    adaptedProductField_isSmoothOn I IB b u h w, ?_⟩
  intro g
  exact adaptedProductField_rightTranslation I IB b u h g w

end
end YangMills.Geometry.PrincipalOrbitAdapted
