/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.PrincipalConnectionAffineGaugeTransformation

/-!
# Generation of vertical tangents by fundamental vectors

Smooth principal local triviality proves that the kernel of the bundle-projection differential is
exactly generated by infinitesimal orbit vectors. A pointwise connection's vertical normalization
then recovers the unique generator as the connection-form value. Right equivariance and connection
smoothness are not used.
-/

namespace YangMills.Geometry

open scoped Manifold ContDiff

universe uEG uHG uEB uHB uEP uHP uG uB uP

noncomputable section

set_option backward.isDefEq.respectTransparency false

variable
    {EG : Type uEG} {HG : Type uHG}
    [NormedAddCommGroup EG] [NormedSpace ℝ EG] [TopologicalSpace HG]
    {EB : Type uEB} {HB : Type uHB}
    [NormedAddCommGroup EB] [NormedSpace ℝ EB] [TopologicalSpace HB]
    {EP : Type uEP} {HP : Type uHP}
    [NormedAddCommGroup EP] [NormedSpace ℝ EP] [TopologicalSpace HP]
    {G : Type uG} {B : Type uB} {P : Type uP}
    [Group G] [TopologicalSpace G] [TopologicalSpace B] [TopologicalSpace P]
    [IsTopologicalGroup G]
    {IB : ModelWithCorners ℝ EB HB}
    {IG : ModelWithCorners ℝ EG HG}
    {IP : ModelWithCorners ℝ EP HP}
    [ChartedSpace HB B] [IsManifold IB ∞ B]
    [ChartedSpace HG G] [LieGroup IG ∞ G]
    [ChartedSpace HP P] [IsManifold IP ∞ P]
    {torsor : PrincipalBundleTorsorData G B P}
    {bundle : TopologicalPrincipalBundleData torsor}
    {smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle}

/-- The infinitesimal orbit map generates the full kernel of the bundle projection differential. -/
theorem vertical_tangent_exists_fundamental
    (p : P) (v : TangentSpace IP p)
    (vertical : mfderiv IP IB torsor.projection p v = 0) :
    ∃ X : GroupLieAlgebra IG G,
      v = principalFundamentalVector smoothBundle p X := by
  let b := torsor.projection p
  let chart := bundle.trivializationAt b
  let localSection : B → P := principalBundleLocalSection chart
  let second : P → G := fun q => (chart.toPartialHomeomorph q).2
  let pair : P → P × G := fun q => (localSection (torsor.projection q), second q)
  let action : P × G → P := fun z => torsor.rightAction z.1 z.2
  have hp : p ∈ chart.toPartialHomeomorph.source :=
    bundle.mem_source_trivializationAt p
  have hb : b ∈ chart.baseSet := bundle.mem_baseSet_trivializationAt b
  have hchartMem : chart ∈ bundle.trivializationAtlas :=
    bundle.trivializationAt_mem_atlas b
  have hchart : ContMDiffAt IP (IB.prod IG) ∞ chart.toPartialHomeomorph p :=
    (smoothBundle.trivialization_smooth chart hchartMem).contMDiffAt
      (chart.toPartialHomeomorph.open_source.mem_nhds hp)
  have hlocalSection : ContMDiffAt IB IP ∞ localSection b := by
    simpa [localSection] using
      principalBundleLocalSection_contMDiffAt smoothBundle chart hchartMem hb
  have hprojection : ContMDiffAt IP IB ∞ torsor.projection p :=
    smoothBundle.projection_smooth.contMDiffAt
  have hfirst : ContMDiffAt IP IP ∞ (fun q => localSection (torsor.projection q)) p := by
    exact hlocalSection.comp p hprojection
  have hsecond : ContMDiffAt IP IG ∞ second p := by
    change ContMDiffAt IP IG ∞ (Prod.snd ∘ chart.toPartialHomeomorph) p
    exact contMDiffAt_snd.comp p hchart
  have hpair : ContMDiffAt IP (IP.prod IG) ∞ pair p := by
    simpa [pair] using hfirst.prodMk hsecond
  have haction : ContMDiffAt (IP.prod IG) IP ∞ action (pair p) := by
    exact smoothBundle.rightAction_smooth.contMDiffAt
  have hlocal : action ∘ pair =ᶠ[nhds p] id := by
    filter_upwards [chart.toPartialHomeomorph.open_source.mem_nhds hp] with q hq
    exact principalBundleLocalSection_rightAction_chartSecond chart q hq
  have hidentity := hlocal.mfderiv_eq (I := IP) (I' := IP)
  rw [mfderiv_id] at hidentity
  have hchain := mfderiv_comp p
    (haction.mdifferentiableAt (by simp)) (hpair.mdifferentiableAt (by simp))
  have hfirstChain := mfderiv_comp p
    (hlocalSection.mdifferentiableAt (by simp)) (hprojection.mdifferentiableAt (by simp))
  have hpairDeriv :
      mfderiv IP (IP.prod IG) pair p =
        (mfderiv IP IP (fun q => localSection (torsor.projection q)) p).prod
          (mfderiv IP IG second p) := by
    simpa [pair] using mfderiv_prodMk
      (hfirst.mdifferentiableAt (by simp)) (hsecond.mdifferentiableAt (by simp))
  have hfirstZero :
      mfderiv IP IP (fun q => localSection (torsor.projection q)) p v = 0 := by
    calc
      mfderiv IP IP (fun q => localSection (torsor.projection q)) p v =
          mfderiv IP IP (localSection ∘ torsor.projection) p v := rfl
      _ = mfderiv IB IP localSection b (mfderiv IP IB torsor.projection p v) :=
        congrArg (fun L => L v) hfirstChain
      _ = 0 := by rw [vertical, map_zero]
  let w : TangentSpace IG (second p) := mfderiv IP IG second p v
  have hpairApply : mfderiv IP (IP.prod IG) pair p v = (0, w) := by
    rw [hpairDeriv]
    change (mfderiv IP IP (fun q => localSection (torsor.projection q)) p v,
      mfderiv IP IG second p v) = (0, w)
    rw [hfirstZero]
  have hv : v = mfderiv (IP.prod IG) IP action (pair p) (0, w) := by
    calc
      v = (ContinuousLinearMap.id ℝ (TangentSpace IP p)) v := by simp
      _ = mfderiv IP IP (action ∘ pair) p v :=
        congrArg (fun L => L v) hidentity.symm
      _ = mfderiv (IP.prod IG) IP action (pair p)
          (mfderiv IP (IP.prod IG) pair p v) :=
        congrArg (fun L => L v) hchain
      _ = mfderiv (IP.prod IG) IP action (pair p) (0, w) := by rw [hpairApply]
  refine ⟨leftMaurerCartanApply (second p) w, ?_⟩
  rw [hv]
  have hsplit := principalRightAction_mfderiv_apply
    (smoothBundle := smoothBundle) (localSection b) (second p) 0 w
  change mfderiv (IP.prod IG) IP action (pair p) (0, w) = _
  rw [show pair p = (localSection b, second p) by rfl, hsplit]
  simp only [map_zero, zero_add]
  have hpresentation : action (pair p) = p := hlocal.self_of_nhds
  have hpresentation' : torsor.rightAction (localSection b) (second p) = p := by
    simpa [action, pair, b] using hpresentation
  rw [hpresentation']

/-- A pointwise connection identifies the unique generator of every projection-vertical tangent. -/
theorem vertical_tangent_eq_fundamental_connection
    (connection : PointwisePrincipalConnectionData smoothBundle)
    (p : P) (v : TangentSpace IP p)
    (vertical : mfderiv IP IB torsor.projection p v = 0) :
    v = principalFundamentalVector smoothBundle p
      (connection.form.evalOne p v) := by
  obtain ⟨X, hX⟩ := vertical_tangent_exists_fundamental
    (smoothBundle := smoothBundle) p v vertical
  have hform : connection.form.evalOne p v = X := by
    rw [hX]
    exact connection.vertical_normalization p X
  simpa [hform] using hX

/-- Existential uniqueness form of vertical tangent generation. -/
theorem vertical_tangent_existsUnique_fundamental
    (connection : PointwisePrincipalConnectionData smoothBundle)
    (p : P) (v : TangentSpace IP p)
    (vertical : mfderiv IP IB torsor.projection p v = 0) :
    ∃! X : GroupLieAlgebra IG G,
      v = principalFundamentalVector smoothBundle p X := by
  refine ⟨connection.form.evalOne p v,
    vertical_tangent_eq_fundamental_connection connection p v vertical, ?_⟩
  intro X hX
  rw [hX, connection.vertical_normalization]

end

end YangMills.Geometry
