/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.PrincipalVerticalTangentGeneration
import YangMills.Geometry.PrincipalFormCovariantExteriorVertical
import YangMills.Geometry.PrincipalFormSmoothDescent
import Mathlib.Geometry.Manifold.GroupLieAlgebra

/-!
# Smooth fundamental vector fields and right-action curves

A fixed Lie-algebra generator determines a globally smooth principal fundamental vector field, whose
values are projection-vertical. Smooth group curves through the identity have the expected
right-action velocity, and finite right-adjoint equivariance is exposed along such curves. No
one-parameter subgroup, exponential map, or infinitesimal derivative formula is assumed.
-/

namespace YangMills.Geometry

open Set Bundle
open scoped Manifold ContDiff
open YangMills.Mathematics

universe uEG uHG uEB uHB uEP uHP uG uB uP

noncomputable section

variable
    {EG : Type uEG} {HG : Type uHG}
    [NormedAddCommGroup EG] [NormedSpace ℝ EG] [TopologicalSpace HG]
    {EB : Type uEB} {HB : Type uHB}
    [NormedAddCommGroup EB] [NormedSpace ℝ EB] [TopologicalSpace HB]
    {EP : Type uEP} {HP : Type uHP}
    [NormedAddCommGroup EP] [NormedSpace ℝ EP] [TopologicalSpace HP]
    {G : Type uG} {B : Type uB} {P : Type uP}
    [Group G] [TopologicalSpace G] [TopologicalSpace B] [TopologicalSpace P]
    [IsTopologicalGroup G]
    {IG : ModelWithCorners ℝ EG HG}
    {IB : ModelWithCorners ℝ EB HB}
    {IP : ModelWithCorners ℝ EP HP}
    [ChartedSpace HG G] [LieGroup IG ∞ G]
    [ChartedSpace HB B] [IsManifold IB ∞ B]
    [ChartedSpace HP P] [IsManifold IP ∞ P]
    {torsor : PrincipalBundleTorsorData G B P}
    {bundle : TopologicalPrincipalBundleData torsor}
    {smoothBundle : SmoothPrincipalBundleData IB IG IP torsor bundle}

/-- The global fundamental vector field generated by a fixed Lie algebra element. -/
def principalFundamentalVectorField (X : GroupLieAlgebra IG G) (p : P) :
    TangentSpace IP p :=
  principalFundamentalVector smoothBundle p X

/-- The fundamental vector field is smooth, directly from smoothness of the joint right action. -/
theorem principalFundamentalVectorField_contMDiff (X : GroupLieAlgebra IG G) :
    ContMDiff IP (IP.tangent) ∞
      (fun p : P =>
        (⟨p, principalFundamentalVectorField (smoothBundle := smoothBundle) X p⟩ :
          TangentBundle IP P)) := by
  let fp : P → TangentBundle IP P := fun p => ⟨p, 0⟩
  have hfp : ContMDiff IP (IP.tangent) ∞ fp :=
    contMDiff_zeroSection ℝ (TangentSpace IP)
  let fX : P → TangentBundle IG G := fun _ => ⟨(1 : G), X⟩
  have hfX : ContMDiff IP (IG.tangent) ∞ fX :=
    contMDiff_const
  let F₁ : P → TangentBundle IP P × TangentBundle IG G := fun p => (fp p, fX p)
  have hF₁ : ContMDiff IP
      ((IP.tangent).prod (IG.tangent))
      ∞ F₁ := hfp.prodMk hfX
  let F₂ : TangentBundle IP P × TangentBundle IG G → TangentBundle (IP.prod IG) (P × G) :=
    (equivTangentBundleProd IP P IG G).symm
  have hF₂ : ContMDiff
      ((IP.tangent).prod (IG.tangent))
      ((IP.prod IG).tangent)
      ∞ F₂ := contMDiff_equivTangentBundleProd_symm
  let action : P × G → P := fun z => torsor.rightAction z.1 z.2
  let F₃ : TangentBundle (IP.prod IG) (P × G) → TangentBundle IP P :=
    tangentMap (IP.prod IG) IP action
  have hF₃ : ContMDiff
      ((IP.prod IG).tangent)
      (IP.tangent) ∞ F₃ := by
    apply ContMDiff.contMDiff_tangentMap smoothBundle.rightAction_smooth
    simp
  have heq :
      (fun p : P =>
        (⟨p, principalFundamentalVectorField (smoothBundle := smoothBundle) X p⟩ :
          TangentBundle IP P)) = F₃ ∘ F₂ ∘ F₁ := by
    funext p
    simp only [F₃, F₂, F₁, fp, fX, Function.comp_apply, tangentMap]
    change (⟨p, principalFundamentalVectorField (smoothBundle := smoothBundle) X p⟩ :
      TangentBundle IP P) =
        (⟨action (p, 1), mfderiv (IP.prod IG) IP action (p, 1) (0, X)⟩ :
          TangentBundle IP P)
    apply TotalSpace.ext
    · change p = torsor.rightAction p 1
      exact (torsor.right_one p).symm
    · change principalFundamentalVector smoothBundle p X ≍
        mfderiv (IP.prod IG) IP action (p, 1) (0, X)
      let embed : G → P × G := fun g => (p, g)
      have hembed : ContMDiff IG (IP.prod IG) ∞ embed :=
        contMDiff_const.prodMk contMDiff_id
      have hchain := mfderiv_comp (I := IG) (I' := IP.prod IG) (I'' := IP)
        (f := embed) (g := action) (1 : G)
        (smoothBundle.rightAction_smooth.mdifferentiableAt (by simp))
        (hembed.mdifferentiableAt (by simp))
      rw [mfderiv_prod_right] at hchain
      have happ := congrArg (fun L => L X) hchain
      change principalFundamentalVector smoothBundle p X =
        mfderiv (IP.prod IG) IP action (p, 1) (0, X) at happ
      exact heq_of_eq happ
  rw [heq]
  exact (hF₃.comp hF₂).comp hF₁

/-- The fundamental field supplies an admissible smooth field for every positive Cartan
certificate, on every chosen local set. -/
theorem principalFundamentalVectorField_isSmoothOn
    (X : GroupLieAlgebra IG G) (s : Set P) :
    ManifoldTangentField.IsSmoothOn IP s
      (principalFundamentalVectorField (smoothBundle := smoothBundle) X) :=
  (principalFundamentalVectorField_contMDiff (smoothBundle := smoothBundle) X).contMDiffOn

/-- Every value of the global fundamental field is vertical. -/
theorem principalFundamentalVectorField_projection_eq_zero
    (X : GroupLieAlgebra IG G) (p : P) :
    mfderiv IP IB torsor.projection p
      (principalFundamentalVectorField (smoothBundle := smoothBundle) X p) = 0 :=
  principalFundamentalVector_projection_eq_zero p X

/-- A smooth group curve through the identity with velocity `X` generates the fundamental
vertical vector through the principal right action. This is the exact right-action curve chain rule
available without a global Lie exponential API. -/
theorem principalRightActionCurve_mfderiv
    (p : P) (X : GroupLieAlgebra IG G) (curve : ℝ → G)
    (curve_zero : curve 0 = 1)
    (curve_smooth : ContMDiffAt (modelWithCornersSelf ℝ ℝ) IG ∞ curve 0)
    (curve_velocity :
      mfderiv (modelWithCornersSelf ℝ ℝ) IG curve 0
        ((NormedSpace.fromTangentSpace (0 : ℝ)).symm 1) = X) :
    mfderiv (modelWithCornersSelf ℝ ℝ) IP
      (fun t => torsor.rightAction p (curve t)) 0
        ((NormedSpace.fromTangentSpace (0 : ℝ)).symm 1) =
        principalFundamentalVector smoothBundle p X := by
  have horbit := (principalOrbitMap_smooth smoothBundle p).mdifferentiableAt (x := curve 0) (by simp)
  have hcurve := curve_smooth.mdifferentiableAt (by simp)
  have hchain := mfderiv_comp
    (I := modelWithCornersSelf ℝ ℝ) (I' := IG) (I'' := IP)
    (f := curve) (g := principalOrbitMap torsor p) 0 horbit hcurve
  have happ := congrArg
    (fun L => L ((NormedSpace.fromTangentSpace (0 : ℝ)).symm 1)) hchain
  change mfderiv (modelWithCornersSelf ℝ ℝ) IP
      (principalOrbitMap torsor p ∘ curve) 0
        ((NormedSpace.fromTangentSpace (0 : ℝ)).symm 1) =
    mfderiv IG IP (principalOrbitMap torsor p) (curve 0)
      (mfderiv (modelWithCornersSelf ℝ ℝ) IG curve 0
        ((NormedSpace.fromTangentSpace (0 : ℝ)).symm 1)) at happ
  rw [curve_zero] at curve_velocity happ
  rw [curve_velocity] at happ
  exact happ

namespace PrincipalForm

/-- Right-adjoint equivariance gives the exact finite right-action identity when all tangent arguments are
transported by the differential of the same principal right action. -/
theorem rightAdEquivariant_along_curve
    {k : ℕ}
    (form : ManifoldDifferentialForm IP P (GroupLieAlgebra IG G) k)
    (equivariant : IsRightAdEquivariant smoothBundle form)
    (p : P) (vectors : Fin k → TangentSpace IP p) (curve : ℝ → G) (t : ℝ) :
    form (torsor.rightAction p (curve t))
        (fun i => principalRightTranslationDifferential smoothBundle p (curve t) (vectors i)) =
      lieGroupAdjoint IG (curve t)⁻¹ (form p vectors) :=
  equivariant (curve t) p vectors

end PrincipalForm


end
end YangMills.Geometry
