/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Classical.EuclideanCurvatureDensity
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Euclidean Yang--Mills action relative to a designated measure

This module integrates the exact chosen-orthonormal curvature scalar with the normalization in Clay
/Jaffe--Witten equation (1). The integration interface is deliberately explicit:

* the measurable structure is the Borel structure generated by the manifold topology;
* the measure is designated model data and is **not** called Riemannian volume;
* integrability of the exact curvature scalar is required in the action data, so Mathlib's
  nonintegrable-zero convention cannot silently yield a finite action;
* the coupling is required to be strictly positive;
* no general Hodge-star or basis-independence theorem is asserted.

A future metric-volume compatibility theorem can strengthen this relative-to-measure action without
changing its exact curvature, pairing, or normalization.
-/

namespace YangMills.Classical

open Bundle MeasureTheory
open scoped Bundle ContDiff Manifold Topology

universe uEG uHG uEB uHB uEP uHP uG uB uP

noncomputable section

variable
    {EG : Type uEG} {HG : Type uHG}
    [NormedAddCommGroup EG] [NormedSpace ℝ EG] [TopologicalSpace HG]
    {EB : Type uEB} {HB : Type uHB}
    [NormedAddCommGroup EB] [NormedSpace ℝ EB] [TopologicalSpace HB]
    {EP : Type uEP} {HP : Type uHP}
    [NormedAddCommGroup EP] [NormedSpace ℝ EP] [TopologicalSpace HP]
    {G : Type uG} {B : Type uB} {P : Type uP}
    [Group G] [TopologicalSpace G] [TopologicalSpace B] [TopologicalSpace P]
    [MeasurableSpace B] [IsTopologicalGroup G]
    {IG : ModelWithCorners ℝ EG HG}
    {IB : ModelWithCorners ℝ EB HB}
    {IP : ModelWithCorners ℝ EP HP}
    [ChartedSpace HG G] [LieGroup IG ∞ G]
    [ChartedSpace HB B] [IsManifold IB ∞ B]
    [ChartedSpace HP P] [IsManifold IP ∞ P]
    {torsor : YangMills.Geometry.PrincipalBundleTorsorData G B P}
    {bundle : YangMills.Geometry.TopologicalPrincipalBundleData torsor}
    {smoothBundle : YangMills.Geometry.SmoothPrincipalBundleData IB IG IP torsor bundle}
    [FiniteDimensional ℝ EG] [FiniteDimensional ℝ EB]

open YangMills.Geometry

/-- Analytic input for the Euclidean action, indexed by the exact geometric scalar it integrates.

The integrability field is not a disconnected regularity witness: its function is definitionally
the chosen contraction of the exact smoothly descended curvature from the same connection,
exterior-derivative datum, and same-index structure certificate. -/
structure EuclideanActionAnalyticData
    (geometry : EuclideanMetricData (IB := IB) (B := B))
    (inner : InvariantInnerProductData (I := IG) (G := G))
    (connection : PrincipalConnectionData smoothBundle)
    (exterior : PrincipalConnectionExteriorDerivativeData connection)
    (certificate : PrincipalCurvatureStructureCertificate smoothBundle connection exterior) where
  measurable_is_borel : BorelSpace B
  measure : Measure B
  coupling : ℝ
  coupling_pos : 0 < coupling
  density_integrable : Integrable
    (geometry.chosenOrthonormalCurvatureDensity inner connection exterior certificate) measure

namespace EuclideanActionAnalyticData

/-- The exact coefficient from Clay/Jaffe--Witten equation (1). The inner `1/2` alternating-form
convention remains separately visible in `chosenOrthonormalTwoFormContraction`. -/
def actionCoefficient
    {geometry : EuclideanMetricData (IB := IB) (B := B)}
    {inner : InvariantInnerProductData (I := IG) (G := G)}
    {connection : PrincipalConnectionData smoothBundle}
    {exterior : PrincipalConnectionExteriorDerivativeData connection}
    {certificate : PrincipalCurvatureStructureCertificate smoothBundle connection exterior}
    (analytic : EuclideanActionAnalyticData geometry inner connection exterior certificate) : ℝ :=
  (4 * analytic.coupling ^ 2)⁻¹

/-- Strict positivity of the physical action coefficient uses the required positive coupling. -/
theorem actionCoefficient_pos
    {geometry : EuclideanMetricData (IB := IB) (B := B)}
    {inner : InvariantInnerProductData (I := IG) (G := G)}
    {connection : PrincipalConnectionData smoothBundle}
    {exterior : PrincipalConnectionExteriorDerivativeData connection}
    {certificate : PrincipalCurvatureStructureCertificate smoothBundle connection exterior}
    (analytic : EuclideanActionAnalyticData geometry inner connection exterior certificate) :
    0 < analytic.actionCoefficient := by
  exact inv_pos.mpr (mul_pos (by norm_num) (pow_pos analytic.coupling_pos 2))

end EuclideanActionAnalyticData

/-- The Euclidean Yang--Mills action relative to the designated Borel measure.

This is not yet advertised as integration against Riemannian volume, and the chosen orthonormal
contraction is not yet identified with a general Hodge-star expression. -/
def euclideanYangMillsActionRelativeToMeasure
    (geometry : EuclideanMetricData (IB := IB) (B := B))
    (inner : InvariantInnerProductData (I := IG) (G := G))
    (connection : PrincipalConnectionData smoothBundle)
    (exterior : PrincipalConnectionExteriorDerivativeData connection)
    (certificate : PrincipalCurvatureStructureCertificate smoothBundle connection exterior)
    (analytic : EuclideanActionAnalyticData geometry inner connection exterior certificate) : ℝ :=
  analytic.actionCoefficient *
    ∫ b, geometry.chosenOrthonormalCurvatureDensity
      inner connection exterior certificate b ∂analytic.measure

/-- The relative-to-measure action unfolds only to the designated measure, positive coupling, and
exact chosen curvature scalar. -/
@[simp]
theorem euclideanYangMillsActionRelativeToMeasure_eq
    (geometry : EuclideanMetricData (IB := IB) (B := B))
    (inner : InvariantInnerProductData (I := IG) (G := G))
    (connection : PrincipalConnectionData smoothBundle)
    (exterior : PrincipalConnectionExteriorDerivativeData connection)
    (certificate : PrincipalCurvatureStructureCertificate smoothBundle connection exterior)
    (analytic : EuclideanActionAnalyticData geometry inner connection exterior certificate) :
    euclideanYangMillsActionRelativeToMeasure
        geometry inner connection exterior certificate analytic =
      (4 * analytic.coupling ^ 2)⁻¹ *
        ∫ b, geometry.chosenOrthonormalCurvatureDensity
          inner connection exterior certificate b ∂analytic.measure :=
  rfl

/-- The relative-to-measure Euclidean action is nonnegative. -/
theorem euclideanYangMillsActionRelativeToMeasure_nonnegative
    (geometry : EuclideanMetricData (IB := IB) (B := B))
    (inner : InvariantInnerProductData (I := IG) (G := G))
    (connection : PrincipalConnectionData smoothBundle)
    (exterior : PrincipalConnectionExteriorDerivativeData connection)
    (certificate : PrincipalCurvatureStructureCertificate smoothBundle connection exterior)
    (analytic : EuclideanActionAnalyticData geometry inner connection exterior certificate) :
    0 ≤ euclideanYangMillsActionRelativeToMeasure
      geometry inner connection exterior certificate analytic := by
  apply mul_nonneg (le_of_lt analytic.actionCoefficient_pos)
  exact integral_nonneg
    (geometry.chosenOrthonormalCurvatureDensity_nonnegative
      inner connection exterior certificate)

end

end YangMills.Classical
