/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Mathematics.CompactRepresentationAveragedInnerProductTopology

/-!
# Hostile probes for the averaged inner-product topology
-/

namespace YangMills
namespace Mathematics
namespace CompactRepresentationAveragedInnerProductTopology
namespace Probes

open Bornology

noncomputable section

universe uG

variable
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {n : ℕ} (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (hρ : Continuous ρ)

/-- The continuous real bilinear package retains the exact averaged Hermitian pairing. -/
theorem exact_real_pairing (first second : Fin n → ℂ) :
    compactRepresentationAveragedRealPairing ρ hρ first second =
      (compactRepresentationAveragedPairing ρ first second).re :=
  compactRepresentationAveragedRealPairing_apply ρ hρ first second

include hρ in
/-- The bounded ellipsoid is literally the unit sublevel set of the same averaged self-pairing. -/
theorem exact_complex_unit_ellipsoid :
    IsVonNBounded ℂ {vector : Fin n → ℂ |
      (compactRepresentationAveragedPairing ρ vector vector).re < 1} :=
  compactRepresentationAveraged_unitEllipsoid_isVonNBounded ρ hρ

/-- The topology comparison names the original coordinate topology and the exact norm generated by
the same averaged core. -/
theorem exact_averaged_core_topology :
    (inferInstance : TopologicalSpace (Fin n → ℂ)) =
      (@InnerProductSpace.Core.toNormedAddCommGroup ℂ (Fin n → ℂ) _ _ _
        (compactRepresentationAveragedInnerProductCore ρ hρ)).toMetricSpace.toUniformSpace.toTopologicalSpace :=
  compactRepresentationAveragedInnerProductCore_topology_eq ρ hρ

/-- Hostile topology probe: claiming that the exact averaged core induces a different topology is
contradictory. -/
theorem changed_averaged_core_topology_blocked
    (changed : (inferInstance : TopologicalSpace (Fin n → ℂ)) ≠
      (@InnerProductSpace.Core.toNormedAddCommGroup ℂ (Fin n → ℂ) _ _ _
        (compactRepresentationAveragedInnerProductCore ρ hρ)).toMetricSpace.toUniformSpace.toTopologicalSpace) :
    False :=
  changed (compactRepresentationAveragedInnerProductCore_topology_eq ρ hρ)

/-- Anti-collapse probe: on any supplied nonzero vector, the exact continuous real pairing cannot
be the zero bilinear map. -/
theorem nonzero_vector_blocks_zero_real_pairing
    (vector : Fin n → ℂ) (vector_ne : vector ≠ 0)
    (collapsed : compactRepresentationAveragedRealPairing ρ hρ = 0) : False := by
  have positive := compactRepresentationAveragedNormSq_pos ρ hρ vector vector_ne
  have selfReal := compactRepresentationAveragedPairing_self_re ρ hρ vector
  have zeroValue : compactRepresentationAveragedRealPairing ρ hρ vector vector = 0 := by
    rw [collapsed]
    rfl
  rw [compactRepresentationAveragedRealPairing_apply, selfReal] at zeroValue
  linarith

/-- Dimension-zero probe: topology compatibility does not smuggle in a positive-dimension
hypothesis. -/
theorem zero_dimension_topology
    (ρ₀ : G →* Matrix (Fin 0) (Fin 0) ℂ) (hρ₀ : Continuous ρ₀) :
    (inferInstance : TopologicalSpace (Fin 0 → ℂ)) =
      (@InnerProductSpace.Core.toNormedAddCommGroup ℂ (Fin 0 → ℂ) _ _ _
        (compactRepresentationAveragedInnerProductCore ρ₀ hρ₀)).toMetricSpace.toUniformSpace.toTopologicalSpace :=
  compactRepresentationAveragedInnerProductCore_topology_eq ρ₀ hρ₀

end

end Probes
end CompactRepresentationAveragedInnerProductTopology
end Mathematics
end YangMills
