/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Mathematics.CompactRepresentationAveragedInnerProductTopology

/-!
# A topology-compatible normed realization of the averaged inner product

The averaged inner-product core has already been proved to induce the original finite coordinate
topology. This file exposes Mathlib's resulting topology-compatible normed additive group, complex
normed space, and inner-product structures as named values. They are not installed globally.

Every group matrix is also packaged as an exact linear equivalence whose inverse is the matrix at
`g⁻¹`. Its action preserves the named averaged norm. This is the intrinsic unitarity statement on
the original coordinate carrier. Choosing an orthonormal basis and deriving an explicit conjugated
unitary matrix representation remain separate tasks.
-/

namespace YangMills
namespace Mathematics

open Bornology

noncomputable section

universe uG

/-- The normed additive-group structure generated by the averaged inner product, adjusted through
the proved topology equality so that its topology is definitionally the original coordinate
topology. -/
@[reducible]
noncomputable def compactRepresentationAveragedNormedAddCommGroup
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {n : ℕ} (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (hρ : Continuous ρ) :
    NormedAddCommGroup (Fin n → ℂ) := by
  let core := compactRepresentationAveragedInnerProductCore ρ hρ
  letI : InnerProductSpace.Core ℂ (Fin n → ℂ) := core
  letI : Inner ℂ (Fin n → ℂ) := core.toCore.toInner
  exact InnerProductSpace.Core.toNormedAddCommGroupOfTopology
    (compactRepresentationAveragedInnerProductCore_diagonal_continuousAt ρ hρ)
    (by
      change IsVonNBounded ℂ {vector : Fin n → ℂ |
        (compactRepresentationAveragedPairing ρ vector vector).re < 1}
      exact compactRepresentationAveraged_unitEllipsoid_isVonNBounded ρ hρ)

/-- The complex normed-space structure for the exact averaged normed additive group. -/
@[reducible]
noncomputable def compactRepresentationAveragedNormedSpace
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {n : ℕ} (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (hρ : Continuous ρ) :
    @NormedSpace ℂ (Fin n → ℂ) _
      (compactRepresentationAveragedNormedAddCommGroup ρ hρ).toSeminormedAddCommGroup := by
  letI : NormedAddCommGroup (Fin n → ℂ) :=
    compactRepresentationAveragedNormedAddCommGroup ρ hρ
  let core := compactRepresentationAveragedInnerProductCore ρ hρ
  letI : InnerProductSpace.Core ℂ (Fin n → ℂ) := core
  letI : Inner ℂ (Fin n → ℂ) := core.toCore.toInner
  exact InnerProductSpace.Core.toNormedSpaceOfTopology
    (compactRepresentationAveragedInnerProductCore_diagonal_continuousAt ρ hρ)
    (by
      change IsVonNBounded ℂ {vector : Fin n → ℂ |
        (compactRepresentationAveragedPairing ρ vector vector).re < 1}
      exact compactRepresentationAveraged_unitEllipsoid_isVonNBounded ρ hρ)

/-- The exact averaged inner-product structure over the topology-compatible averaged norm. -/
@[reducible]
noncomputable def compactRepresentationAveragedInnerProductSpace
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {n : ℕ} (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (hρ : Continuous ρ) :
    @InnerProductSpace ℂ (Fin n → ℂ) _
      (compactRepresentationAveragedNormedAddCommGroup ρ hρ).toSeminormedAddCommGroup := by
  letI : NormedAddCommGroup (Fin n → ℂ) :=
    compactRepresentationAveragedNormedAddCommGroup ρ hρ
  let core := compactRepresentationAveragedInnerProductCore ρ hρ
  letI : InnerProductSpace.Core ℂ (Fin n → ℂ) := core
  letI : Inner ℂ (Fin n → ℂ) := core.toCore.toInner
  exact InnerProductSpace.ofCoreOfTopology core
    (compactRepresentationAveragedInnerProductCore_diagonal_continuousAt ρ hρ)
    (by
      change IsVonNBounded ℂ {vector : Fin n → ℂ |
        (compactRepresentationAveragedPairing ρ vector vector).re < 1}
      exact compactRepresentationAveraged_unitEllipsoid_isVonNBounded ρ hρ)

/-- The named topology-compatible inner-product structure retains exactly the normalized-Haar
averaged pairing. -/
@[simp]
theorem compactRepresentationAveragedInnerProductSpace_inner
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {n : ℕ} (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (hρ : Continuous ρ)
    (first second : Fin n → ℂ) :
    @inner ℂ (Fin n → ℂ)
      (@InnerProductSpace.toCore ℂ (Fin n → ℂ) _
        (compactRepresentationAveragedNormedAddCommGroup ρ hρ)
        (compactRepresentationAveragedInnerProductSpace ρ hρ)).toInner first second =
      compactRepresentationAveragedPairing ρ first second := by
  rfl

/-- The action of any group element is an exact complex-linear equivalence on coordinate vectors;
its inverse is the action at `g⁻¹`. -/
noncomputable def matrixRepresentationLinearEquiv
    {G : Type uG} [Group G] {n : ℕ}
    (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (g : G) :
    (Fin n → ℂ) ≃ₗ[ℂ] (Fin n → ℂ) := by
  apply LinearEquiv.ofLinear (matrixRepresentation ρ g)
    (matrixRepresentation ρ (g⁻¹))
  · apply LinearMap.ext
    intro vector
    change Matrix.mulVec (ρ g) (Matrix.mulVec (ρ (g⁻¹)) vector) = vector
    rw [Matrix.mulVec_mulVec, ← map_mul, mul_inv_cancel, map_one, Matrix.one_mulVec]
  · apply LinearMap.ext
    intro vector
    change Matrix.mulVec (ρ (g⁻¹)) (Matrix.mulVec (ρ g) vector) = vector
    rw [Matrix.mulVec_mulVec, ← map_mul, inv_mul_cancel, map_one, Matrix.one_mulVec]

/-- Every representation matrix preserves the exact named averaged norm. This is intrinsic
unitarity before choosing orthonormal coordinates. -/
theorem compactRepresentationAveragedAction_norm
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {n : ℕ} (ρ : G →* Matrix (Fin n) (Fin n) ℂ) (hρ : Continuous ρ)
    (g : G) (vector : Fin n → ℂ) :
    @norm (Fin n → ℂ)
      (compactRepresentationAveragedNormedAddCommGroup ρ hρ).toNorm
      (Matrix.mulVec (ρ g) vector) =
    @norm (Fin n → ℂ)
      (compactRepresentationAveragedNormedAddCommGroup ρ hρ).toNorm vector := by
  change Real.sqrt ((compactRepresentationAveragedPairing ρ
    (Matrix.mulVec (ρ g) vector) (Matrix.mulVec (ρ g) vector)).re) =
      Real.sqrt ((compactRepresentationAveragedPairing ρ vector vector).re)
  rw [compactRepresentationAveragedPairing_invariant]

end

end Mathematics
end YangMills
