/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import Mathlib.LinearAlgebra.Dimension.Constructions
import YangMills.Mathematics.CompactUnitaryCharacterOrthogonality

/-!
# Finite subspaces generated by inequivalent compact irreducible characters

For a finite indexed family of positive-dimensional, pairwise inequivalent, irreducible unitary
matrix representations, this file constructs the character synthesis map

`c ↦ (g ↦ ∑ᵢ cᵢ tr(ρᵢ(g)))`.

Every synthesized function is continuous and central. Character orthogonality proves exact
coefficient analysis, the finite algebraic pairing

`∫ conj(∑cᵢχᵢ) (∑eᵢχᵢ) dμ_H = ∑ conj(cᵢ)eᵢ`,

injectivity, and exact dimension equal to the number of represented inequivalent characters. This
is a finite central-character subspace; it does not assert that all irreducible characters have been
enumerated or that their span is dense or complete among central functions.
-/

namespace YangMills
namespace Mathematics

open MeasureTheory

noncomputable section

universe uG uι

/-- Linear synthesis from a finite coefficient family to the matching finite sum of matrix trace
characters. -/
def finiteCharacterSynthesis
    {G : Type uG} [Group G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ) :
    (ι → ℂ) →ₗ[ℂ] (G → ℂ) where
  toFun coefficients g :=
    ∑ i, coefficients i * Matrix.trace (ρ i g)
  map_add' first second := by
    funext g
    change (∑ i, (first i + second i) * Matrix.trace (ρ i g)) =
      (∑ i, first i * Matrix.trace (ρ i g)) +
        ∑ i, second i * Matrix.trace (ρ i g)
    simp [add_mul, Finset.sum_add_distrib]
  map_smul' scalar coefficients := by
    funext g
    change (∑ i, (scalar * coefficients i) * Matrix.trace (ρ i g)) =
      scalar * ∑ i, coefficients i * Matrix.trace (ρ i g)
    simp_rw [mul_assoc, ← Finset.mul_sum]

@[simp]
theorem finiteCharacterSynthesis_apply
    {G : Type uG} [Group G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (coefficients : ι → ℂ) (g : G) :
    finiteCharacterSynthesis dimension ρ coefficients g =
      ∑ i, coefficients i * Matrix.trace (ρ i g) :=
  rfl

/-- Every synthesized finite character sum is a central function. -/
theorem finiteCharacterSynthesis_conj
    {G : Type uG} [Group G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (coefficients : ι → ℂ) (g h : G) :
    finiteCharacterSynthesis dimension ρ coefficients (h * g * h⁻¹) =
      finiteCharacterSynthesis dimension ρ coefficients g := by
  rw [finiteCharacterSynthesis_apply, finiteCharacterSynthesis_apply]
  apply Finset.sum_congr rfl
  intro i _
  rw [matrixRepresentation_trace_conj]

/-- Every finite character synthesis is continuous when all represented matrix families are
continuous. -/
theorem continuous_finiteCharacterSynthesis
    {G : Type uG} [Group G] [TopologicalSpace G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (hρ : ∀ i, Continuous (ρ i)) (coefficients : ι → ℂ) :
    Continuous (finiteCharacterSynthesis dimension ρ coefficients) := by
  change Continuous (fun g =>
    ∑ i, coefficients i * Matrix.trace (ρ i g))
  fun_prop

/-- Analysis against one represented irreducible character exactly recovers its synthesized
coefficient. The inequivalence hypothesis is oriented to match the target character in the
conjugated first slot. -/
theorem normalizedCompactHaar_character_analysis_synthesis
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (hρ : ∀ i, Continuous (ρ i))
    (unitaryρ : ∀ i g, star (ρ i g) * ρ i g = 1)
    [∀ i, Representation.IsIrreducible (matrixRepresentation (ρ i))]
    (dimension_pos : ∀ i, 0 < dimension i)
    (pairwiseInequivalent : ∀ i j, i ≠ j →
      IsEmpty (Representation.Equiv
        (matrixRepresentation (ρ j)) (matrixRepresentation (ρ i))))
    (coefficients : ι → ℂ) (index : ι) :
    (∫ g, star (Matrix.trace (ρ index g)) *
        finiteCharacterSynthesis dimension ρ coefficients g
      ∂normalizedCompactHaarMeasure G) = coefficients index := by
  let μ := normalizedCompactHaarMeasure G
  letI : IsProbabilityMeasure μ := normalizedCompactHaarMeasure_isProbability G
  have integrableTerm (other : ι) :
      Integrable (fun g =>
        star (Matrix.trace (ρ index g)) *
          (coefficients other * Matrix.trace (ρ other g))) μ := by
    have continuousTerm : Continuous (fun g =>
        star (Matrix.trace (ρ index g)) *
          (coefficients other * Matrix.trace (ρ other g))) := by
      fun_prop
    simpa only [integrableOn_univ] using
      continuousTerm.continuousOn.integrableOn_compact
        (μ := μ) isCompact_univ
  calc
    (∫ g, star (Matrix.trace (ρ index g)) *
        finiteCharacterSynthesis dimension ρ coefficients g ∂μ) =
        ∫ g, ∑ other,
          star (Matrix.trace (ρ index g)) *
            (coefficients other * Matrix.trace (ρ other g)) ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with g
      rw [finiteCharacterSynthesis_apply, Finset.mul_sum]
    _ = ∑ other,
        ∫ g, star (Matrix.trace (ρ index g)) *
          (coefficients other * Matrix.trace (ρ other g)) ∂μ := by
      rw [integral_finsetSum Finset.univ]
      intro other _
      exact integrableTerm other
    _ = ∑ other, coefficients other *
        (if other = index then 1 else 0) := by
      apply Finset.sum_congr rfl
      intro other _
      calc
        (∫ g, star (Matrix.trace (ρ index g)) *
            (coefficients other * Matrix.trace (ρ other g)) ∂μ) =
            coefficients other *
              ∫ g, star (Matrix.trace (ρ index g)) *
                Matrix.trace (ρ other g) ∂μ := by
          rw [← integral_const_mul]
          apply integral_congr_ae
          filter_upwards [] with g
          ring
        _ = coefficients other *
            (if other = index then 1 else 0) := by
          by_cases equality : other = index
          · subst other
            simp only [if_pos]
            rw [normalizedCompactHaar_character_normSq_integral
              (ρ index) (hρ index) (unitaryρ index)
              (dimension_pos index), mul_one]
          · letI := pairwiseInequivalent index other (Ne.symm equality)
            simp only [equality, if_false, mul_zero]
            rw [normalizedCompactHaar_character_orthogonality_inequivalent
              (ρ index) (ρ other) (hρ index) (hρ other)
              (unitaryρ index)]
            simp
    _ = coefficients index := by simp

/-- Finite sums of pairwise inequivalent normalized irreducible characters have the exact coordinate
pairing. -/
theorem normalizedCompactHaar_finiteCharacterSynthesis_pairing
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (hρ : ∀ i, Continuous (ρ i))
    (unitaryρ : ∀ i g, star (ρ i g) * ρ i g = 1)
    [∀ i, Representation.IsIrreducible (matrixRepresentation (ρ i))]
    (dimension_pos : ∀ i, 0 < dimension i)
    (pairwiseInequivalent : ∀ i j, i ≠ j →
      IsEmpty (Representation.Equiv
        (matrixRepresentation (ρ j)) (matrixRepresentation (ρ i))))
    (first second : ι → ℂ) :
    (∫ g, star (finiteCharacterSynthesis dimension ρ first g) *
        finiteCharacterSynthesis dimension ρ second g
      ∂normalizedCompactHaarMeasure G) =
      ∑ i, star (first i) * second i := by
  let μ := normalizedCompactHaarMeasure G
  letI : IsProbabilityMeasure μ := normalizedCompactHaarMeasure_isProbability G
  have integrableTerm (index : ι) :
      Integrable (fun g =>
        star (first index * Matrix.trace (ρ index g)) *
          finiteCharacterSynthesis dimension ρ second g) μ := by
    have continuousTerm : Continuous (fun g =>
        star (first index * Matrix.trace (ρ index g)) *
          finiteCharacterSynthesis dimension ρ second g) := by
      apply Continuous.mul
      · exact (Continuous.const_mul
          (continuous_matrixRepresentation_trace (ρ index) (hρ index))
          (first index)).star
      · exact continuous_finiteCharacterSynthesis
          dimension ρ hρ second
    simpa only [integrableOn_univ] using
      continuousTerm.continuousOn.integrableOn_compact
        (μ := μ) isCompact_univ
  calc
    (∫ g, star (finiteCharacterSynthesis dimension ρ first g) *
        finiteCharacterSynthesis dimension ρ second g ∂μ) =
        ∫ g, ∑ index,
          star (first index * Matrix.trace (ρ index g)) *
            finiteCharacterSynthesis dimension ρ second g ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with g
      rw [finiteCharacterSynthesis_apply]
      change (starRingEnd ℂ)
          (∑ index, first index * Matrix.trace (ρ index g)) * _ = _
      rw [map_sum, Finset.sum_mul]
      simp only [starRingEnd_apply]
    _ = ∑ index,
        ∫ g, star (first index * Matrix.trace (ρ index g)) *
          finiteCharacterSynthesis dimension ρ second g ∂μ := by
      rw [integral_finsetSum Finset.univ]
      intro index _
      exact integrableTerm index
    _ = ∑ index, star (first index) * second index := by
      apply Finset.sum_congr rfl
      intro index _
      have analysis := normalizedCompactHaar_character_analysis_synthesis
        dimension ρ hρ unitaryρ dimension_pos pairwiseInequivalent
        second index
      have factorIntegrand :
          (fun g => star (first index * Matrix.trace (ρ index g)) *
              finiteCharacterSynthesis dimension ρ second g) =
            fun g => star (first index) *
              (star (Matrix.trace (ρ index g)) *
                finiteCharacterSynthesis dimension ρ second g) := by
        funext g
        change (starRingEnd ℂ)
            (first index * Matrix.trace (ρ index g)) * _ =
          (starRingEnd ℂ) (first index) *
            ((starRingEnd ℂ) (Matrix.trace (ρ index g)) * _)
        rw [map_mul]
        ring
      rw [factorIntegrand, integral_const_mul, analysis]

/-- Character synthesis is injective for a finite pairwise inequivalent irreducible family. -/
theorem finiteCharacterSynthesis_injective
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (hρ : ∀ i, Continuous (ρ i))
    (unitaryρ : ∀ i g, star (ρ i g) * ρ i g = 1)
    [∀ i, Representation.IsIrreducible (matrixRepresentation (ρ i))]
    (dimension_pos : ∀ i, 0 < dimension i)
    (pairwiseInequivalent : ∀ i j, i ≠ j →
      IsEmpty (Representation.Equiv
        (matrixRepresentation (ρ j)) (matrixRepresentation (ρ i)))) :
    Function.Injective (finiteCharacterSynthesis dimension ρ) := by
  intro first second functionsEqual
  funext index
  have analysesEqual := congrArg (fun f : G → ℂ =>
    ∫ g, star (Matrix.trace (ρ index g)) * f g
      ∂normalizedCompactHaarMeasure G) functionsEqual
  rw [normalizedCompactHaar_character_analysis_synthesis
      dimension ρ hρ unitaryρ dimension_pos pairwiseInequivalent
      first index,
    normalizedCompactHaar_character_analysis_synthesis
      dimension ρ hρ unitaryρ dimension_pos pairwiseInequivalent
      second index] at analysesEqual
  exact analysesEqual

/-- The finite central-character subspace is the exact range of character synthesis. -/
def finiteCharacterSubspace
    {G : Type uG} [Group G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ) :
    Submodule ℂ (G → ℂ) :=
  LinearMap.range (finiteCharacterSynthesis dimension ρ)

/-- Character synthesis identifies the coefficient family with its exact finite central-character
subspace. -/
noncomputable def finiteCharacterSynthesisEquiv
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (hρ : ∀ i, Continuous (ρ i))
    (unitaryρ : ∀ i g, star (ρ i g) * ρ i g = 1)
    [∀ i, Representation.IsIrreducible (matrixRepresentation (ρ i))]
    (dimension_pos : ∀ i, 0 < dimension i)
    (pairwiseInequivalent : ∀ i j, i ≠ j →
      IsEmpty (Representation.Equiv
        (matrixRepresentation (ρ j)) (matrixRepresentation (ρ i)))) :
    (ι → ℂ) ≃ₗ[ℂ] finiteCharacterSubspace dimension ρ :=
  LinearEquiv.ofInjective (finiteCharacterSynthesis dimension ρ)
    (finiteCharacterSynthesis_injective
      dimension ρ hρ unitaryρ dimension_pos pairwiseInequivalent)

/-- Every finite character range is finite dimensional, before irreducibility assumptions. -/
noncomputable instance finiteCharacterSubspace_finiteDimensional
    {G : Type uG} [Group G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ) :
    FiniteDimensional ℂ (finiteCharacterSubspace dimension ρ) :=
  Module.Finite.range (finiteCharacterSynthesis dimension ρ)

/-- A finite family of pairwise inequivalent irreducible unitary characters spans a subspace of
exact dimension equal to the cardinality of its index type. -/
theorem finrank_finiteCharacterSubspace
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [MeasurableSpace G] [BorelSpace G]
    {ι : Type uι} [Fintype ι] [DecidableEq ι]
    (dimension : ι → ℕ)
    (ρ : ∀ i, G →* Matrix (Fin (dimension i)) (Fin (dimension i)) ℂ)
    (hρ : ∀ i, Continuous (ρ i))
    (unitaryρ : ∀ i g, star (ρ i g) * ρ i g = 1)
    [∀ i, Representation.IsIrreducible (matrixRepresentation (ρ i))]
    (dimension_pos : ∀ i, 0 < dimension i)
    (pairwiseInequivalent : ∀ i j, i ≠ j →
      IsEmpty (Representation.Equiv
        (matrixRepresentation (ρ j)) (matrixRepresentation (ρ i)))) :
    Module.finrank ℂ (finiteCharacterSubspace dimension ρ) =
      Fintype.card ι := by
  rw [← (finiteCharacterSynthesisEquiv
    dimension ρ hρ unitaryρ dimension_pos pairwiseInequivalent).finrank_eq]
  simp

end

end Mathematics
end YangMills
