/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Mathematics.ObservationGeneratedMeasurableSpace
import YangMills.Mathematics.SimultaneousConjugacyQuotient

/-!
# Nonempty finite simultaneous-conjugacy observations

A finite random-holonomy observation must remember the joint class of a family of loops already
restricted to one fixed base point, under one common conjugation at that point. This file combines
the exact simultaneous quotient with dependent-observation sigma fields. Families are positive-arity
by construction, so an empty tuple cannot masquerade as a holonomy generator. A caller with loops
at different base points must partition them by base point and use a tuple of separate joint classes;
this API deliberately supplies no common-conjugator operation across such groups.

No fixed-base loop space, probability law, surface, or Yang--Mills model is constructed here.
-/

namespace YangMills.Mathematics

universe uBasedLoop uG uΩ

/-- A genuinely nonempty finite family, represented by `n + 1` indexed entries. -/
def NonemptyFiniteFamily (α : Type uBasedLoop) : Type uBasedLoop :=
  Σ n : ℕ, Fin (n + 1) → α

/-- The exact number of entries in a nonempty finite family. -/
def NonemptyFiniteFamily.card {α : Type uBasedLoop} (family : NonemptyFiniteFamily α) : ℕ :=
  family.1 + 1

/-- The first entry, proving that every represented family is genuinely nonempty. -/
def NonemptyFiniteFamily.first {α : Type uBasedLoop} (family : NonemptyFiniteFamily α) : α :=
  family.2 0

/-- The singleton family containing one exact entry. -/
def singletonNonemptyFiniteFamily {α : Type uBasedLoop} (entry : α) : NonemptyFiniteFamily α :=
  ⟨0, fun _ => entry⟩

/-- A nonempty finite family exists exactly when its entry carrier is nonempty. -/
theorem nonempty_nonemptyFiniteFamily_iff {α : Type uBasedLoop} :
    Nonempty (NonemptyFiniteFamily α) ↔ Nonempty α := by
  constructor
  · rintro ⟨family⟩
    exact ⟨family.first⟩
  · rintro ⟨entry⟩
    exact ⟨singletonNonemptyFiniteFamily entry⟩

section Observation

variable {BasedLoop : Type uBasedLoop} {G : Type uG} {Ω : Type uΩ}
    [Group G] [MeasurableSpace G]

/-- Exact joint class of the holonomies in one nonempty finite family from a single fixed-base loop
carrier. -/
def finiteSimultaneousConjugacyObservation
    (holonomy : BasedLoop → Ω → G) (family : NonemptyFiniteFamily BasedLoop) :
    Ω → SimultaneousConjugacyQuotient (Fin (family.1 + 1)) G :=
  fun sample => simultaneousConjugacyClass (fun index => holonomy (family.2 index) sample)

/-- The dependent target carrier for each finite family. -/
@[reducible] def finiteSimultaneousConjugacyObservationValue
    (family : NonemptyFiniteFamily BasedLoop) : Type (max uG 0) :=
  SimultaneousConjugacyQuotient (Fin (family.1 + 1)) G

/-- The exact sigma field generated by all nonempty finite simultaneous-conjugacy observations. -/
@[reducible] def finiteSimultaneousConjugacyGeneratedMeasurableSpace
    (holonomy : BasedLoop → Ω → G) : MeasurableSpace Ω :=
  observationGeneratedMeasurableSpace
    (finiteSimultaneousConjugacyObservationValue (G := G))
    (fun _ => inferInstance)
    (finiteSimultaneousConjugacyObservation holonomy)

/-- Every finite simultaneous class is measurable from the exact generated sigma field. -/
theorem finiteSimultaneousConjugacyObservation_measurable_generated
    (holonomy : BasedLoop → Ω → G) (family : NonemptyFiniteFamily BasedLoop) :
    @Measurable Ω (finiteSimultaneousConjugacyObservationValue (G := G) family)
      (finiteSimultaneousConjugacyGeneratedMeasurableSpace holonomy)
      inferInstance (finiteSimultaneousConjugacyObservation holonomy family) :=
  observation_measurable
    (finiteSimultaneousConjugacyObservationValue (G := G))
    (fun _ => inferInstance)
    (finiteSimultaneousConjugacyObservation holonomy) family

/-- If every one-loop holonomy is measurable on an ambient sample sigma field, then every exact
finite joint class is measurable there. -/
theorem finiteSimultaneousConjugacyObservation_measurable
    [MeasurableSpace Ω]
    (holonomy : BasedLoop → Ω → G) (holonomy_measurable : ∀ basedLoop, Measurable (holonomy basedLoop))
    (family : NonemptyFiniteFamily BasedLoop) :
    Measurable (finiteSimultaneousConjugacyObservation holonomy family) := by
  apply simultaneousConjugacyClass_measurable.comp
  apply measurable_pi_iff.mpr
  intro index
  exact holonomy_measurable (family.2 index)

/-- Consequently the generated finite-holonomy sigma field is contained in every ambient field on
which each exact one-loop holonomy is measurable. -/
theorem finiteSimultaneousConjugacyGeneratedMeasurableSpace_le
    [MeasurableSpace Ω]
    (holonomy : BasedLoop → Ω → G) (holonomy_measurable : ∀ basedLoop, Measurable (holonomy basedLoop)) :
    finiteSimultaneousConjugacyGeneratedMeasurableSpace holonomy ≤
      (inferInstance : MeasurableSpace Ω) := by
  apply observationGeneratedMeasurableSpace_le
  intro family
  exact measurable_iff_comap_le.mp
    (finiteSimultaneousConjugacyObservation_measurable holonomy holonomy_measurable family)

/-- Exact recognition of an ambient sample sigma field as the field generated by all nonempty finite
simultaneous-conjugacy observations. -/
theorem ambient_eq_finiteSimultaneousConjugacyGeneratedMeasurableSpace
    [MeasurableSpace Ω]
    (holonomy : BasedLoop → Ω → G) (holonomy_measurable : ∀ basedLoop, Measurable (holonomy basedLoop))
    (generated_covers : (inferInstance : MeasurableSpace Ω) ≤
      finiteSimultaneousConjugacyGeneratedMeasurableSpace holonomy) :
    (inferInstance : MeasurableSpace Ω) =
      finiteSimultaneousConjugacyGeneratedMeasurableSpace holonomy := by
  apply le_antisymm generated_covers
  exact finiteSimultaneousConjugacyGeneratedMeasurableSpace_le holonomy holonomy_measurable

omit [MeasurableSpace G] in
/-- Sample-dependent common conjugation leaves every exact finite-family observation unchanged. -/
theorem finiteSimultaneousConjugacyObservation_common_conjugation
    (holonomy : BasedLoop → Ω → G) (conjugator : Ω → G)
    (family : NonemptyFiniteFamily BasedLoop) (sample : Ω) :
    finiteSimultaneousConjugacyObservation
        (fun basedLoop samplePoint =>
          (conjugator samplePoint)⁻¹ * holonomy basedLoop samplePoint * conjugator samplePoint)
        family sample =
      finiteSimultaneousConjugacyObservation holonomy family sample :=
  simultaneousConjugacyClass_conjugate
    (fun index => holonomy (family.2 index) sample) (conjugator sample)

end Observation

end YangMills.Mathematics
