/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Mathematics.LieGroupAdjointBracket

/-!
# Hostile probes for adjoint bracket preservation
-/

namespace YangMills.Mathematics.LieGroupAdjointBracket.Probes

open scoped Manifold ContDiff

universe uE uH uG

noncomputable section

variable
    {E : Type uE} {H : Type uH}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [TopologicalSpace H]
    {I : ModelWithCorners ℝ E H}
    {G : Type uG} [Group G] [TopologicalSpace G] [ChartedSpace H G]
    [LieGroup I ∞ G] [LieGroup I (minSmoothness ℝ 3) G]
    [IsManifold I (minSmoothness ℝ 2) G]

omit [FiniteDimensional ℝ E] [LieGroup I (minSmoothness ℝ 3) G]
    [IsManifold I (minSmoothness ℝ 2) G] in
/-- Inner conjugation has the exact project carrier and inverse. -/
theorem exact_conjugation_diffeomorph
    (g x : G) :
    lieGroupConjugationDiffeomorph I g x = lieGroupConjugation g x ∧
      (lieGroupConjugationDiffeomorph I g).symm x = lieGroupConjugation g⁻¹ x :=
  ⟨rfl, rfl⟩

omit [FiniteDimensional ℝ E] [LieGroup I (minSmoothness ℝ 3) G]
    [IsManifold I (minSmoothness ℝ 2) G] in
/-- Conjugation pushes each left-invariant field to the field generated by the exact adjoint. -/
theorem exact_conjugation_pushforward
    (g : G) (X : GroupLieAlgebra I G) :
    Diffeomorph.pushforwardField (lieGroupConjugationDiffeomorph I g)
        (mulInvariantVectorField X) =
      mulInvariantVectorField (lieGroupAdjoint I g X) :=
  lieGroupConjugation_pushforward_mulInvariantVectorField I g X

/-- The derivative-defined adjoint preserves the intrinsic tangent Lie bracket. -/
theorem exact_adjoint_bracket
    (g : G) (X Y : GroupLieAlgebra I G) :
    lieGroupAdjoint I g ⁅X, Y⁆ =
      ⁅lieGroupAdjoint I g X, lieGroupAdjoint I g Y⁆ :=
  lieGroupAdjoint_lieBracket I g X Y

/-- A changed bracket under the same adjoint action is rejected. -/
theorem mismatched_adjoint_bracket_blocked
    (g : G) (X Y : GroupLieAlgebra I G)
    (wrong : lieGroupAdjoint I g ⁅X, Y⁆ ≠
      ⁅lieGroupAdjoint I g X, lieGroupAdjoint I g Y⁆) : False :=
  wrong (lieGroupAdjoint_lieBracket I g X Y)

end

end YangMills.Mathematics.LieGroupAdjointBracket.Probes
