/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import Mathlib.Analysis.Complex.Basic
import YangMills.Mathematics.LieGroupRightInvariantScalarLaplacian

/-!
# Right-invariant complex scalar Laplacian

Driver's compact-group heat-kernel and character formulas are complex-valued, while the earlier
pairing-normalized scalar Laplacian module deliberately constructed only the real-valued carrier.
This file supplies the parallel complex-valued carrier using the same Mathlib manifold derivative,
the same right-invariant vector fields, and an orthonormal basis for the same invariant pairing.

Basis independence remains explicit data rather than an inferred theorem. This file constructs no
Casimir eigenvalue, representation-theoretic bridge, heat equation, or heat kernel.
-/

namespace YangMills
namespace Mathematics

open scoped Manifold ContDiff BigOperators

noncomputable section

universe uE uG

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [ChartedSpace E G]
    [LieGroup (modelWithCornersSelf ℝ E) ∞ G]

/-- Smooth complex scalar function on the exact real Lie-group manifold. -/
structure SmoothLieGroupComplexFunction where
  toFun : G → ℂ
  contMDiff : ContMDiff (modelWithCornersSelf ℝ E)
    (modelWithCornersSelf ℝ ℂ) ∞ toFun

instance : CoeFun (SmoothLieGroupComplexFunction (E := E) (G := G)) (fun _ => G → ℂ) :=
  ⟨SmoothLieGroupComplexFunction.toFun⟩

namespace SmoothLieGroupComplexFunction

omit [Group G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
/-- Smooth complex scalar functions are equal when their underlying functions are equal. -/
@[ext]
theorem ext {f h : SmoothLieGroupComplexFunction (E := E) (G := G)}
    (toFun_eq : f.toFun = h.toFun) : f = h := by
  cases f
  cases h
  cases toFun_eq
  rfl

/-- Constant smooth complex scalar function. -/
def const (c : ℂ) : SmoothLieGroupComplexFunction (E := E) (G := G) where
  toFun := fun _ => c
  contMDiff := contMDiff_const

omit [Group G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem const_apply (c : ℂ) (g : G) :
    (const (E := E) (G := G) c) g = c :=
  rfl

end SmoothLieGroupComplexFunction

/-- Derivative of a complex scalar function along the right-invariant field generated by `Y`. -/
def rightInvariantComplexDerivative
    (f : G → ℂ)
    (Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) : ℂ :=
  mfderiv (modelWithCornersSelf ℝ E) (modelWithCornersSelf ℝ ℂ) f g
    (mulRightInvariantVectorField (modelWithCornersSelf ℝ E) Y g)

/-- Iterated complex right-invariant derivative, with `X` acting after `Y`. -/
def rightInvariantComplexSecondDerivative
    (f : G → ℂ)
    (X Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) : ℂ :=
  rightInvariantComplexDerivative
    (fun q => rightInvariantComplexDerivative f Y q) X g

/-- Driver's complex-valued basis-sum Laplacian candidate for one exact finite basis. -/
def rightInvariantComplexLaplacianInBasis
    {rank : ℕ}
    (basis : Module.Basis (Fin rank) ℝ
      (GroupLieAlgebra (modelWithCornersSelf ℝ E) G))
    (f : G → ℂ) (g : G) : ℂ :=
  ∑ a, rightInvariantComplexSecondDerivative f (basis a) (basis a) g

omit [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem rightInvariantComplexDerivative_const
    (c : ℂ) (Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) :
    rightInvariantComplexDerivative (fun _ : G => c) Y g = 0 := by
  rw [rightInvariantComplexDerivative, mfderiv_const]
  rfl

omit [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem rightInvariantComplexSecondDerivative_const
    (c : ℂ) (X Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) :
    rightInvariantComplexSecondDerivative (fun _ : G => c) X Y g = 0 := by
  simp [rightInvariantComplexSecondDerivative]

omit [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem rightInvariantComplexLaplacianInBasis_const
    {rank : ℕ}
    (basis : Module.Basis (Fin rank) ℝ
      (GroupLieAlgebra (modelWithCornersSelf ℝ E) G))
    (c : ℂ) (g : G) :
    rightInvariantComplexLaplacianInBasis basis (fun _ : G => c) g = 0 := by
  simp [rightInvariantComplexLaplacianInBasis]

/-- Basis-independent complex right-invariant Laplacian normalized by the exact invariant pairing.
The selected and comparison bases are orthonormal for that same pairing. -/
structure RightInvariantPairingComplexLaplacianData
    (inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)) where
  orthonormalBasis : Geometry.InvariantPairingOrthonormalBasisData inner
  basis_independent :
    ∀ (other : Geometry.InvariantPairingOrthonormalBasisData inner)
      (f : SmoothLieGroupComplexFunction (E := E) (G := G)) (g : G),
      rightInvariantComplexLaplacianInBasis other.basis f g =
        rightInvariantComplexLaplacianInBasis orthonormalBasis.basis f g

namespace RightInvariantPairingComplexLaplacianData

/-- Exact selected-basis presentation of the complex pairing Laplacian. -/
def laplacian
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    (data : RightInvariantPairingComplexLaplacianData inner)
    (f : SmoothLieGroupComplexFunction (E := E) (G := G)) (g : G) : ℂ :=
  rightInvariantComplexLaplacianInBasis data.orthonormalBasis.basis f g

/-- Every other orthonormal basis for the same pairing computes the same complex Laplacian. -/
theorem laplacian_eq_inBasis
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    (data : RightInvariantPairingComplexLaplacianData inner)
    (other : Geometry.InvariantPairingOrthonormalBasisData inner)
    (f : SmoothLieGroupComplexFunction (E := E) (G := G)) (g : G) :
    data.laplacian f g = rightInvariantComplexLaplacianInBasis other.basis f g := by
  rw [laplacian]
  exact (data.basis_independent other f g).symm

/-- The exact complex pairing Laplacian annihilates constants. -/
@[simp]
theorem laplacian_const
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    (data : RightInvariantPairingComplexLaplacianData inner) (c : ℂ) (g : G) :
    data.laplacian (SmoothLieGroupComplexFunction.const c) g = 0 := by
  rw [laplacian]
  change rightInvariantComplexLaplacianInBasis data.orthonormalBasis.basis
    (fun _ : G => c) g = 0
  exact rightInvariantComplexLaplacianInBasis_const _ c g

end RightInvariantPairingComplexLaplacianData

end

end Mathematics
end YangMills
