/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Mathematics.LieGroupAdjointBracket
import YangMills.Mathematics.LieGroupAdjointRegularity

/-!
# Smooth right-invariant fields and inverse-adjoint orbits

The right-invariant field generated at the identity is constructed, proved invariant under right
translation, and proved smooth. In left trivialization its coefficient is exactly `Ad(g⁻¹)Y`, whose
model-coordinate orbit is also proved smooth. These are prerequisites for, but do not assert, the
still-missing infinitesimal formula
`d(Ad(·⁻¹)Y)₁(X) = -[X,Y]`.
-/

namespace YangMills.Mathematics

open Function Bundle
open scoped Manifold ContDiff

universe uE uH uG

noncomputable section

variable
    {E : Type uE} {H : Type uH}
    [NormedAddCommGroup E] [NormedSpace ℝ E] [TopologicalSpace H]
    (I : ModelWithCorners ℝ E H)
    {G : Type uG} [Group G] [TopologicalSpace G] [ChartedSpace H G]
    [LieGroup I ∞ G]

/-- The right-invariant vector field generated by an identity tangent vector. -/
def mulRightInvariantVectorField (Y : GroupLieAlgebra I G) (g : G) : TangentSpace I g :=
  mfderiv I I (fun h : G => h * g) 1 Y

/-- The field generated by `Y` is invariant under every right translation. -/
theorem mfderiv_mul_right_mulRightInvariantVectorField
    (Y : GroupLieAlgebra I G) (g a : G) :
    mfderiv I I (fun q : G => q * a) g (mulRightInvariantVectorField I Y g) =
      mulRightInvariantVectorField I Y (g * a) := by
  change mfderiv I I (fun q : G => q * a) g
      (mfderiv I I (fun h : G => h * g) 1 Y) =
    mfderiv I I (fun h : G => h * (g * a)) 1 Y
  have hcomp := mfderiv_comp (I := I) (I' := I) (I'' := I)
    (f := fun h : G => h * g) (g := fun q : G => q * a) (1 : G)
    ((contMDiff_mul_right (I := I) (n := ∞) (a := a)).mdifferentiableAt (by simp))
    ((contMDiff_mul_right (I := I) (n := ∞) (a := g)).mdifferentiableAt (by simp))
  rw [one_mul] at hcomp
  have happ := congrArg (fun L => L Y) hcomp
  change mfderiv I I ((fun q : G => q * a) ∘ (fun h : G => h * g)) 1 Y =
    mfderiv I I (fun q : G => q * a) g
      (mfderiv I I (fun h : G => h * g) 1 Y) at happ
  rw [show ((fun q : G => q * a) ∘ (fun h : G => h * g)) =
      (fun h : G => h * (g * a)) by funext h; simp [mul_assoc]] at happ
  exact happ.symm

set_option backward.isDefEq.respectTransparency false in
/-- A right-invariant field, left-trivialized at `g`, has coefficient `Ad(g⁻¹)Y`. -/
theorem mulRightInvariantVectorField_eq_mulInvariant_adjoint_inv
    (Y : GroupLieAlgebra I G) (g : G) :
    mulRightInvariantVectorField I Y g =
      mulInvariantVectorField (lieGroupAdjoint I g⁻¹ Y) g := by
  have hfun : (fun h : G => h * g) =
      (fun x : G => g * x) ∘ lieGroupConjugation g⁻¹ := by
    funext h
    simp only [Function.comp_apply, lieGroupConjugation]
    group
  have hsmoothLeft : ContMDiff I I ∞ (fun x : G => g * x) :=
    contMDiff_mul_left
  have hchain := mfderiv_comp (I := I) (I' := I) (I'' := I)
    (f := lieGroupConjugation g⁻¹) (g := fun x : G => g * x) (1 : G)
    (hsmoothLeft.mdifferentiableAt (by simp))
    ((lieGroupConjugation_smooth I g⁻¹).mdifferentiableAt (by simp))
  have hone : lieGroupConjugation g⁻¹ (1 : G) = 1 := by
    simp [lieGroupConjugation]
  rw [hone] at hchain
  have happ := congrArg (fun L => L Y) hchain
  rw [← hfun] at happ
  change mfderiv I I (fun h : G => h * g) 1 Y =
    mfderiv I I (fun x : G => g * x) 1
      (mfderiv I I (lieGroupConjugation g⁻¹) 1 Y) at happ
  exact happ

set_option backward.defeqAttrib.useBackward true in
/-- The right-invariant vector field is smooth. This is the right-factor counterpart of Mathlib's
`contMDiff_mulInvariantVectorField`. -/
theorem contMDiff_mulRightInvariantVectorField (Y : GroupLieAlgebra I G) :
    ContMDiff I (I.tangent) ∞
      (fun g : G =>
        (⟨g, mulRightInvariantVectorField I Y g⟩ : TangentBundle I G)) := by
  let fY : G → TangentBundle I G := fun _ => ⟨(1 : G), Y⟩
  have hfY : ContMDiff I (I.tangent) ∞ fY := contMDiff_const
  let fg : G → TangentBundle I G := fun g => ⟨g, 0⟩
  have hfg : ContMDiff I (I.tangent) ∞ fg :=
    contMDiff_zeroSection ℝ (TangentSpace I)
  let F₁ : G → TangentBundle I G × TangentBundle I G := fun g => (fY g, fg g)
  have hF₁ : ContMDiff I ((I.tangent).prod (I.tangent)) ∞ F₁ := hfY.prodMk hfg
  let F₂ : TangentBundle I G × TangentBundle I G → TangentBundle (I.prod I) (G × G) :=
    (equivTangentBundleProd I G I G).symm
  have hF₂ : ContMDiff ((I.tangent).prod (I.tangent)) ((I.prod I).tangent) ∞ F₂ :=
    contMDiff_equivTangentBundleProd_symm
  let multiplication : G × G → G := fun z => z.1 * z.2
  let F₃ : TangentBundle (I.prod I) (G × G) → TangentBundle I G :=
    tangentMap (I.prod I) I multiplication
  have hF₃ : ContMDiff ((I.prod I).tangent) (I.tangent) ∞ F₃ := by
    apply ContMDiff.contMDiff_tangentMap (contMDiff_mul I ∞)
    simp
  convert! ((hF₃.comp hF₂).comp hF₁) with g
  · simp [F₁, F₂, F₃, fY, fg, multiplication]
  · simp only [Function.comp_apply, F₃, F₂, F₁, fY, fg, tangentMap]
    rw [mfderiv_prod_eq_add_apply
      ((contMDiff_mul I ∞).mdifferentiableAt (by simp))]
    simp +instances [mulRightInvariantVectorField]

/-- The exact target whose proof would identify the infinitesimal inverse-adjoint action. -/
def inverseAdjointOrbit (Y : GroupLieAlgebra I G) : G → GroupLieAlgebra I G :=
  fun g => lieGroupAdjoint I g⁻¹ Y

/-- Smoothness needed to differentiate the inverse-adjoint orbit is already available. -/
theorem inverseAdjointOrbit_contMDiff (Y : GroupLieAlgebra I G) :
    ContMDiff I 𝓘(ℝ, E) ∞
      (fun g : G => groupLieAlgebraModelEquiv I (inverseAdjointOrbit I Y g)) := by
  have hpair : ContMDiff I (I.prod 𝓘(ℝ, E)) ∞
      (fun g : G => (g, groupLieAlgebraModelEquiv I Y)) :=
    contMDiff_id.prodMk contMDiff_const
  exact (lieGroupAdjointCoordinates_inverseAction_contMDiff (I := I) (G := G)).comp hpair


end

end YangMills.Mathematics
