/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Geometry.InvariantPairingOrthonormalBasis
import YangMills.Mathematics.LieGroupRightInvariantField
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

/-!
# Right-invariant scalar derivatives and pairing-normalized Laplacian

Driver Definition 4.5 differentiates a scalar function along the right-invariant field generated by
an identity tangent vector. Definition 4.7 defines the group Laplacian as the sum of the corresponding
second derivatives over an orthonormal Lie-algebra basis, and Remark 4.8 records basis independence.

This module constructs the exact first/second derivative carriers from Mathlib's manifold
derivative and packages basis independence as an explicit acceptance requirement tied to one
unchanged invariant pairing. It constructs neither an invariant Riemannian metric nor a heat kernel.
-/

namespace YangMills.Mathematics

open scoped Manifold ContDiff BigOperators

universe uE uG

noncomputable section

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [ChartedSpace E G]
    [LieGroup (modelWithCornersSelf ℝ E) ∞ G]

/-- Smooth real scalar function on the exact Lie-group manifold. -/
structure SmoothLieGroupScalarFunction where
  toFun : G → ℝ
  contMDiff : ContMDiff (modelWithCornersSelf ℝ E) 𝓘(ℝ, ℝ) ∞ toFun

instance : CoeFun (SmoothLieGroupScalarFunction (E := E) (G := G)) (fun _ => G → ℝ) :=
  ⟨SmoothLieGroupScalarFunction.toFun⟩

namespace SmoothLieGroupScalarFunction

/-- Constant smooth scalar function. -/
def const (c : ℝ) : SmoothLieGroupScalarFunction (E := E) (G := G) where
  toFun := fun _ => c
  contMDiff := contMDiff_const

omit [Group G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem const_apply (c : ℝ) (g : G) :
    (const (E := E) (G := G) c) g = c :=
  rfl

end SmoothLieGroupScalarFunction

/-- Derivative of a scalar function along the exact right-invariant field generated by `Y`. -/
def rightInvariantScalarDerivative
    (f : G → ℝ)
    (Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) : ℝ :=
  mfderiv (modelWithCornersSelf ℝ E) 𝓘(ℝ, ℝ) f g
    (mulRightInvariantVectorField (modelWithCornersSelf ℝ E) Y g)

/-- Iterated right-invariant derivative, with `X` acting after `Y`. -/
def rightInvariantScalarSecondDerivative
    (f : G → ℝ)
    (X Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) : ℝ :=
  rightInvariantScalarDerivative
    (fun q => rightInvariantScalarDerivative f Y q) X g

/-- Driver's basis-sum Laplacian candidate for one exact finite basis. -/
def rightInvariantScalarLaplacianInBasis
    {rank : ℕ}
    (basis : Module.Basis (Fin rank) ℝ
      (GroupLieAlgebra (modelWithCornersSelf ℝ E) G))
    (f : G → ℝ) (g : G) : ℝ :=
  ∑ a, rightInvariantScalarSecondDerivative f (basis a) (basis a) g

omit [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem rightInvariantScalarDerivative_const
    (c : ℝ) (Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) :
    rightInvariantScalarDerivative (fun _ : G => c) Y g = 0 := by
  rw [rightInvariantScalarDerivative, mfderiv_const]
  rfl

omit [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem rightInvariantScalarSecondDerivative_const
    (c : ℝ) (X Y : GroupLieAlgebra (modelWithCornersSelf ℝ E) G) (g : G) :
    rightInvariantScalarSecondDerivative (fun _ : G => c) X Y g = 0 := by
  simp [rightInvariantScalarSecondDerivative]

omit [LieGroup (modelWithCornersSelf ℝ E) ∞ G] in
@[simp]
theorem rightInvariantScalarLaplacianInBasis_const
    {rank : ℕ}
    (basis : Module.Basis (Fin rank) ℝ
      (GroupLieAlgebra (modelWithCornersSelf ℝ E) G))
    (c : ℝ) (g : G) :
    rightInvariantScalarLaplacianInBasis basis (fun _ : G => c) g = 0 := by
  simp [rightInvariantScalarLaplacianInBasis]

/-- Basis-independent right-invariant Laplacian normalized by one exact invariant pairing.

A selected nonempty orthonormal basis makes the operator concrete; the final field requires every
other basis orthonormal for the same pairing to compute the same scalar. -/
structure RightInvariantPairingLaplacianData
    (inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)) where
  orthonormalBasis : Geometry.InvariantPairingOrthonormalBasisData inner
  basis_independent :
    ∀ (other : Geometry.InvariantPairingOrthonormalBasisData inner)
      (f : SmoothLieGroupScalarFunction (E := E) (G := G)) (g : G),
      rightInvariantScalarLaplacianInBasis other.basis f g =
        rightInvariantScalarLaplacianInBasis orthonormalBasis.basis f g

namespace RightInvariantPairingLaplacianData

/-- Exact selected-basis presentation of the right-invariant pairing Laplacian. -/
def laplacian
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    (data : RightInvariantPairingLaplacianData inner)
    (f : SmoothLieGroupScalarFunction (E := E) (G := G)) (g : G) : ℝ :=
  rightInvariantScalarLaplacianInBasis data.orthonormalBasis.basis f g

/-- Every other exact orthonormal basis computes the same selected Laplacian. -/
theorem laplacian_eq_inBasis
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    (data : RightInvariantPairingLaplacianData inner)
    (other : Geometry.InvariantPairingOrthonormalBasisData inner)
    (f : SmoothLieGroupScalarFunction (E := E) (G := G)) (g : G) :
    data.laplacian f g = rightInvariantScalarLaplacianInBasis other.basis f g := by
  rw [laplacian]
  exact (data.basis_independent other f g).symm

/-- The exact right-invariant pairing Laplacian annihilates constants. -/
@[simp]
theorem laplacian_const
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    (data : RightInvariantPairingLaplacianData inner) (c : ℝ) (g : G) :
    data.laplacian (SmoothLieGroupScalarFunction.const c) g = 0 := by
  rw [laplacian]
  change rightInvariantScalarLaplacianInBasis data.orthonormalBasis.basis
    (fun _ : G => c) g = 0
  exact rightInvariantScalarLaplacianInBasis_const _ c g

end RightInvariantPairingLaplacianData

end

end YangMills.Mathematics
