/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import Mathlib.MeasureTheory.MeasurableSpace.Basic

/-!
# Measurable spaces generated by a dependent family of observations

This file packages the exact sigma field generated by a possibly dependent family of measurable
observations. It is reusable for random holonomy: an observation index may encode a finite loop
family, while its value carrier may be that family's simultaneous-conjugacy quotient.

No probability law or Yang--Mills object is constructed here.
-/

namespace YangMills.Mathematics

universe uΩ uObservation uValue

/-- The smallest measurable space on `Ω` making every supplied dependent observation measurable.
The target measurable spaces are explicit data, so distinct observations may have distinct value
carriers without installing global typeclass instances. -/
@[reducible] def observationGeneratedMeasurableSpace
    {Ω : Type uΩ} {Observation : Type uObservation}
    (Value : Observation → Type uValue)
    (target : ∀ observation, MeasurableSpace (Value observation))
    (observe : ∀ observation, Ω → Value observation) : MeasurableSpace Ω :=
  ⨆ observation, MeasurableSpace.comap (observe observation) (target observation)

/-- Every generator comap is contained in the generated measurable space. -/
theorem observation_comap_le_generated
    {Ω : Type uΩ} {Observation : Type uObservation}
    (Value : Observation → Type uValue)
    (target : ∀ observation, MeasurableSpace (Value observation))
    (observe : ∀ observation, Ω → Value observation)
    (observation : Observation) :
    MeasurableSpace.comap (observe observation) (target observation) ≤
      observationGeneratedMeasurableSpace Value target observe :=
  le_iSup (fun index => MeasurableSpace.comap (observe index) (target index)) observation

/-- Every supplied observation is measurable from the generated measurable space to its exact
target measurable space. -/
theorem observation_measurable
    {Ω : Type uΩ} {Observation : Type uObservation}
    (Value : Observation → Type uValue)
    (target : ∀ observation, MeasurableSpace (Value observation))
    (observe : ∀ observation, Ω → Value observation)
    (observation : Observation) :
    @Measurable Ω (Value observation)
      (observationGeneratedMeasurableSpace Value target observe)
      (target observation) (observe observation) :=
  measurable_iff_comap_le.mpr
    (observation_comap_le_generated Value target observe observation)

/-- Minimality: any measurable space containing every observation comap contains the generated
measurable space. -/
theorem observationGeneratedMeasurableSpace_le
    {Ω : Type uΩ} {Observation : Type uObservation}
    (Value : Observation → Type uValue)
    (target : ∀ observation, MeasurableSpace (Value observation))
    (observe : ∀ observation, Ω → Value observation)
    (ambient : MeasurableSpace Ω)
    (each : ∀ observation,
      MeasurableSpace.comap (observe observation) (target observation) ≤ ambient) :
    observationGeneratedMeasurableSpace Value target observe ≤ ambient := by
  apply iSup_le
  exact each

/-- Exact recognition principle for an ambient measurable space generated by the observations. -/
theorem ambient_eq_observationGeneratedMeasurableSpace
    {Ω : Type uΩ} {Observation : Type uObservation}
    (Value : Observation → Type uValue)
    (target : ∀ observation, MeasurableSpace (Value observation))
    (observe : ∀ observation, Ω → Value observation)
    (ambient : MeasurableSpace Ω)
    (observations_measurable : ∀ observation,
      MeasurableSpace.comap (observe observation) (target observation) ≤ ambient)
    (generated_covers : ambient ≤ observationGeneratedMeasurableSpace Value target observe) :
    ambient = observationGeneratedMeasurableSpace Value target observe := by
  apply le_antisymm generated_covers
  exact observationGeneratedMeasurableSpace_le Value target observe ambient observations_measurable

/-- Reindexing observations along a surjection does not alter the generated measurable space. -/
theorem observationGeneratedMeasurableSpace_comp_surjective
    {Ω : Type uΩ} {Observation : Type uObservation} {Observation' : Type*}
    (Value : Observation → Type uValue)
    (target : ∀ observation, MeasurableSpace (Value observation))
    (observe : ∀ observation, Ω → Value observation)
    (index : Observation' → Observation) (surjective : Function.Surjective index) :
    observationGeneratedMeasurableSpace (fun observation' => Value (index observation'))
        (fun observation' => target (index observation'))
        (fun observation' => observe (index observation')) =
      observationGeneratedMeasurableSpace Value target observe := by
  apply le_antisymm
  · apply observationGeneratedMeasurableSpace_le
    intro observation'
    exact observation_comap_le_generated Value target observe (index observation')
  · apply observationGeneratedMeasurableSpace_le
    intro observation
    obtain ⟨observation', rfl⟩ := surjective observation
    exact observation_comap_le_generated
      (fun index' => Value (index index'))
      (fun index' => target (index index'))
      (fun index' => observe (index index')) observation'

end YangMills.Mathematics
