/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Mathematics.FiniteSimultaneousConjugacyObservation

/-!
# Finite joint-holonomy fields partitioned by base point

One common conjugator is valid only for loops at one fixed base point. This file generates a sample
sigma field from every positive-arity finite family inside each dependent fixed-base loop carrier.
Families at different base points remain separate observations; no quotient permits one common
conjugator across them.
-/

namespace YangMills.Mathematics

universe uBase uLoop uG uΩ

/-- One selected base point together with a nonempty finite family of loops at that exact base. -/
def PartitionedFixedBaseFiniteFamily
    {Base : Type uBase} (LoopAt : Base → Type uLoop) : Type (max uBase uLoop) :=
  Σ base : Base, NonemptyFiniteFamily (LoopAt base)

section Observation

variable {Base : Type uBase} {LoopAt : Base → Type uLoop}
    {G : Type uG} {Ω : Type uΩ} [Group G] [MeasurableSpace G]

/-- Exact joint conjugacy class for one finite family at one selected base point. -/
def partitionedFixedBaseConjugacyObservation
    (holonomy : ∀ base, LoopAt base → Ω → G)
    (family : PartitionedFixedBaseFiniteFamily LoopAt) :
    Ω → SimultaneousConjugacyQuotient (Fin (family.2.1 + 1)) G :=
  finiteSimultaneousConjugacyObservation (holonomy family.1) family.2

/-- Dependent target of each selected fixed-base finite family. -/
@[reducible] def partitionedFixedBaseConjugacyObservationValue
    (family : PartitionedFixedBaseFiniteFamily LoopAt) : Type (max uG 0) :=
  SimultaneousConjugacyQuotient (Fin (family.2.1 + 1)) G

/-- Smallest sigma field generated by every positive-arity joint class within every base-point
partition. -/
@[reducible] def partitionedFixedBaseConjugacyGeneratedMeasurableSpace
    (holonomy : ∀ base, LoopAt base → Ω → G) : MeasurableSpace Ω :=
  observationGeneratedMeasurableSpace
    (partitionedFixedBaseConjugacyObservationValue (G := G))
    (fun _ => inferInstance)
    (partitionedFixedBaseConjugacyObservation holonomy)

/-- Every partitioned fixed-base observation is measurable on the exact generated field. -/
theorem partitionedFixedBaseConjugacyObservation_measurable_generated
    (holonomy : ∀ base, LoopAt base → Ω → G)
    (family : PartitionedFixedBaseFiniteFamily LoopAt) :
    @Measurable Ω (partitionedFixedBaseConjugacyObservationValue (G := G) family)
      (partitionedFixedBaseConjugacyGeneratedMeasurableSpace holonomy)
      inferInstance (partitionedFixedBaseConjugacyObservation holonomy family) :=
  observation_measurable
    (partitionedFixedBaseConjugacyObservationValue (G := G))
    (fun _ => inferInstance)
    (partitionedFixedBaseConjugacyObservation holonomy) family

/-- Measurable one-loop holonomies make every exact fixed-base family measurable in an ambient
sample sigma field. -/
theorem partitionedFixedBaseConjugacyObservation_measurable
    [MeasurableSpace Ω] (holonomy : ∀ base, LoopAt base → Ω → G)
    (holonomy_measurable : ∀ base loop, Measurable (holonomy base loop))
    (family : PartitionedFixedBaseFiniteFamily LoopAt) :
    Measurable (partitionedFixedBaseConjugacyObservation holonomy family) :=
  finiteSimultaneousConjugacyObservation_measurable
    (holonomy family.1) (holonomy_measurable family.1) family.2

/-- The generated partitioned field lies below every ambient field making all exact one-loop
holonomies measurable. -/
theorem partitionedFixedBaseConjugacyGeneratedMeasurableSpace_le
    [MeasurableSpace Ω] (holonomy : ∀ base, LoopAt base → Ω → G)
    (holonomy_measurable : ∀ base loop, Measurable (holonomy base loop)) :
    partitionedFixedBaseConjugacyGeneratedMeasurableSpace holonomy ≤
      (inferInstance : MeasurableSpace Ω) := by
  apply observationGeneratedMeasurableSpace_le
  intro family
  exact measurable_iff_comap_le.mp
    (partitionedFixedBaseConjugacyObservation_measurable holonomy holonomy_measurable family)

/-- Ambient equality requires the explicit converse coverage inclusion. -/
theorem ambient_eq_partitionedFixedBaseConjugacyGeneratedMeasurableSpace
    [MeasurableSpace Ω] (holonomy : ∀ base, LoopAt base → Ω → G)
    (holonomy_measurable : ∀ base loop, Measurable (holonomy base loop))
    (generated_covers : (inferInstance : MeasurableSpace Ω) ≤
      partitionedFixedBaseConjugacyGeneratedMeasurableSpace holonomy) :
    (inferInstance : MeasurableSpace Ω) =
      partitionedFixedBaseConjugacyGeneratedMeasurableSpace holonomy := by
  apply le_antisymm generated_covers
  exact partitionedFixedBaseConjugacyGeneratedMeasurableSpace_le holonomy holonomy_measurable

omit [MeasurableSpace G] in
/-- Independent base-point conjugators leave every observation unchanged, while no single
conjugator is formed across different base points. -/
theorem partitionedFixedBaseConjugacyObservation_common_conjugation
    (holonomy : ∀ base, LoopAt base → Ω → G)
    (conjugator : Base → Ω → G)
    (family : PartitionedFixedBaseFiniteFamily LoopAt) (sample : Ω) :
    partitionedFixedBaseConjugacyObservation
        (fun base loop samplePoint =>
          (conjugator base samplePoint)⁻¹ * holonomy base loop samplePoint *
            conjugator base samplePoint)
        family sample =
      partitionedFixedBaseConjugacyObservation holonomy family sample :=
  finiteSimultaneousConjugacyObservation_common_conjugation
    (holonomy family.1) (conjugator family.1) family.2 sample

end Observation

end YangMills.Mathematics
