/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Constructions
import Mathlib.Topology.Constructions

/-!
# Open sets are measurable in measurable sums

Mathlib equips a sum with the final measurable structure generated by its two injections and with
the disjoint-union topology. If open sets are measurable on both summands, the same is true on the
sum. This small general-purpose instance is useful when applying continuity-to-measurability to a
map whose domain is a disjoint union.
-/

namespace YangMills.Mathematics

universe uα uβ

/-- The standard measurable sum has measurable open sets whenever both summands do. -/
instance sumOpensMeasurableSpace
    {α : Type uα} {β : Type uβ}
    [TopologicalSpace α] [MeasurableSpace α] [OpensMeasurableSpace α]
    [TopologicalSpace β] [MeasurableSpace β] [OpensMeasurableSpace β] :
    OpensMeasurableSpace (α ⊕ β) where
  borel_le := MeasurableSpace.generateFrom_le fun set isOpenSet => by
    rw [measurableSet_sum_iff]
    change IsOpen set at isOpenSet
    rw [isOpen_sum_iff] at isOpenSet
    exact ⟨isOpenSet.1.measurableSet, isOpenSet.2.measurableSet⟩

end YangMills.Mathematics
