/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Dimensions.TwoDimensionalSelectedLoopBrownianRealization
import YangMills.Dimensions.TwoDimensionalSelectedLoopSpectralHeatKernelBridge

/-!
# Spectral Brownian and generated-operator coherence

Sengupta and Driver identify the area-indexed heat density both as the law of group Brownian
increments and as the kernel of the semigroup generated by `Δ / 2`. The existing Brownian interface
records continuous paths and independent stationary right increments, while the existing
operator interface records the generated semigroup and Driver's kernel formula.

`TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData` forces both interfaces to use the
exact heat core constructed from one spectral density bridge. It derives the Brownian increment and
marginal laws with the spectral `ENNReal` density and exposes the unchanged generator formula.

This is still not a construction of Brownian motion. In particular, no conditional-expectation or
Markov transition theorem is inferred merely from the marginal/increment law; that stronger
stochastic operator identification remains future proof debt.
-/

namespace YangMills
namespace Dimensions

open MeasureTheory ProbabilityTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection uΩ

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [SecondCountableTopology G]
    [MeasurableSpace G] [BorelSpace G] [MeasurableMul₂ G] [MeasurableInv G]
    [ChartedSpace E G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {Ω : Type uΩ} [MeasurableSpace Ω]
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}

/-- One exact spectral heat core shared by Driver's generated operator and a supplied Brownian
realization on `Ω`. -/
structure TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData where
  spectralHeatKernel : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
    (law := law) (inner := inner) (realLaplacian := realLaplacian)
    (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData)
  brownian : TwoDimensionalSelectedLoopBrownianRealizationData
    inner law spectralHeatKernel.convolutionSemigroup realLaplacian
      spectralHeatKernel.heatEquationCore Ω

namespace TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Every positive stationary right increment has exactly the conditional spectral `ENNReal`
density, not merely an unrelated selected-loop density. -/
theorem stationary_increment_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (ht : 0 < t) :
    Measure.map (fun samplePoint =>
      (bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint) bridge.brownian.probabilityMeasure =
      (normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) := by
  rw [bridge.brownian.stationary_increment_law s t ht]
  congr 1
  funext g
  exact bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.selectedAreaDensity_eq
    (t : ℝ) (by exact_mod_cast ht) g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- The positive-time Brownian marginal has exactly the spectral density. -/
theorem marginal_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : NNReal) (ht : 0 < t) :
    Measure.map (bridge.brownian.process t) bridge.brownian.probabilityMeasure =
      (normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) := by
  rw [bridge.brownian.marginal_law t ht]
  congr 1
  funext g
  exact bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.selectedAreaDensity_eq
    (t : ℝ) (by exact_mod_cast ht) g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- The operator attached to the same spectral heat core is generated by the unchanged real
pairing Laplacian with Driver's factor `1/2`. -/
theorem generated_operator_hasDerivAt
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    HasDerivAt (fun s => bridge.spectralHeatKernel.kernelOperator.heatOperator s f g)
      ((1 / 2 : ℝ) * realLaplacian.laplacian
        (bridge.spectralHeatKernel.kernelOperator.positiveTimeSmooth t ht f) g) t :=
  bridge.spectralHeatKernel.kernelOperator.heatOperator_hasDerivAt t ht f g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Driver's generated operator uses the exact real part of the same spectral series governing the
Brownian increment laws. -/
theorem generated_operator_eq_spectralKernelIntegral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
        ∂normalizedCompactHaarMeasure G := by
  simpa only [TwoDimensionalSelectedLoopSpectralHeatEquationBridgeData.toHeatEquationCoreData]
    using bridge.spectralHeatKernel.kernelOperator.heatOperator_eq_kernelIntegral t ht f g

end TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData

end

end Dimensions
end YangMills
