/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Dimensions.TwoDimensionalSelectedLoopBrownianRealization
import YangMills.Dimensions.TwoDimensionalSelectedLoopSpectralHeatKernelBridge

/-!
# Spectral Brownian and generated-operator coherence

Sengupta and Driver identify the area-indexed heat density both as the law of group Brownian
increments and as the kernel of the semigroup generated by `Δ / 2`. The existing Brownian interface
records continuous paths and independent stationary right increments, while the existing
operator interface records the generated semigroup and Driver's kernel formula.

`TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData` forces both interfaces to use the
exact heat core constructed from one spectral density bridge. It derives the Brownian increment and
marginal laws with the spectral `ENNReal` density and exposes the unchanged generator formula.

This is still not a construction of Brownian motion. In particular, no conditional-expectation or
Markov transition theorem is inferred merely from the marginal/increment law; that stronger
stochastic operator identification remains future proof debt.
-/

namespace YangMills
namespace Dimensions

open MeasureTheory ProbabilityTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection uΩ

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [SecondCountableTopology G]
    [MeasurableSpace G] [BorelSpace G] [MeasurableMul₂ G] [MeasurableInv G]
    [ChartedSpace E G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {Ω : Type uΩ} [MeasurableSpace Ω]
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}

/-- One exact spectral heat core shared by Driver's generated operator and a supplied Brownian
realization on `Ω`. -/
structure TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData where
  spectralHeatKernel : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
    (law := law) (inner := inner) (realLaplacian := realLaplacian)
    (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData)
  brownian : TwoDimensionalSelectedLoopBrownianRealizationData
    inner law spectralHeatKernel.convolutionSemigroup realLaplacian
      spectralHeatKernel.heatEquationCore Ω

namespace TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Every positive stationary right increment has exactly the conditional spectral `ENNReal`
density, not merely an unrelated selected-loop density. -/
theorem stationary_increment_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (ht : 0 < t) :
    Measure.map (fun samplePoint =>
      (bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint) bridge.brownian.probabilityMeasure =
      (normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) := by
  rw [bridge.brownian.stationary_increment_law s t ht]
  congr 1
  funext g
  exact bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.selectedAreaDensity_eq
    (t : ℝ) (by exact_mod_cast ht) g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- The positive-time Brownian marginal has exactly the spectral density. -/
theorem marginal_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : NNReal) (ht : 0 < t) :
    Measure.map (bridge.brownian.process t) bridge.brownian.probabilityMeasure =
      (normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) := by
  rw [bridge.brownian.marginal_law t ht]
  congr 1
  funext g
  exact bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.selectedAreaDensity_eq
    (t : ℝ) (by exact_mod_cast ht) g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Integrating a continuous real test function against the spectral `ENNReal` density measure is
exactly weighted integration against its strictly positive real representative. -/
theorem integral_spectralDensity_eq_integral_densityReal_mul
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) :
    (∫ h, f h ∂(normalizedCompactHaarMeasure G).withDensity
      (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData t)) =
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t h * f h
        ∂normalizedCompactHaarMeasure G := by
  rw [integral_withDensity_eq_integral_toReal_smul
    (measurable_unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData t)
    (Filter.Eventually.of_forall fun _ => ENNReal.ofReal_lt_top)]
  apply integral_congr_ae
  filter_upwards [] with h
  rw [unitaryMatrixDualCasimirHeatDensityENNReal,
    ENNReal.toReal_ofReal (unitaryMatrixDualCasimirHeatDensityReal_pos heatTraceData
      bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.positivity ht h).le]
  rfl

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Driver's kernel formula is equivalently right translation by the spectral density. The proof
uses left Haar invariance and spectral inversion symmetry; no commutativity is used. -/
theorem generated_operator_eq_rightIncrementIntegral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
      ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t x * f (g * x)
        ∂normalizedCompactHaarMeasure G := by
  let μ := normalizedCompactHaarMeasure G
  let kernelIntegrand : G → ℝ := fun h =>
    unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
  have kernelIntegrand_continuous : Continuous kernelIntegrand := by
    exact ((continuous_unitaryMatrixDualCasimirHeatDensityReal heatTraceData t).comp
      (continuous_inv.mul continuous_const)).mul f.continuous
  have left_measurable : Measurable (fun x : G => g * x) :=
    (continuous_const_mul g).measurable
  calc
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g = ∫ h, kernelIntegrand h ∂μ := by
      simpa only [kernelIntegrand, μ,
        TwoDimensionalSelectedLoopSpectralHeatEquationBridgeData.toHeatEquationCoreData]
        using bridge.spectralHeatKernel.kernelOperator.heatOperator_eq_kernelIntegral t ht f g
    _ = ∫ h, kernelIntegrand h ∂Measure.map (g * ·) μ := by
      rw [normalizedCompactHaarMeasure_map_mul_left]
    _ = ∫ x, kernelIntegrand (g * x) ∂μ :=
      integral_map left_measurable.aemeasurable kernelIntegrand_continuous.aestronglyMeasurable
    _ = ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t x * f (g * x) ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with x
      dsimp only [kernelIntegrand]
      rw [show (g * x)⁻¹ * g = x⁻¹ by group,
        unitaryMatrixDualCasimirHeatDensityReal_inv heatTraceData ht]

omit [FiniteDimensional ℝ E] in
/-- At every deterministic base point, Driver's generated heat operator is exactly expectation of a
continuous test after right multiplication by any positive Brownian increment. This remains an
unconditional equality and does not assert a conditional Markov property for the random process. -/
theorem generated_operator_eq_rightIncrementExpectation
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (g : G) (s t : NNReal) (ht : 0 < t) (f : C(G, ℝ)) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f g =
      ∫ samplePoint, f (g * ((bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint)) ∂bridge.brownian.probabilityMeasure := by
  let increment : Ω → G := fun samplePoint =>
    (bridge.brownian.process s samplePoint)⁻¹ * bridge.brownian.process (s + t) samplePoint
  let translated : C(G, ℝ) :=
    ⟨fun x => f (g * x), f.continuous.comp (continuous_const_mul g)⟩
  have increment_measurable : Measurable increment :=
    (bridge.brownian.process_measurable s).inv.mul
      (bridge.brownian.process_measurable (s + t))
  have hmap := bridge.stationary_increment_law_spectral s t ht
  have hintegralMap :
      (∫ x, translated x ∂Measure.map increment bridge.brownian.probabilityMeasure) =
        ∫ samplePoint, translated (increment samplePoint) ∂bridge.brownian.probabilityMeasure :=
    integral_map increment_measurable.aemeasurable translated.continuous.aestronglyMeasurable
  calc
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f g =
        ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData (t : ℝ) x * f (g * x)
          ∂normalizedCompactHaarMeasure G :=
      bridge.generated_operator_eq_rightIncrementIntegral (t : ℝ) (by exact_mod_cast ht) f g
    _ = ∫ x, translated x ∂(normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) :=
      (bridge.integral_spectralDensity_eq_integral_densityReal_mul
        (t : ℝ) (by exact_mod_cast ht) translated).symm
    _ = ∫ x, translated x ∂Measure.map increment bridge.brownian.probabilityMeasure := by
      rw [hmap]
    _ = ∫ samplePoint, translated (increment samplePoint) ∂bridge.brownian.probabilityMeasure :=
      hintegralMap

omit [FiniteDimensional ℝ E] in
/-- At the identity, Driver's generated heat operator is exactly expectation of a continuous test
function of any positive Brownian right increment. This is an unconditional equality and does not
assert a conditional Markov property. -/
theorem generated_operator_one_eq_increment_expectation
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (ht : 0 < t) (f : C(G, ℝ)) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f 1 =
      ∫ samplePoint, f ((bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint) ∂bridge.brownian.probabilityMeasure := by
  simpa only [one_mul] using
    bridge.generated_operator_eq_rightIncrementExpectation 1 s t ht f

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- The operator attached to the same spectral heat core is generated by the unchanged real
pairing Laplacian with Driver's factor `1/2`. -/
theorem generated_operator_hasDerivAt
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    HasDerivAt (fun s => bridge.spectralHeatKernel.kernelOperator.heatOperator s f g)
      ((1 / 2 : ℝ) * realLaplacian.laplacian
        (bridge.spectralHeatKernel.kernelOperator.positiveTimeSmooth t ht f) g) t :=
  bridge.spectralHeatKernel.kernelOperator.heatOperator_hasDerivAt t ht f g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Driver's generated operator uses the exact real part of the same spectral series governing the
Brownian increment laws. -/
theorem generated_operator_eq_spectralKernelIntegral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
        ∂normalizedCompactHaarMeasure G := by
  simpa only [TwoDimensionalSelectedLoopSpectralHeatEquationBridgeData.toHeatEquationCoreData]
    using bridge.spectralHeatKernel.kernelOperator.heatOperator_eq_kernelIntegral t ht f g

end TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData

end

end Dimensions
end YangMills
