/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Dimensions.TwoDimensionalSelectedLoopFullPastMarkov

/-!
# Finite-cylinder pi-system for the exact selected-loop process past

Finite cylinders are the sets measurable for the supremum of any finite family of process-evaluation
pullbacks through time `s`. They form a pi-system and generate the exact full past. Thus the remaining
Markov extension debt can be stated solely as the transition set-integral identity on these concrete
finite-coordinate sigma-algebras.
-/

namespace YangMills.Dimensions

open MeasureTheory ProbabilityTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection uΩ

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [SecondCountableTopology G]
    [MeasurableSpace G] [BorelSpace G] [MeasurableMul₂ G] [MeasurableInv G]
    [ChartedSpace E G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {Ω : Type uΩ} [MeasurableSpace Ω]
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {semigroup : TwoDimensionalSelectedLoopConvolutionSemigroupData law}
    {laplacian : RightInvariantPairingLaplacianData inner}
    {heat : TwoDimensionalSelectedLoopHeatEquationCoreData inner law semigroup laplacian}

/-- Sigma-algebra generated by one explicit finite family of process evaluations through `s`. -/
@[reducible] def twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) (times : Finset (Set.Iic s)) : MeasurableSpace Ω :=
  ⨆ t : times, MeasurableSpace.comap (brownian.process t.1.1) inferInstance

/-- All sets depending measurably on some finite family of process evaluations through `s`. -/
def twoDimensionalSelectedLoopFinitePastCylinderSets
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) : Set (Set Ω) :=
  {set | ∃ times : Finset (Set.Iic s),
    @MeasurableSet Ω (twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace brownian s times)
      set}

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- Every finite evaluation sigma-algebra lies below the exact full past. -/
theorem twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace_le_past
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) (times : Finset (Set.Iic s)) :
    twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace brownian s times ≤
      twoDimensionalSelectedLoopPastMeasurableSpace brownian s := by
  apply iSup_le
  intro t
  exact le_iSup
    (fun u : Set.Iic s => MeasurableSpace.comap (brownian.process u.1) inferInstance) t.1

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- Concrete finite past cylinders are closed under binary intersections. -/
theorem twoDimensionalSelectedLoopFinitePastCylinderSets_isPiSystem
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) : IsPiSystem (twoDimensionalSelectedLoopFinitePastCylinderSets brownian s) := by
  intro left hleft right hright _
  rcases hleft with ⟨leftTimes, left_measurable⟩
  rcases hright with ⟨rightTimes, right_measurable⟩
  refine ⟨leftTimes ∪ rightTimes, ?_⟩
  have left_le :
      twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace brownian s leftTimes ≤
        twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace brownian s
          (leftTimes ∪ rightTimes) := by
    apply iSup_le
    intro t
    exact le_iSup
      (fun u : ↥(leftTimes ∪ rightTimes) =>
        MeasurableSpace.comap (brownian.process u.1.1) inferInstance)
      ⟨t.1, Finset.mem_union_left rightTimes t.2⟩
  have right_le :
      twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace brownian s rightTimes ≤
        twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace brownian s
          (leftTimes ∪ rightTimes) := by
    apply iSup_le
    intro t
    exact le_iSup
      (fun u : ↥(leftTimes ∪ rightTimes) =>
        MeasurableSpace.comap (brownian.process u.1.1) inferInstance)
      ⟨t.1, Finset.mem_union_right leftTimes t.2⟩
  exact (left_le left left_measurable).inter (right_le right right_measurable)

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- The concrete finite-cylinder pi-system generates exactly the supremum of all process evaluations
through `s`; no countability or enumeration of time is assumed. -/
theorem twoDimensionalSelectedLoopFinitePastCylinderSets_generateFrom_eq
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) :
    MeasurableSpace.generateFrom (twoDimensionalSelectedLoopFinitePastCylinderSets brownian s) =
      twoDimensionalSelectedLoopPastMeasurableSpace brownian s := by
  apply le_antisymm
  · apply MeasurableSpace.generateFrom_le
    intro set hset
    rcases hset with ⟨times, set_measurable⟩
    exact (twoDimensionalSelectedLoopFiniteEvaluationMeasurableSpace_le_past
      brownian s times) set set_measurable
  · apply iSup_le
    intro t set set_measurable
    apply MeasurableSpace.measurableSet_generateFrom
    refine ⟨{t}, ?_⟩
    exact (le_iSup
      (fun u : ({t} : Finset (Set.Iic s)) =>
        MeasurableSpace.comap (brownian.process u.1.1) inferInstance)
      ⟨t, Finset.mem_singleton_self t⟩) set set_measurable

/-- Reduced process-specific obligation: prove the transition set-integral identity only for sets
measurable with respect to some finite family of past evaluations. The generic pi-system theorem
then supplies the full-past conditional and bounded-test semantics. -/
structure TwoDimensionalSelectedLoopFinitePastCylinderMarkovData
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)) where
  cylinder_transition : ∀ (s t : NNReal), 0 < t → ∀ f : C(G, ℝ),
    ∀ set, set ∈ twoDimensionalSelectedLoopFinitePastCylinderSets bridge.brownian s →
      (∫ samplePoint in set,
        bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
          (bridge.brownian.process s samplePoint)
        ∂bridge.brownian.probabilityMeasure) =
      ∫ samplePoint in set, f (bridge.brownian.process (s + t) samplePoint)
        ∂bridge.brownian.probabilityMeasure

omit [FiniteDimensional ℝ E] in
/-- The finite-cylinder obligation canonically supplies the reduced pi-system record; the total
transition identity is its `univ` case. -/
noncomputable def TwoDimensionalSelectedLoopFinitePastCylinderMarkovData.toPiSystemMarkovData
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    {bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)}
    (data : TwoDimensionalSelectedLoopFinitePastCylinderMarkovData bridge) :
    TwoDimensionalSelectedLoopFullPastPiSystemMarkovData bridge where
  generator := twoDimensionalSelectedLoopFinitePastCylinderSets bridge.brownian
  generator_pi :=
    twoDimensionalSelectedLoopFinitePastCylinderSets_isPiSystem bridge.brownian
  generator_eq := fun s =>
    (twoDimensionalSelectedLoopFinitePastCylinderSets_generateFrom_eq bridge.brownian s).symm
  total_transition := by
    intro s t ht f
    have transition := data.cylinder_transition s t ht f Set.univ
      ⟨∅, MeasurableSet.univ⟩
    simpa only [MeasureTheory.setIntegral_univ] using transition
  generator_transition := data.cylinder_transition

omit [FiniteDimensional ℝ E] in
/-- Finite-cylinder set identities construct the exact universal full-past Markov acceptance data. -/
noncomputable def TwoDimensionalSelectedLoopFinitePastCylinderMarkovData.toFullPastMarkovData
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    {bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)}
    (data : TwoDimensionalSelectedLoopFinitePastCylinderMarkovData bridge) :
    TwoDimensionalSelectedLoopFullPastMarkovData bridge :=
  data.toPiSystemMarkovData.toFullPastMarkovData

end

end YangMills.Dimensions
