/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Dimensions.TwoDimensionalSelectedLoopHeatEquation

/-!
# Operator-kernel bridge for the selected two-dimensional heat density

Driver Remark 4.13 uses the explicit operator identity
`exp(t Δ / 2) f(g) = ∫ Q_t(h⁻¹g) f(h) dh`. This uninhabited interface designates the generated
operator semigroup, ties it to the exact Definition 4.7 pairing Laplacian and initial identity, and
requires the displayed convolution-kernel formula for the unchanged real density.
-/

namespace YangMills.Dimensions

open MeasureTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [T2Space G] [SecondCountableTopology G] [ChartedSpace E G]
    [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    [CompactSpace G] [MeasurableSpace G] [BorelSpace G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {semigroup : TwoDimensionalSelectedLoopConvolutionSemigroupData law}
    {laplacian : RightInvariantPairingLaplacianData inner}

/-- Exact operator-semigroup meaning of the unchanged selected density as Driver's heat kernel. -/
structure TwoDimensionalSelectedLoopHeatKernelOperatorData
    (heat : TwoDimensionalSelectedLoopHeatEquationCoreData
      inner law semigroup laplacian) where
  /-- Designated `exp(t Δ / 2)` operator on continuous real functions. -/
  heatOperator : ℝ → C(G, ℝ) → C(G, ℝ)
  /-- Initial identity operator. -/
  heatOperator_zero : ∀ f, heatOperator 0 f = f
  /-- Positive-time operator outputs are spatially smooth. -/
  positiveTimeSmooth : ∀ t : ℝ, 0 < t → C(G, ℝ) →
    SmoothLieGroupScalarFunction (E := E) (G := G)
  positiveTimeSmooth_apply : ∀ (t : ℝ) (ht : 0 < t) f g,
    positiveTimeSmooth t ht f g = heatOperator t f g
  /-- Exact semigroup law on nonnegative times. -/
  heatOperator_add : ∀ s t : ℝ, 0 ≤ s → 0 ≤ t → ∀ f,
    heatOperator (s + t) f = heatOperator s (heatOperator t f)
  /-- The designated operator is generated by exactly `Δ / 2`. -/
  heatOperator_hasDerivAt : ∀ (t : ℝ) (ht : 0 < t) f g,
    HasDerivAt (fun s => heatOperator s f g)
      ((1 / 2 : ℝ) * laplacian.laplacian (positiveTimeSmooth t ht f) g) t
  /-- Driver's displayed convolution-kernel formula, with canonical normalized Haar measure. -/
  heatOperator_eq_kernelIntegral : ∀ (t : ℝ) (_ht : 0 < t) f g,
    heatOperator t f g =
      ∫ h, heat.densityReal t (h⁻¹ * g) * f h ∂normalizedCompactHaarMeasure G

end

end YangMills.Dimensions
