/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Dimensions.TwoDimensionalSelectedLoopBrownianRealization
import YangMills.Dimensions.TwoDimensionalSelectedLoopSpectralHeatKernelBridge
import Mathlib.Probability.Independence.Integration

/-!
# Spectral Brownian and generated-operator coherence

Sengupta and Driver identify the area-indexed heat density both as the law of group Brownian
increments and as the kernel of the semigroup generated by `Δ / 2`. The existing Brownian interface
records continuous paths and independent stationary right increments, while the existing
operator interface records the generated semigroup and Driver's kernel formula.

`TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData` forces both interfaces to use the
exact heat core constructed from one spectral density bridge. It derives the Brownian increment and
marginal laws with the spectral `ENNReal` density and exposes the unchanged generator formula.

This is still not a construction of Brownian motion. In particular, no conditional-expectation or
Markov transition theorem is inferred merely from the marginal/increment law; that stronger
stochastic operator identification remains future proof debt.
-/

namespace YangMills
namespace Dimensions

open MeasureTheory ProbabilityTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection uΩ

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [SecondCountableTopology G]
    [MeasurableSpace G] [BorelSpace G] [MeasurableMul₂ G] [MeasurableInv G]
    [ChartedSpace E G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {Ω : Type uΩ} [MeasurableSpace Ω]
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}

/-- One exact spectral heat core shared by Driver's generated operator and a supplied Brownian
realization on `Ω`. -/
structure TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData where
  spectralHeatKernel : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
    (law := law) (inner := inner) (realLaplacian := realLaplacian)
    (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData)
  brownian : TwoDimensionalSelectedLoopBrownianRealizationData
    inner law spectralHeatKernel.convolutionSemigroup realLaplacian
      spectralHeatKernel.heatEquationCore Ω

namespace TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Every positive stationary right increment has exactly the conditional spectral `ENNReal`
density, not merely an unrelated selected-loop density. -/
theorem stationary_increment_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (ht : 0 < t) :
    Measure.map (fun samplePoint =>
      (bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint) bridge.brownian.probabilityMeasure =
      (normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) := by
  rw [bridge.brownian.stationary_increment_law s t ht]
  congr 1
  funext g
  exact bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.selectedAreaDensity_eq
    (t : ℝ) (by exact_mod_cast ht) g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- The positive-time Brownian marginal has exactly the spectral density. -/
theorem marginal_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : NNReal) (ht : 0 < t) :
    Measure.map (bridge.brownian.process t) bridge.brownian.probabilityMeasure =
      (normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) := by
  rw [bridge.brownian.marginal_law t ht]
  congr 1
  funext g
  exact bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.selectedAreaDensity_eq
    (t : ℝ) (by exact_mod_cast ht) g

omit [FiniteDimensional ℝ E] in
/-- At two successive positive times, the process value and following right increment have the exact
product of the two spectral density measures. This is derived from finite increment independence,
identity start, and the spectral marginal laws rather than supplied as a Markov field. -/
theorem process_rightIncrement_joint_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (hs : 0 < s) (ht : 0 < t) :
    Measure.map (fun samplePoint =>
      (bridge.brownian.process s samplePoint,
        (bridge.brownian.process s samplePoint)⁻¹ *
          bridge.brownian.process (s + t) samplePoint)) bridge.brownian.probabilityMeasure =
      ((normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (s : ℝ))).prod
      ((normalizedCompactHaarMeasure G).withDensity
        (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ))) := by
  let increment : Ω → G := fun samplePoint =>
    (bridge.brownian.process s samplePoint)⁻¹ * bridge.brownian.process (s + t) samplePoint
  have increment_measurable : Measurable increment :=
    (bridge.brownian.process_measurable s).inv.mul
      (bridge.brownian.process_measurable (s + t))
  letI : IsFiniteMeasure bridge.brownian.probabilityMeasure :=
    ⟨by rw [bridge.brownian.probability_normalized]; exact ENNReal.one_lt_top⟩
  have joint := (bridge.brownian.process_indep_rightIncrement s t).map_prod_eq_prod_map_map
    (bridge.brownian.process_measurable s).aemeasurable increment_measurable.aemeasurable
  rw [bridge.marginal_law_spectral s hs,
    bridge.stationary_increment_law_spectral s t ht] at joint
  exact joint

omit [FiniteDimensional ℝ E] in
/-- The exact two-time process law is the pushforward of the two spectral factors by
`(x,y) ↦ (x,x*y)`, displaying the right-increment transition orientation without introducing a
conditional expectation. -/
theorem process_twoTime_law_spectral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (hs : 0 < s) (ht : 0 < t) :
    Measure.map (fun samplePoint =>
      (bridge.brownian.process s samplePoint,
        bridge.brownian.process (s + t) samplePoint)) bridge.brownian.probabilityMeasure =
      Measure.map (fun pair : G × G => (pair.1, pair.1 * pair.2))
        (((normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (s : ℝ))).prod
        ((normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)))) := by
  let processIncrement : Ω → G × G := fun samplePoint =>
    (bridge.brownian.process s samplePoint,
      (bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint)
  let multiplyIncrement : G × G → G × G := fun pair => (pair.1, pair.1 * pair.2)
  have processIncrement_measurable : Measurable processIncrement :=
    (bridge.brownian.process_measurable s).prodMk
      ((bridge.brownian.process_measurable s).inv.mul
        (bridge.brownian.process_measurable (s + t)))
  have multiplyIncrement_measurable : Measurable multiplyIncrement :=
    measurable_fst.prodMk (measurable_fst.mul measurable_snd)
  calc
    Measure.map (fun samplePoint =>
        (bridge.brownian.process s samplePoint,
          bridge.brownian.process (s + t) samplePoint)) bridge.brownian.probabilityMeasure =
      Measure.map multiplyIncrement
        (Measure.map processIncrement bridge.brownian.probabilityMeasure) := by
          rw [Measure.map_map multiplyIncrement_measurable processIncrement_measurable]
          apply Measure.map_congr
          filter_upwards [] with samplePoint
          simp [processIncrement, multiplyIncrement]
    _ = Measure.map multiplyIncrement
        (((normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (s : ℝ))).prod
        ((normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)))) := by
      rw [bridge.process_rightIncrement_joint_law_spectral s t hs ht]

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Integrating a continuous real test function against the spectral `ENNReal` density measure is
exactly weighted integration against its strictly positive real representative. -/
theorem integral_spectralDensity_eq_integral_densityReal_mul
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) :
    (∫ h, f h ∂(normalizedCompactHaarMeasure G).withDensity
      (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData t)) =
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t h * f h
        ∂normalizedCompactHaarMeasure G := by
  rw [integral_withDensity_eq_integral_toReal_smul
    (measurable_unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData t)
    (Filter.Eventually.of_forall fun _ => ENNReal.ofReal_lt_top)]
  apply integral_congr_ae
  filter_upwards [] with h
  rw [unitaryMatrixDualCasimirHeatDensityENNReal,
    ENNReal.toReal_ofReal (unitaryMatrixDualCasimirHeatDensityReal_pos heatTraceData
      bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.positivity ht h).le]
  rfl

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Driver's kernel formula is equivalently right translation by the spectral density. The proof
uses left Haar invariance and spectral inversion symmetry; no commutativity is used. -/
theorem generated_operator_eq_rightIncrementIntegral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
      ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t x * f (g * x)
        ∂normalizedCompactHaarMeasure G := by
  let μ := normalizedCompactHaarMeasure G
  let kernelIntegrand : G → ℝ := fun h =>
    unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
  have kernelIntegrand_continuous : Continuous kernelIntegrand := by
    exact ((continuous_unitaryMatrixDualCasimirHeatDensityReal heatTraceData t).comp
      (continuous_inv.mul continuous_const)).mul f.continuous
  have left_measurable : Measurable (fun x : G => g * x) :=
    (continuous_const_mul g).measurable
  calc
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g = ∫ h, kernelIntegrand h ∂μ := by
      simpa only [kernelIntegrand, μ,
        TwoDimensionalSelectedLoopSpectralHeatEquationBridgeData.toHeatEquationCoreData]
        using bridge.spectralHeatKernel.kernelOperator.heatOperator_eq_kernelIntegral t ht f g
    _ = ∫ h, kernelIntegrand h ∂Measure.map (g * ·) μ := by
      rw [normalizedCompactHaarMeasure_map_mul_left]
    _ = ∫ x, kernelIntegrand (g * x) ∂μ :=
      integral_map left_measurable.aemeasurable kernelIntegrand_continuous.aestronglyMeasurable
    _ = ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t x * f (g * x) ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with x
      dsimp only [kernelIntegrand]
      rw [show (g * x)⁻¹ * g = x⁻¹ by group,
        unitaryMatrixDualCasimirHeatDensityReal_inv heatTraceData ht]

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Driver's generated operator is integration after deterministic right multiplication against the
exact spectral probability measure. -/
theorem generated_operator_eq_spectralMeasureIntegral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
      ∫ x, f (g * x) ∂unitaryMatrixDualCasimirHeatProbabilityMeasure heatTraceData t := by
  let translated : C(G, ℝ) :=
    ⟨fun x => f (g * x), f.continuous.comp (continuous_const_mul g)⟩
  calc
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
        ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t x * f (g * x)
          ∂normalizedCompactHaarMeasure G :=
      bridge.generated_operator_eq_rightIncrementIntegral t ht f g
    _ = ∫ x, translated x ∂(normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData t) :=
      (bridge.integral_spectralDensity_eq_integral_densityReal_mul t ht translated).symm
    _ = ∫ x, f (g * x)
          ∂unitaryMatrixDualCasimirHeatProbabilityMeasure heatTraceData t := rfl

omit [FiniteDimensional ℝ E] in
/-- At every deterministic base point, Driver's generated heat operator is exactly expectation of a
continuous test after right multiplication by any positive Brownian increment. This remains an
unconditional equality and does not assert a conditional Markov property for the random process. -/
theorem generated_operator_eq_rightIncrementExpectation
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (g : G) (s t : NNReal) (ht : 0 < t) (f : C(G, ℝ)) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f g =
      ∫ samplePoint, f (g * ((bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint)) ∂bridge.brownian.probabilityMeasure := by
  let increment : Ω → G := fun samplePoint =>
    (bridge.brownian.process s samplePoint)⁻¹ * bridge.brownian.process (s + t) samplePoint
  let translated : C(G, ℝ) :=
    ⟨fun x => f (g * x), f.continuous.comp (continuous_const_mul g)⟩
  have increment_measurable : Measurable increment :=
    (bridge.brownian.process_measurable s).inv.mul
      (bridge.brownian.process_measurable (s + t))
  have hmap := bridge.stationary_increment_law_spectral s t ht
  have hintegralMap :
      (∫ x, translated x ∂Measure.map increment bridge.brownian.probabilityMeasure) =
        ∫ samplePoint, translated (increment samplePoint) ∂bridge.brownian.probabilityMeasure :=
    integral_map increment_measurable.aemeasurable translated.continuous.aestronglyMeasurable
  calc
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f g =
        ∫ x, unitaryMatrixDualCasimirHeatDensityReal heatTraceData (t : ℝ) x * f (g * x)
          ∂normalizedCompactHaarMeasure G :=
      bridge.generated_operator_eq_rightIncrementIntegral (t : ℝ) (by exact_mod_cast ht) f g
    _ = ∫ x, translated x ∂(normalizedCompactHaarMeasure G).withDensity
          (unitaryMatrixDualCasimirHeatDensityENNReal heatTraceData (t : ℝ)) :=
      (bridge.integral_spectralDensity_eq_integral_densityReal_mul
        (t : ℝ) (by exact_mod_cast ht) translated).symm
    _ = ∫ x, translated x ∂Measure.map increment bridge.brownian.probabilityMeasure := by
      rw [hmap]
    _ = ∫ samplePoint, translated (increment samplePoint) ∂bridge.brownian.probabilityMeasure :=
      hintegralMap

omit [FiniteDimensional ℝ E] in
/-- Two-time continuous tests satisfy the weak state-Markov identity with the exact generated
operator. This is derived from the spectral two-time law and product Fubini. It quantifies only over
the current-state observable `φ(B_s)` and therefore does not assert conditioning on the full past
sigma-algebra. -/
theorem twoTime_weakMarkov_identity
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (hs : 0 < s) (ht : 0 < t) (φ f : C(G, ℝ)) :
    (∫ samplePoint, φ (bridge.brownian.process s samplePoint) *
      f (bridge.brownian.process (s + t) samplePoint)
        ∂bridge.brownian.probabilityMeasure) =
      ∫ samplePoint, φ (bridge.brownian.process s samplePoint) *
        bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
          (bridge.brownian.process s samplePoint)
        ∂bridge.brownian.probabilityMeasure := by
  let μs := unitaryMatrixDualCasimirHeatProbabilityMeasure heatTraceData (s : ℝ)
  let μt := unitaryMatrixDualCasimirHeatProbabilityMeasure heatTraceData (t : ℝ)
  let processPair : Ω → G × G := fun samplePoint =>
    (bridge.brownian.process s samplePoint, bridge.brownian.process (s + t) samplePoint)
  let multiplyIncrement : G × G → G × G := fun pair => (pair.1, pair.1 * pair.2)
  let pairTest : C(G × G, ℝ) :=
    ⟨fun pair => φ pair.1 * f pair.2,
      (φ.continuous.comp continuous_fst).mul (f.continuous.comp continuous_snd)⟩
  let stateTest : C(G, ℝ) :=
    ⟨fun x => φ x * bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f x,
      φ.continuous.mul
        (bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).continuous⟩
  have processPair_measurable : Measurable processPair :=
    (bridge.brownian.process_measurable s).prodMk
      (bridge.brownian.process_measurable (s + t))
  have multiplyIncrement_measurable : Measurable multiplyIncrement :=
    measurable_fst.prodMk (measurable_fst.mul measurable_snd)
  letI : IsFiniteMeasure μs :=
    ⟨by
      rw [unitaryMatrixDualCasimirHeatProbabilityMeasure_univ
        bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.casimirBridge
        bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.positivity
        (by exact_mod_cast hs)]
      exact ENNReal.one_lt_top⟩
  letI : IsFiniteMeasure μt :=
    ⟨by
      rw [unitaryMatrixDualCasimirHeatProbabilityMeasure_univ
        bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.casimirBridge
        bridge.spectralHeatKernel.heatEquationBridge.spectralDensityBridge.positivity
        (by exact_mod_cast ht)]
      exact ENNReal.one_lt_top⟩
  have pairIntegrable : Integrable
      (fun pair : G × G => φ pair.1 * f (pair.1 * pair.2)) (μs.prod μt) := by
    have hc : Continuous (fun pair : G × G => φ pair.1 * f (pair.1 * pair.2)) := by
      exact (φ.continuous.comp continuous_fst).mul
        (f.continuous.comp (continuous_fst.mul continuous_snd))
    simpa only [integrableOn_univ] using
      hc.continuousOn.integrableOn_compact (μ := μs.prod μt) isCompact_univ
  have processPairIntegral :
      (∫ pair, pairTest pair ∂Measure.map processPair bridge.brownian.probabilityMeasure) =
        ∫ samplePoint, pairTest (processPair samplePoint)
          ∂bridge.brownian.probabilityMeasure :=
    integral_map processPair_measurable.aemeasurable pairTest.continuous.aestronglyMeasurable
  have stateIntegral :
      (∫ x, stateTest x ∂Measure.map (bridge.brownian.process s)
        bridge.brownian.probabilityMeasure) =
        ∫ samplePoint, stateTest (bridge.brownian.process s samplePoint)
          ∂bridge.brownian.probabilityMeasure :=
    integral_map (bridge.brownian.process_measurable s).aemeasurable
      stateTest.continuous.aestronglyMeasurable
  calc
    (∫ samplePoint, φ (bridge.brownian.process s samplePoint) *
        f (bridge.brownian.process (s + t) samplePoint)
          ∂bridge.brownian.probabilityMeasure) =
      ∫ pair, pairTest pair ∂Measure.map processPair bridge.brownian.probabilityMeasure := by
        exact processPairIntegral.symm
    _ = ∫ pair, pairTest pair ∂Measure.map multiplyIncrement (μs.prod μt) := by
      rw [bridge.process_twoTime_law_spectral s t hs ht]
      rfl
    _ = ∫ pair, pairTest (multiplyIncrement pair) ∂μs.prod μt :=
      integral_map multiplyIncrement_measurable.aemeasurable
        pairTest.continuous.aestronglyMeasurable
    _ = ∫ x, ∫ y, φ x * f (x * y) ∂μt ∂μs := by
      exact integral_prod _ pairIntegrable
    _ = ∫ x, stateTest x ∂μs := by
      apply integral_congr_ae
      filter_upwards [] with x
      change (∫ y, φ x * f (x * y) ∂μt) =
        φ x * bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f x
      rw [bridge.generated_operator_eq_spectralMeasureIntegral
        (t : ℝ) (by exact_mod_cast ht) f x]
      rw [integral_const_mul]
    _ = ∫ x, stateTest x ∂Measure.map (bridge.brownian.process s)
          bridge.brownian.probabilityMeasure := by
      rw [bridge.marginal_law_spectral s hs]
      rfl
    _ = ∫ samplePoint, φ (bridge.brownian.process s samplePoint) *
        bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
          (bridge.brownian.process s samplePoint)
          ∂bridge.brownian.probabilityMeasure := by
      exact stateIntegral

omit [FiniteDimensional ℝ E] in
/-- At the identity, Driver's generated heat operator is exactly expectation of a continuous test
function of any positive Brownian right increment. This is an unconditional equality and does not
assert a conditional Markov property. -/
theorem generated_operator_one_eq_increment_expectation
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (ht : 0 < t) (f : C(G, ℝ)) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f 1 =
      ∫ samplePoint, f ((bridge.brownian.process s samplePoint)⁻¹ *
        bridge.brownian.process (s + t) samplePoint) ∂bridge.brownian.probabilityMeasure := by
  simpa only [one_mul] using
    bridge.generated_operator_eq_rightIncrementExpectation 1 s t ht f

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- The operator attached to the same spectral heat core is generated by the unchanged real
pairing Laplacian with Driver's factor `1/2`. -/
theorem generated_operator_hasDerivAt
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    HasDerivAt (fun s => bridge.spectralHeatKernel.kernelOperator.heatOperator s f g)
      ((1 / 2 : ℝ) * realLaplacian.laplacian
        (bridge.spectralHeatKernel.kernelOperator.positiveTimeSmooth t ht f) g) t :=
  bridge.spectralHeatKernel.kernelOperator.heatOperator_hasDerivAt t ht f g

omit [FiniteDimensional ℝ E] [MeasurableMul₂ G] [MeasurableInv G] in
/-- Driver's generated operator uses the exact real part of the same spectral series governing the
Brownian increment laws. -/
theorem generated_operator_eq_spectralKernelIntegral
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.spectralHeatKernel.kernelOperator.heatOperator t f g =
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
        ∂normalizedCompactHaarMeasure G := by
  simpa only [TwoDimensionalSelectedLoopSpectralHeatEquationBridgeData.toHeatEquationCoreData]
    using bridge.spectralHeatKernel.kernelOperator.heatOperator_eq_kernelIntegral t ht f g

end TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData

end

end Dimensions
end YangMills
