/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Dimensions.TwoDimensionalSelectedLoopFinitePastBoundedMeasurableTransition
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut
import YangMills.Mathematics.ConditionalExpectationPiSystem

/-!
# Exact full-past sigma-algebra and Markov obligation

The process past at time `s` is the supremum of the sigma-algebras pulled back by every evaluation
`B(t)` with `t ≤ s`. A source-facing weak full-past Markov predicate tests the transition identity
against every bounded real random variable measurable for that sigma-algebra.

Every bounded measurable finite process-cylinder test is proved past-measurable and satisfies the
required identity. Extending this finite-cylinder result to every bounded full-past-measurable test
is retained as an explicit monotone-class obligation. From any supplied extension, conditional-
expectation uniqueness derives the exact full-past conditional Markov identity.
-/

namespace YangMills.Dimensions

open MeasureTheory ProbabilityTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection uΩ

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [SecondCountableTopology G]
    [MeasurableSpace G] [BorelSpace G] [MeasurableMul₂ G] [MeasurableInv G]
    [ChartedSpace E G] [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {Ω : Type uΩ} [MeasurableSpace Ω]
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {semigroup : TwoDimensionalSelectedLoopConvolutionSemigroupData law}
    {laplacian : RightInvariantPairingLaplacianData inner}
    {heat : TwoDimensionalSelectedLoopHeatEquationCoreData
      inner law semigroup laplacian}

/-- Sigma-algebra generated by all process evaluations at times at most `s`. -/
@[reducible] def twoDimensionalSelectedLoopPastMeasurableSpace
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) : MeasurableSpace Ω :=
  ⨆ t : Set.Iic s, MeasurableSpace.comap (brownian.process t.1) inferInstance

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- Every process evaluation at or before `s` is measurable for the exact past sigma-algebra. -/
theorem TwoDimensionalSelectedLoopBrownianRealizationData.process_measurable_past
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s t : NNReal) (ht : t ≤ s) :
    @Measurable Ω G (twoDimensionalSelectedLoopPastMeasurableSpace brownian s) _
      (brownian.process t) := by
  rw [measurable_iff_comap_le]
  exact le_iSup
    (fun u : Set.Iic s => MeasurableSpace.comap (brownian.process u.1) inferInstance) ⟨t, ht⟩

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- The generated past sigma-algebra is a sub-sigma-algebra of the ambient process space. -/
theorem TwoDimensionalSelectedLoopBrownianRealizationData.pastMeasurableSpace_le_ambient
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) :
    twoDimensionalSelectedLoopPastMeasurableSpace brownian s ≤
      (inferInstance : MeasurableSpace Ω) := by
  apply iSup_le
  intro t
  exact (brownian.process_measurable t.1).comap_le

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- Process past sigma-algebras increase with time. -/
theorem TwoDimensionalSelectedLoopBrownianRealizationData.pastMeasurableSpace_mono
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    {s t : NNReal} (hst : s ≤ t) :
    twoDimensionalSelectedLoopPastMeasurableSpace brownian s ≤
      twoDimensionalSelectedLoopPastMeasurableSpace brownian t := by
  apply iSup_le
  intro u
  exact le_iSup
    (fun v : Set.Iic t => MeasurableSpace.comap (brownian.process v.1) inferInstance)
    ⟨u.1, u.2.trans hst⟩

/-- A bounded measurable test of an actual finite process-evaluation history. -/
def twoDimensionalFinitePastProcessTest
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (n : ℕ) (times : Fin (n + 2) → NNReal)
    (test : (Fin n → G) → ℝ) (samplePoint : Ω) : ℝ :=
  test (twoDimensionalPastProcessValues brownian n times samplePoint)

omit [FiniteDimensional ℝ E] [T2Space G] [SecondCountableTopology G]
    [MeasurableMul₂ G] [MeasurableInv G] in
/-- Every measurable finite process-history test using only times at most `s` is measurable for the
exact full-past sigma-algebra. -/
theorem TwoDimensionalSelectedLoopBrownianRealizationData.finitePastProcessTest_measurable_past
    (brownian : TwoDimensionalSelectedLoopBrownianRealizationData
      inner law semigroup laplacian heat Ω)
    (s : NNReal) (n : ℕ) (times : Fin (n + 2) → NNReal)
    (history_le : ∀ i : Fin n, times i.succ.castSucc ≤ s)
    (test : (Fin n → G) → ℝ) (test_measurable : Measurable test) :
    @Measurable Ω ℝ (twoDimensionalSelectedLoopPastMeasurableSpace brownian s) _
      (twoDimensionalFinitePastProcessTest brownian n times test) := by
  have history_measurable :
      @Measurable Ω (Fin n → G)
        (twoDimensionalSelectedLoopPastMeasurableSpace brownian s) _
        (twoDimensionalPastProcessValues brownian n times) := by
    apply (@measurable_pi_iff Ω (Fin n) (fun _ => G)
      (twoDimensionalSelectedLoopPastMeasurableSpace brownian s)
      (fun _ => inferInstance)).mpr
    intro i
    exact brownian.process_measurable_past s (times i.succ.castSucc) (history_le i)
  exact test_measurable.comp history_measurable

/-- Weak full-past Markov semantics: every bounded real test measurable for the exact process past
obeys the generated spectral transition identity. -/
def TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData.HasFullPastWeakMarkovProperty
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)) : Prop :=
  ∀ (s t : NNReal), 0 < t → ∀ (pastTest : Ω → ℝ),
    @Measurable Ω ℝ
      (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) _ pastTest →
    (∃ bound : ℝ, ∀ samplePoint, ‖pastTest samplePoint‖ ≤ bound) →
    ∀ f : C(G, ℝ),
      (∫ samplePoint, pastTest samplePoint *
        f (bridge.brownian.process (s + t) samplePoint)
        ∂bridge.brownian.probabilityMeasure) =
      ∫ samplePoint, pastTest samplePoint *
        bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
          (bridge.brownian.process s samplePoint)
        ∂bridge.brownian.probabilityMeasure

/-- Conditional-expectation form of the full-past Markov property. This is deliberately separate
from finite-history testing: the conditional expectation is taken with respect to the exact
sigma-algebra generated by every process evaluation through time `s`. -/
def TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData.HasFullPastConditionalMarkovProperty
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)) : Prop :=
  ∀ (s t : NNReal), 0 < t → ∀ f : C(G, ℝ),
    MeasureTheory.condExp
        (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s)
        bridge.brownian.probabilityMeasure
        (fun samplePoint => f (bridge.brownian.process (s + t) samplePoint)) =ᵐ[
          bridge.brownian.probabilityMeasure]
      fun samplePoint =>
        bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
          (bridge.brownian.process s samplePoint)

/-- Reduced full-past obligation through a generating pi-system. Application-specific work must
supply a pi-system generating the exact process past and prove the transition set-integral identity
on its basic finite cylinders. The generic complement/disjoint-union closure is proved separately. -/
structure TwoDimensionalSelectedLoopFullPastPiSystemMarkovData
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)) where
  generator : NNReal → Set (Set Ω)
  generator_pi : ∀ s, IsPiSystem (generator s)
  generator_eq : ∀ s,
    twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s =
      MeasurableSpace.generateFrom (generator s)
  total_transition : ∀ (s t : NNReal), 0 < t → ∀ f : C(G, ℝ),
    (∫ samplePoint,
      bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
        (bridge.brownian.process s samplePoint)
      ∂bridge.brownian.probabilityMeasure) =
    ∫ samplePoint, f (bridge.brownian.process (s + t) samplePoint)
      ∂bridge.brownian.probabilityMeasure
  generator_transition : ∀ (s t : NNReal), 0 < t → ∀ f : C(G, ℝ),
    ∀ set, set ∈ generator s →
      (∫ samplePoint in set,
        bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
          (bridge.brownian.process s samplePoint)
        ∂bridge.brownian.probabilityMeasure) =
      ∫ samplePoint in set, f (bridge.brownian.process (s + t) samplePoint)
        ∂bridge.brownian.probabilityMeasure

/-- Explicit unresolved monotone-class bridge from proved bounded measurable finite cylinders to the
full process-past sigma-algebra. No inhabitant is constructed here. -/
structure TwoDimensionalSelectedLoopFullPastMarkovData
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)) where
  fullPastWeakMarkov : bridge.HasFullPastWeakMarkovProperty

omit [FiniteDimensional ℝ E] in
/-- Universal bounded weak testing against the exact past determines the corresponding conditional
expectation. This discharges the semantic bridge, but not the unresolved monotone-class construction
of `TwoDimensionalSelectedLoopFullPastMarkovData`. -/
theorem TwoDimensionalSelectedLoopFullPastMarkovData.fullPastConditionalMarkov
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    {bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)}
    (data : TwoDimensionalSelectedLoopFullPastMarkovData bridge) :
    bridge.HasFullPastConditionalMarkovProperty := by
  intro s t ht f
  let μ := bridge.brownian.probabilityMeasure
  letI : IsProbabilityMeasure μ := ⟨bridge.brownian.probability_normalized⟩
  let future : Ω → ℝ := fun samplePoint =>
    f (bridge.brownian.process (s + t) samplePoint)
  let predicted : Ω → ℝ := fun samplePoint =>
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
      (bridge.brownian.process s samplePoint)
  have hm : twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s ≤
      (inferInstance : MeasurableSpace Ω) :=
    bridge.brownian.pastMeasurableSpace_le_ambient s
  have future_measurable : Measurable future :=
    f.continuous.measurable.comp (bridge.brownian.process_measurable (s + t))
  have future_integrable : Integrable future μ := by
    apply Integrable.of_bound future_measurable.aestronglyMeasurable ‖f‖
    exact Filter.Eventually.of_forall fun samplePoint => f.norm_coe_le_norm _
  have predicted_measurable :
      @Measurable Ω ℝ (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) _
        predicted :=
    (bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).continuous.measurable.comp
      (bridge.brownian.process_measurable_past s s le_rfl)
  have predicted_integrable : Integrable predicted μ := by
    apply Integrable.of_bound
      ((bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).continuous.measurable.comp
        (bridge.brownian.process_measurable s)).aestronglyMeasurable
      ‖bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f‖
    exact Filter.Eventually.of_forall fun samplePoint =>
      (bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).norm_coe_le_norm _
  symm
  apply ae_eq_condExp_of_forall_setIntegral_eq hm future_integrable
  · intro measurableSet _ _
    exact predicted_integrable.integrableOn
  · intro measurableSet hmeasurableSet _
    have indicator_measurable :
        @Measurable Ω ℝ
          (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) _
          (measurableSet.indicator fun _ => (1 : ℝ)) :=
      measurable_const.indicator hmeasurableSet
    have indicator_bounded :
        ∃ bound : ℝ, ∀ samplePoint, ‖measurableSet.indicator (fun _ => (1 : ℝ)) samplePoint‖ ≤ bound := by
      refine ⟨1, fun samplePoint => ?_⟩
      by_cases hmem : samplePoint ∈ measurableSet <;> simp [Set.indicator, hmem]
    have weak := data.fullPastWeakMarkov s t ht
      (measurableSet.indicator fun _ => (1 : ℝ)) indicator_measurable indicator_bounded f
    calc
      ∫ samplePoint in measurableSet, predicted samplePoint ∂μ =
          ∫ samplePoint, measurableSet.indicator predicted samplePoint ∂μ :=
        (integral_indicator (hm measurableSet hmeasurableSet)).symm
      _ = ∫ samplePoint,
          measurableSet.indicator (fun _ => (1 : ℝ)) samplePoint * predicted samplePoint ∂μ := by
        apply integral_congr_ae
        exact Filter.Eventually.of_forall fun samplePoint => by
          by_cases hmem : samplePoint ∈ measurableSet <;> simp [Set.indicator, hmem]
      _ = ∫ samplePoint,
          measurableSet.indicator (fun _ => (1 : ℝ)) samplePoint * future samplePoint ∂μ :=
        weak.symm
      _ = ∫ samplePoint, measurableSet.indicator future samplePoint ∂μ := by
        apply integral_congr_ae
        exact Filter.Eventually.of_forall fun samplePoint => by
          by_cases hmem : samplePoint ∈ measurableSet <;> simp [Set.indicator, hmem]
      _ = ∫ samplePoint in measurableSet, future samplePoint ∂μ :=
        integral_indicator (hm measurableSet hmeasurableSet)
  · exact predicted_measurable.aestronglyMeasurable

omit [FiniteDimensional ℝ E] in
/-- For continuous terminal tests on this normalized process, universal bounded weak testing and the
exact conditional-expectation statement are equivalent. Thus the unresolved debt is the
finite-cylinder-to-full-past extension, not an ambiguity between two Markov semantics. -/
theorem TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData.fullPastConditionalMarkov_iff_weakMarkov
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)) :
    bridge.HasFullPastConditionalMarkovProperty ↔ bridge.HasFullPastWeakMarkovProperty := by
  constructor
  · intro conditional s t ht pastTest pastTest_measurable pastTest_bounded f
    let μ := bridge.brownian.probabilityMeasure
    let future : Ω → ℝ := fun samplePoint =>
      f (bridge.brownian.process (s + t) samplePoint)
    let predicted : Ω → ℝ := fun samplePoint =>
      bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
        (bridge.brownian.process s samplePoint)
    letI : IsProbabilityMeasure μ := ⟨bridge.brownian.probability_normalized⟩
    have hm : twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s ≤
        (inferInstance : MeasurableSpace Ω) :=
      bridge.brownian.pastMeasurableSpace_le_ambient s
    have future_measurable : Measurable future :=
      f.continuous.measurable.comp (bridge.brownian.process_measurable (s + t))
    have future_integrable : Integrable future μ := by
      apply Integrable.of_bound future_measurable.aestronglyMeasurable ‖f‖
      exact Filter.Eventually.of_forall fun samplePoint => f.norm_coe_le_norm _
    obtain ⟨bound, pastTest_bound⟩ := pastTest_bounded
    have pullOut := condExp_stronglyMeasurable_mul_of_bound₀ hm
      pastTest_measurable.aestronglyMeasurable future_integrable bound
      (Filter.Eventually.of_forall pastTest_bound)
    have conditionalIdentity := conditional s t ht f
    calc
      ∫ samplePoint, pastTest samplePoint * future samplePoint ∂μ =
          ∫ samplePoint,
            MeasureTheory.condExp
              (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) μ
              (fun samplePoint => pastTest samplePoint * future samplePoint) samplePoint ∂μ :=
        (integral_condExp hm).symm
      _ = ∫ samplePoint, pastTest samplePoint *
          MeasureTheory.condExp
            (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) μ future samplePoint
          ∂μ := integral_congr_ae pullOut
      _ = ∫ samplePoint, pastTest samplePoint * predicted samplePoint ∂μ := by
        apply integral_congr_ae
        filter_upwards [conditionalIdentity] with samplePoint hconditional
        rw [hconditional]
  · intro weak
    exact (TwoDimensionalSelectedLoopFullPastMarkovData.mk weak).fullPastConditionalMarkov

omit [FiniteDimensional ℝ E] in
/-- The generic pi-system monotone-class theorem converts the reduced finite-cylinder obligation
into exact conditional-expectation semantics. -/
theorem TwoDimensionalSelectedLoopFullPastPiSystemMarkovData.fullPastConditionalMarkov
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    {bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)}
    (data : TwoDimensionalSelectedLoopFullPastPiSystemMarkovData bridge) :
    bridge.HasFullPastConditionalMarkovProperty := by
  intro s t ht f
  let μ := bridge.brownian.probabilityMeasure
  let future : Ω → ℝ := fun samplePoint =>
    f (bridge.brownian.process (s + t) samplePoint)
  let predicted : Ω → ℝ := fun samplePoint =>
    bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
      (bridge.brownian.process s samplePoint)
  letI : IsProbabilityMeasure μ := ⟨bridge.brownian.probability_normalized⟩
  have hm : twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s ≤
      (inferInstance : MeasurableSpace Ω) :=
    bridge.brownian.pastMeasurableSpace_le_ambient s
  have future_measurable : Measurable future :=
    f.continuous.measurable.comp (bridge.brownian.process_measurable (s + t))
  have future_integrable : Integrable future μ := by
    apply Integrable.of_bound future_measurable.aestronglyMeasurable ‖f‖
    exact Filter.Eventually.of_forall fun samplePoint => f.norm_coe_le_norm _
  have predicted_measurable :
      @Measurable Ω ℝ (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) _
        predicted :=
    (bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).continuous.measurable.comp
      (bridge.brownian.process_measurable_past s s le_rfl)
  have predicted_integrable : Integrable predicted μ := by
    apply Integrable.of_bound
      ((bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).continuous.measurable.comp
        (bridge.brownian.process_measurable s)).aestronglyMeasurable
      ‖bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f‖
    exact Filter.Eventually.of_forall fun samplePoint =>
      (bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f).norm_coe_le_norm _
  exact (ae_eq_condExp_of_piSystem_setIntegral_eq hm future_integrable predicted_integrable
    predicted_measurable.aestronglyMeasurable (data.generator s) (data.generator_pi s)
    (data.generator_eq s) (data.total_transition s t ht f)
    (data.generator_transition s t ht f)).symm

omit [FiniteDimensional ℝ E] in
/-- Forget the pi-system presentation after the generic closure theorem has constructed the exact
universal full-past semantics. -/
noncomputable def TwoDimensionalSelectedLoopFullPastPiSystemMarkovData.toFullPastMarkovData
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    {bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω)}
    (data : TwoDimensionalSelectedLoopFullPastPiSystemMarkovData bridge) :
    TwoDimensionalSelectedLoopFullPastMarkovData bridge where
  fullPastWeakMarkov :=
    bridge.fullPastConditionalMarkov_iff_weakMarkov.mp data.fullPastConditionalMarkov

omit [FiniteDimensional ℝ E] in
/-- Every proved bounded measurable finite process cylinder is measurable for the exact past and
satisfies the full-past testing identity. The remaining debt is extending from these cylinders to
all bounded functions measurable for the generated past sigma-algebra. -/
theorem TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData.finitePastCylinder_satisfies_fullPastTest
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}
    (bridge : TwoDimensionalSelectedLoopSpectralBrownianGeneratorBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData) (Ω := Ω))
    (s t : NNReal) (ht : 0 < t)
    (n : ℕ) (times : Fin (n + 2) → NNReal) (times_monotone : Monotone times)
    (times_zero : times 0 = 0)
    (history_le : ∀ i : Fin n, times i.succ.castSucc ≤ s)
    (current_time : times (Fin.last n).castSucc = s)
    (future_time : times (Fin.last (n + 1)) = s + t)
    (test : (Fin n → G) → ℝ) (test_measurable : Measurable test)
    (bound : ℝ) (test_bound : ∀ history, ‖test history‖ ≤ bound)
    (f : C(G, ℝ)) :
    @Measurable Ω ℝ
        (twoDimensionalSelectedLoopPastMeasurableSpace bridge.brownian s) _
        (twoDimensionalFinitePastProcessTest bridge.brownian n times test) ∧
      (∫ samplePoint,
        twoDimensionalFinitePastProcessTest bridge.brownian n times test samplePoint *
          f (bridge.brownian.process (s + t) samplePoint)
        ∂bridge.brownian.probabilityMeasure) =
      ∫ samplePoint,
        twoDimensionalFinitePastProcessTest bridge.brownian n times test samplePoint *
          bridge.spectralHeatKernel.kernelOperator.heatOperator (t : ℝ) f
            (bridge.brownian.process s samplePoint)
        ∂bridge.brownian.probabilityMeasure := by
  refine ⟨bridge.brownian.finitePastProcessTest_measurable_past
    s n times history_le test test_measurable, ?_⟩
  have final_time :
      times (Fin.last (n + 1)) = times (Fin.last n).castSucc + t := by
    rw [future_time, current_time]
  have identity := bridge.finiteProcessHistory_boundedMeasurable_weakMarkov_identity
    n times times_monotone times_zero t ht final_time
      test test_measurable bound test_bound f
  rw [current_time, future_time] at identity
  exact identity

end

end YangMills.Dimensions
