/-
Copyright (c) 2026 YangMillsDefinition contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: YangMillsDefinition contributors
-/
import YangMills.Dimensions.TwoDimensionalSelectedLoopSpectralHeatKernelBridge

/-!
# Hostile probes for the selected-loop spectral heat-kernel bridge
-/

namespace YangMills
namespace Dimensions
namespace TwoDimensionalSelectedLoopSpectralHeatKernelBridge
namespace Probes

open MeasureTheory
open YangMills.Mathematics
open scoped Manifold ContDiff

noncomputable section

universe uE uG uGauge uSample uConnection

variable
    {E : Type uE} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [FiniteDimensional ℝ E]
    {G : Type uG} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [SecondCountableTopology G]
    [MeasurableSpace G] [BorelSpace G] [ChartedSpace E G]
    [LieGroup (modelWithCornersSelf ℝ E) ∞ G]
    {Gauge : Type uGauge} [Group Gauge]
    {Sample : Type uSample} [MeasurableSpace Sample]
    {Connection : Type uConnection}
    {base : TwoDimensionalGaugeFixedHolonomyMeasureData G Gauge Sample Connection}
    {law : TwoDimensionalSelectedLoopHaarDensityLawData base}
    {inner : Geometry.InvariantInnerProductData
      (I := modelWithCornersSelf ℝ E) (G := G)}
    {realLaplacian : RightInvariantPairingLaplacianData inner}
    {complexLaplacian : RightInvariantPairingComplexLaplacianData inner}
    {heatTraceData : UnitaryMatrixDualHeatTraceSummabilityData (G := G)}

/-- The connected operator uses the exact heat core derived from the spectral density. -/
noncomputable def exact_kernel_operator
    (bridge : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData)) :
    TwoDimensionalSelectedLoopHeatKernelOperatorData bridge.heatEquationCore :=
  bridge.kernelOperator

omit [FiniteDimensional ℝ E] in
/-- Driver's operator formula uses the exact spectral real density and `h⁻¹ * g` order. -/
theorem exact_spectral_kernel_formula
    (bridge : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    bridge.kernelOperator.heatOperator t f g =
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
        ∂normalizedCompactHaarMeasure G := by
  simpa only [TwoDimensionalSelectedLoopSpectralHeatEquationBridgeData.toHeatEquationCoreData]
    using bridge.kernelOperator.heatOperator_eq_kernelIntegral t ht f g

omit [FiniteDimensional ℝ E] in
/-- The connected operator is generated by the unchanged real pairing Laplacian. -/
theorem exact_spectral_operator_generator
    (bridge : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) :
    HasDerivAt (fun s => bridge.kernelOperator.heatOperator s f g)
      ((1 / 2 : ℝ) * realLaplacian.laplacian
        (bridge.kernelOperator.positiveTimeSmooth t ht f) g) t :=
  bridge.kernelOperator.heatOperator_hasDerivAt t ht f g

omit [FiniteDimensional ℝ E] in
/-- Hostile kernel probe: replacing Driver's exact spectral integral by a changed value is
contradictory. -/
theorem changed_spectral_kernel_formula_blocked
    (bridge : TwoDimensionalSelectedLoopSpectralHeatKernelBridgeData
      (law := law) (inner := inner) (realLaplacian := realLaplacian)
      (complexLaplacian := complexLaplacian) (heatTraceData := heatTraceData))
    (t : ℝ) (ht : 0 < t) (f : C(G, ℝ)) (g : G) (changed : ℝ)
    (hchanged : changed ≠
      ∫ h, unitaryMatrixDualCasimirHeatDensityReal heatTraceData t (h⁻¹ * g) * f h
        ∂normalizedCompactHaarMeasure G)
    (changedFormula : bridge.kernelOperator.heatOperator t f g = changed) : False := by
  apply hchanged
  rw [← changedFormula]
  exact exact_spectral_kernel_formula bridge t ht f g

end

end Probes
end TwoDimensionalSelectedLoopSpectralHeatKernelBridge
end Dimensions
end YangMills
