/-
Copyright (c) 2026 Sebastian Rodrigo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/

import YangMills.Minkowski.PoincareCoverRepresentation

/-!
# Poincaré-invariant unique vacuum interface

Streater–Wightman, printed p. 97, axiom `0`, requires a vacuum vector invariant under the same
continuous unitary Poincaré representation and unique up to phase. This module packages that exact
connection: invariance is defined using the already supplied representation `U`, and the complete
invariant-vector subspace is required to be the complex line generated by one normalized vacuum.

Physical translation invariance is derived by restricting that same `U`; no disconnected vacuum,
Hamiltonian, or surrogate translation action is accepted. No vacuum inhabitant, field cyclicity,
spectrum, existence theorem, or mass gap is constructed.
-/

namespace YangMills.Minkowski

/-- A vector invariant under every element of one exact Poincaré lift-group representation. -/
def IsPoincareInvariantVector
    {d : EuclideanDimension} {G : Type*}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {lift : ProperOrthochronousPoincareLiftData d G}
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [TopologicalSpace.SeparableSpace H]
    (U : StronglyContinuousUnitaryPoincareRepresentation lift H) (ψ : H) : Prop :=
  ∀ g : G, U.unitary g ψ = ψ

/-- One normalized Poincaré-invariant vacuum whose invariant-vector subspace is exactly its complex
line. -/
structure PoincareInvariantVacuumData
    {d : EuclideanDimension} {G : Type*}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {lift : ProperOrthochronousPoincareLiftData d G}
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [TopologicalSpace.SeparableSpace H]
    (U : StronglyContinuousUnitaryPoincareRepresentation lift H) where
  /-- The physical vacuum vector. -/
  vacuum : H
  /-- Unit normalization prevents a zero or arbitrarily scaled vacuum witness. -/
  norm_eq_one : ‖vacuum‖ = 1
  /-- The same Poincaré representation fixes the vacuum. -/
  invariant : IsPoincareInvariantVector U vacuum
  /-- Every vector fixed by that representation lies on the same vacuum line. -/
  invariant_line : ∀ ψ : H, IsPoincareInvariantVector U ψ →
    ∃ c : ℂ, ψ = c • vacuum

/-- A normalized vacuum is nonzero. -/
theorem PoincareInvariantVacuumData.vacuum_ne_zero
    {d : EuclideanDimension} {G : Type*}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {lift : ProperOrthochronousPoincareLiftData d G}
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [TopologicalSpace.SeparableSpace H]
    {U : StronglyContinuousUnitaryPoincareRepresentation lift H}
    (vacuumData : PoincareInvariantVacuumData U) : vacuumData.vacuum ≠ 0 := by
  intro hzero
  have hnorm := vacuumData.norm_eq_one
  rw [hzero, norm_zero] at hnorm
  norm_num at hnorm

/-- The vacuum is invariant under every physical translation derived from the same representation. -/
theorem PoincareInvariantVacuumData.translation_invariant
    {d : EuclideanDimension} {G : Type*}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {lift : ProperOrthochronousPoincareLiftData d G}
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [TopologicalSpace.SeparableSpace H]
    {U : StronglyContinuousUnitaryPoincareRepresentation lift H}
    (vacuumData : PoincareInvariantVacuumData U) (a : Spacetime d) :
    U.translationUnitary a vacuumData.vacuum = vacuumData.vacuum :=
  vacuumData.invariant (lift.translation (Multiplicative.ofAdd a))

/-- Any other normalized invariant vector differs from the selected vacuum by a unit-modulus complex
phase. -/
theorem PoincareInvariantVacuumData.normalized_invariant_eq_phase_smul
    {d : EuclideanDimension} {G : Type*}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {lift : ProperOrthochronousPoincareLiftData d G}
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [TopologicalSpace.SeparableSpace H]
    {U : StronglyContinuousUnitaryPoincareRepresentation lift H}
    (vacuumData : PoincareInvariantVacuumData U)
    (ψ : H) (hψnorm : ‖ψ‖ = 1) (hψinv : IsPoincareInvariantVector U ψ) :
    ∃ c : ℂ, ‖c‖ = 1 ∧ ψ = c • vacuumData.vacuum := by
  rcases vacuumData.invariant_line ψ hψinv with ⟨c, rfl⟩
  refine ⟨c, ?_, rfl⟩
  rw [norm_smul, vacuumData.norm_eq_one, mul_one] at hψnorm
  exact hψnorm

end YangMills.Minkowski
